# Generated by Django 3.1.7 on 2021-03-26 09:48

from django.db import migrations

import isc_common.fields.code_field


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0010_jasper_reports_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasper_reports',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
    ]
