
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-04T09:10:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a220b531bbeffd973fddcda3f6e44b5d7b669141",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
