# Generated by Django 3.1.7 on 2021-03-26 09:48

from django.db import migrations

import isc_common.fields.code_field


class Migration(migrations.Migration):
    dependencies = [
        ('isc_common', '0088_auto_20210323_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_types',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
        migrations.AlterField(
            model_name='standard_colors',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
    ]
