# Generated by Django 3.2 on 2021-04-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('isc_common', '0093_auto_20210406_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debug',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
