# Generated by Django 3.2.3 on 2021-05-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0098_alter_images_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='real_name',
            field=models.TextField(db_index=True, unique=True, verbose_name='Первоначальное имя файла'),
        ),
    ]
