
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-03T11:26:07+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "82d4d018f8d51ba93becd2dd53a5fc1d6e49be18",
 "version": "0.2.36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
