# Generated by Django 3.2.8 on 2022-02-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_auto_20220131_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='usr',
            new_name='user',
        ),
    ]
