
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-02T11:52:38+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "903df3a76983850ae038b977a76cc1f13a600dbd",
 "version": "0.5.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
