# Generated by Django 3.2.6 on 2021-08-23 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('isc_common', '0110_alter_images_unique_together'),
    ]

    operations = [
    ]
