from . import config as config, formatter as formatter
from typing import Any, Dict, Iterable, Optional

logger: Any

def load_plugin(module: str, force: bool = ..., *, cache: Dict = ...) -> Optional['Plugin']: ...
def get_names() -> Iterable[str]: ...
def search_plugins(*modules, force: bool = ...): ...

class Plugin:
    formatters: Any
    config_loaders: Any
    configs: Any
    def __init__(self) -> None: ...
    def get_config(self): ...
    def add_arguments(self, parser) -> None: ...
    def parse_known_args(self, args, namespace): ...

class ProxyPlugin(Plugin):
    configs: Any
    def __init__(self, original) -> None: ...
