# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/iec61968/assetinfo/ShortCircuitTest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.protobuf.cim.iec61968.assetinfo import TransformerTest_pb2 as zepben_dot_protobuf_dot_cim_dot_iec61968_dot_assetinfo_dot_TransformerTest__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/protobuf/cim/iec61968/assetinfo/ShortCircuitTest.proto',
  package='zepben.protobuf.cim.iec61968.assetinfo',
  syntax='proto3',
  serialized_options=b'\n*com.zepben.protobuf.cim.iec61968.assetinfoP\001\252\002&Zepben.Protobuf.CIM.IEC61968.AssetInfo',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n=zepben/protobuf/cim/iec61968/assetinfo/ShortCircuitTest.proto\x12&zepben.protobuf.cim.iec61968.assetinfo\x1a<zepben/protobuf/cim/iec61968/assetinfo/TransformerTest.proto\"\xad\x02\n\x10ShortCircuitTest\x12\x43\n\x02tt\x18\x01 \x01(\x0b\x32\x37.zepben.protobuf.cim.iec61968.assetinfo.TransformerTest\x12\x0f\n\x07\x63urrent\x18\x02 \x01(\x01\x12\x18\n\x10\x65nergisedEndStep\x18\x03 \x01(\x05\x12\x17\n\x0fgroundedEndStep\x18\x04 \x01(\x05\x12\x18\n\x10leakageImpedance\x18\x05 \x01(\x01\x12\x1c\n\x14leakageImpedanceZero\x18\x06 \x01(\x01\x12\x0c\n\x04loss\x18\x07 \x01(\x05\x12\x10\n\x08lossZero\x18\x08 \x01(\x05\x12\r\n\x05power\x18\t \x01(\x05\x12\x0f\n\x07voltage\x18\n \x01(\x01\x12\x18\n\x10voltageOhmicPart\x18\x0b \x01(\x01\x42W\n*com.zepben.protobuf.cim.iec61968.assetinfoP\x01\xaa\x02&Zepben.Protobuf.CIM.IEC61968.AssetInfob\x06proto3'
  ,
  dependencies=[zepben_dot_protobuf_dot_cim_dot_iec61968_dot_assetinfo_dot_TransformerTest__pb2.DESCRIPTOR,])




_SHORTCIRCUITTEST = _descriptor.Descriptor(
  name='ShortCircuitTest',
  full_name='zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tt', full_name='zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest.tt', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current', full_name='zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest.current', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='energisedEndStep', full_name='zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest.energisedEndStep', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='groundedEndStep', full_name='zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest.groundedEndStep', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leakageImpedance', full_name='zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest.leakageImpedance', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leakageImpedanceZero', full_name='zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest.leakageImpedanceZero', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loss', full_name='zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest.loss', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lossZero', full_name='zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest.lossZero', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='power', full_name='zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest.power', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voltage', full_name='zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest.voltage', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voltageOhmicPart', full_name='zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest.voltageOhmicPart', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=469,
)

_SHORTCIRCUITTEST.fields_by_name['tt'].message_type = zepben_dot_protobuf_dot_cim_dot_iec61968_dot_assetinfo_dot_TransformerTest__pb2._TRANSFORMERTEST
DESCRIPTOR.message_types_by_name['ShortCircuitTest'] = _SHORTCIRCUITTEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShortCircuitTest = _reflection.GeneratedProtocolMessageType('ShortCircuitTest', (_message.Message,), {
  'DESCRIPTOR' : _SHORTCIRCUITTEST,
  '__module__' : 'zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.cim.iec61968.assetinfo.ShortCircuitTest)
  })
_sym_db.RegisterMessage(ShortCircuitTest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
