# -*- coding: utf-8 -*-
r"""
contains constants for visualization
"""
SPINDEFAULT_TIPLENGTH: float = 1.0
SPINDEFAULT_TIPRADIUS: float = 0.35
SPINDEFAULT_ARROWSCALE: float = 0.7
SPINDEFAULT_DRAWBACKGROUND: bool = False
SPINDEFAULT_SETTINGS={'tiplength':SPINDEFAULT_TIPLENGTH,'tipradius':SPINDEFAULT_TIPRADIUS,'arrowscale':SPINDEFAULT_ARROWSCALE, 'drawbackground':SPINDEFAULT_DRAWBACKGROUND}

EVECDEFAULT_TIPLENGTH: float = 0.4
EVECDEFAULT_TIPRADIUS: float = 0.25
EVECDEFAULT_ARROWSCALE: float = 20.0
EVECDEFAULT_DRAWBACKGROUND: bool = True
EVECDEFAULT_SETTINGS={'tiplength':EVECDEFAULT_TIPLENGTH,'tipradius':EVECDEFAULT_TIPRADIUS,'arrowscale':EVECDEFAULT_ARROWSCALE, 'drawbackground':EVECDEFAULT_DRAWBACKGROUND}
