from aioworkers.worker.subprocess import Subprocess as Subprocess
from typing import Any

class BaseUpdater(Subprocess):
    def set_config(self, config) -> None: ...
    async def can_restart(self): ...
    async def wait_restart(self) -> None: ...
    async def restart(self) -> None: ...
    async def can_update(self): ...
    async def update(self) -> None: ...
    async def run(self, value: Any | None = ...) -> None: ...

class PipUpdater(BaseUpdater):
    pip: Any
    current_version: Any
    new_version: Any
    def set_config(self, config) -> None: ...
    async def can_update(self): ...
    @classmethod
    def version(cls, package): ...
    async def update(self) -> None: ...
