
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-07T13:54:05-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5e78af47c393ba3c5f557ef32efcb3f076007cf",
 "version": "2022.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
