
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-02T11:12:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a66ae0c935016d5c6552ac32f847f30fdce65708",
 "version": "2022.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
