# Generated by Django 3.2.6 on 2021-08-30 14:40

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0093_alter_messages_files_size'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='messages_theme',
            constraint=models.CheckConstraint(check=models.Q(('id', django.db.models.expressions.F('parent_id')), _negated=True), name='c_Messages_theme'),
        ),
    ]
