from typing import Any

class CommandNotFound(RuntimeError): ...

def kwargs_from_argv(params, ns, argv): ...
def run(cmd, context, loop: Any | None = ..., ns: Any | None = ..., argv: Any | None = ...): ...
