
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-05T19:07:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f9ca266b8ff91aa090ad3291bff188815af603b",
 "version": "6.15.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
