# file stubs/ogdf/fast_multipole_embedder/LinearQuadtree/LQNode.py generated from structogdf_1_1fast__multipole__embedder_1_1_linear_quadtree_1_1_l_q_node
import enum
from typing import *
from ogdf_python import ogdf, cpp
std = cpp.std
class LQNode(object):

	child : NodeID = ...

	fence : bool = ...

	firstPoint : PointID = ...

	level : int = ...

	next : NodeID = ...

	numChilds : int = ...

	numPoints : int = ...
