# Generated by Django 4.0.1 on 2022-01-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_scopedsettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopedsettings',
            options={'ordering': ['namespace', 'key', 'scope'], 'permissions': [('change_own_user_settings', "Can change own user's Scoped settings"), ('change_own_client_settings', "Can change own client's Scoped settings")], 'verbose_name': 'Scoped settings', 'verbose_name_plural': 'Scoped settings'},
        ),
    ]
