#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['asyncstdlib']

package_data = \
{'': ['*']}

extras_require = \
{":python_version<'3.8'": ['typing_extensions'],
 'doc': ['sphinx', 'sphinxcontrib-trio'],
 'test': ['pytest',
          'flake8',
          'flake8-bugbear',
          'coverage',
          'pytest-cov',
          'flake8-2020'],
 "test:implementation_name=='cpython'": ['black', 'mypy']}

setup(name='asyncstdlib',
      version='3.10.3',
      description='The missing async toolbox',
      author='Max Fischer',
      author_email='maxfischer2781@gmail.com',
      url='https://github.com/maxfischer2781/asyncstdlib',
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      python_requires='~=3.6',
     )
