from django.db import models


class Matches(models.Model):
    match_id = models.IntegerField(primary_key=True)
    tournament_id = models.IntegerField()
    h1_id = models.IntegerField(blank=True, null=True)
    h2_id = models.IntegerField(blank=True, null=True)
    h3_id = models.IntegerField(blank=True, null=True)
    h4_id = models.IntegerField(blank=True, null=True)
    h5_id = models.IntegerField(blank=True, null=True)
    h6_id = models.IntegerField(blank=True, null=True)
    h7_id = models.IntegerField(blank=True, null=True)
    h8_id = models.IntegerField(blank=True, null=True)
    h9_id = models.IntegerField(blank=True, null=True)
    h10_id = models.IntegerField(blank=True, null=True)
    h11_id = models.IntegerField(blank=True, null=True)
    h12_id = models.IntegerField(blank=True, null=True)
    h13_id = models.IntegerField(blank=True, null=True)
    h14_id = models.IntegerField(blank=True, null=True)
    h15_id = models.IntegerField(blank=True, null=True)
    h16_id = models.IntegerField(blank=True, null=True)
    h17_id = models.IntegerField(blank=True, null=True)
    h18_id = models.IntegerField(blank=True, null=True)
    h19_id = models.IntegerField(blank=True, null=True)
    h20_id = models.IntegerField(blank=True, null=True)
    a1_id = models.IntegerField(blank=True, null=True)
    a2_id = models.IntegerField(blank=True, null=True)
    a3_id = models.IntegerField(blank=True, null=True)
    a4_id = models.IntegerField(blank=True, null=True)
    a5_id = models.IntegerField(blank=True, null=True)
    a6_id = models.IntegerField(blank=True, null=True)
    a7_id = models.IntegerField(blank=True, null=True)
    a8_id = models.IntegerField(blank=True, null=True)
    a9_id = models.IntegerField(blank=True, null=True)
    a10_id = models.IntegerField(blank=True, null=True)
    a11_id = models.IntegerField(blank=True, null=True)
    a12_id = models.IntegerField(blank=True, null=True)
    a13_id = models.IntegerField(blank=True, null=True)
    a14_id = models.IntegerField(blank=True, null=True)
    a15_id = models.IntegerField(blank=True, null=True)
    a16_id = models.IntegerField(blank=True, null=True)
    a17_id = models.IntegerField(blank=True, null=True)
    a18_id = models.IntegerField(blank=True, null=True)
    a19_id = models.IntegerField(blank=True, null=True)
    a20_id = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'matches'
