from enum import Enum


class SensorType(str, Enum):
    PERCENTAGE = 'PERCENTAGE',
    TEMPERATURE = 'TEMPERATURE',
    COUNT = 'COUNT',
    DISTANCE = 'DISTANCE',
    TIMESTAMP = 'TIMESTAMP',
    IDENTIFIER = 'IDENTIFIER',
    HUMIDITY = 'HUMIDITY',
    CONCENTRATION = 'CONCENTRATION'
    LASER_POWER = 'LASER_POWER'
