# file stubs/ogdf/GraphIO/FileType.py generated from structogdf_1_1_graph_i_o_1_1_file_type
import enum
from typing import *
from ogdf_python import ogdf, cpp
std = cpp.std
class FileType(object):

	attr_reader_func : AttrReaderFunc = ...

	attr_writer_func : AttrWriterFunc = ...

	auto_attr_reader_func : AttrReaderFunc = ...

	auto_cluster_attr_reader_func : ClusterAttrReaderFunc = ...

	auto_cluster_reader_func : ClusterReaderFunc = ...

	auto_reader_func : ReaderFunc = ...

	cluster_attr_reader_func : ClusterAttrReaderFunc = ...

	cluster_attr_writer_func : ClusterAttrWriterFunc = ...

	cluster_reader_func : ClusterReaderFunc = ...

	cluster_writer_func : ClusterWriterFunc = ...

	extensions : List[ str ] = ...

	reader_func : ReaderFunc = ...

	writer_func : WriterFunc = ...

	def __init__(self, extensions : List[ str ], readerFunc : ReaderFunc = None, writerFunc : WriterFunc = None, attrReaderFunc : AttrReaderFunc = None, attrWriterFunc : AttrWriterFunc = None, clusterReaderFunc : ClusterReaderFunc = None, clusterWriterFunc : ClusterWriterFunc = None, clusterAttrReaderFunc : ClusterAttrReaderFunc = None, clusterAttrWriterFunc : ClusterAttrWriterFunc = None) -> None:
		...

	def replaceAutoReaders(self, readerFunc : ReaderFunc = None, attrReaderFunc : AttrReaderFunc = None, clusterReaderFunc : ClusterReaderFunc = None, clusterAttrReaderFunc : ClusterAttrReaderFunc = None) -> FileType:
		...
