# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ApplicationEndpointConfiguration(Model):
    """ApplicationEndpointConfiguration.

    :param type: Possible values include: 'Jupyter', 'JupyterLab', 'SSH',
     'TensorBoard', 'VSCode', 'Theia', 'Grafana', 'Custom'
    :type type: str or ~designer.models.ApplicationEndpointType
    :param port:
    :type port: int
    :param properties:
    :type properties: dict[str, str]
    """

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'port': {'key': 'port', 'type': 'int'},
        'properties': {'key': 'properties', 'type': '{str}'},
    }

    def __init__(self, *, type=None, port: int=None, properties=None, **kwargs) -> None:
        super(ApplicationEndpointConfiguration, self).__init__(**kwargs)
        self.type = type
        self.port = port
        self.properties = properties
