# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DataSettings(Model):
    """DataSettings.

    :param target_column_name:
    :type target_column_name: str
    :param weight_column_name:
    :type weight_column_name: str
    :param validation_data:
    :type validation_data: ~designer.models.ValidationDataSettings
    :param test_data:
    :type test_data: ~designer.models.TestDataSettings
    """

    _attribute_map = {
        'target_column_name': {'key': 'targetColumnName', 'type': 'str'},
        'weight_column_name': {'key': 'weightColumnName', 'type': 'str'},
        'validation_data': {'key': 'validationData', 'type': 'ValidationDataSettings'},
        'test_data': {'key': 'testData', 'type': 'TestDataSettings'},
    }

    def __init__(self, **kwargs):
        super(DataSettings, self).__init__(**kwargs)
        self.target_column_name = kwargs.get('target_column_name', None)
        self.weight_column_name = kwargs.get('weight_column_name', None)
        self.validation_data = kwargs.get('validation_data', None)
        self.test_data = kwargs.get('test_data', None)
