# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class FeedDtoSupportedAssetTypes(Model):
    """FeedDtoSupportedAssetTypes.

    :param component:
    :type component: ~designer.models.AssetTypeMetaInfo
    :param model:
    :type model: ~designer.models.AssetTypeMetaInfo
    :param environment:
    :type environment: ~designer.models.AssetTypeMetaInfo
    :param dataset:
    :type dataset: ~designer.models.AssetTypeMetaInfo
    :param data_store:
    :type data_store: ~designer.models.AssetTypeMetaInfo
    :param sample_graph:
    :type sample_graph: ~designer.models.AssetTypeMetaInfo
    """

    _attribute_map = {
        'component': {'key': 'Component', 'type': 'AssetTypeMetaInfo'},
        'model': {'key': 'Model', 'type': 'AssetTypeMetaInfo'},
        'environment': {'key': 'Environment', 'type': 'AssetTypeMetaInfo'},
        'dataset': {'key': 'Dataset', 'type': 'AssetTypeMetaInfo'},
        'data_store': {'key': 'DataStore', 'type': 'AssetTypeMetaInfo'},
        'sample_graph': {'key': 'SampleGraph', 'type': 'AssetTypeMetaInfo'},
    }

    def __init__(self, **kwargs):
        super(FeedDtoSupportedAssetTypes, self).__init__(**kwargs)
        self.component = kwargs.get('component', None)
        self.model = kwargs.get('model', None)
        self.environment = kwargs.get('environment', None)
        self.dataset = kwargs.get('dataset', None)
        self.data_store = kwargs.get('data_store', None)
        self.sample_graph = kwargs.get('sample_graph', None)
