# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ICheckableLongRunningOperationResponse1(Model):
    """ICheckableLongRunningOperationResponse1.

    :param completion_result:
    :type completion_result: object
    :param location:
    :type location: str
    :param operation_result:
    :type operation_result: str
    """

    _attribute_map = {
        'completion_result': {'key': 'completionResult', 'type': 'object'},
        'location': {'key': 'location', 'type': 'str'},
        'operation_result': {'key': 'operationResult', 'type': 'str'},
    }

    def __init__(self, *, completion_result=None, location: str=None, operation_result: str=None, **kwargs) -> None:
        super(ICheckableLongRunningOperationResponse1, self).__init__(**kwargs)
        self.completion_result = completion_result
        self.location = location
        self.operation_result = operation_result
