# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ParsedAssetMetaInfo(Model):
    """ParsedAssetMetaInfo.

    :param name:
    :type name: str
    :param version:
    :type version: str
    :param family_id:
    :type family_id: str
    :param root_blob_uri:
    :type root_blob_uri: str
    :param serialized_asset_info:
    :type serialized_asset_info: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'version': {'key': 'version', 'type': 'str'},
        'family_id': {'key': 'familyId', 'type': 'str'},
        'root_blob_uri': {'key': 'rootBlobUri', 'type': 'str'},
        'serialized_asset_info': {'key': 'serializedAssetInfo', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(ParsedAssetMetaInfo, self).__init__(**kwargs)
        self.name = kwargs.get('name', None)
        self.version = kwargs.get('version', None)
        self.family_id = kwargs.get('family_id', None)
        self.root_blob_uri = kwargs.get('root_blob_uri', None)
        self.serialized_asset_info = kwargs.get('serialized_asset_info', None)
