# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Relationship(Model):
    """Relationship.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param relation_type:
    :type relation_type: str
    :param target_entity_id:
    :type target_entity_id: str
    :ivar entity_type:
    :vartype entity_type: str
    :ivar entity_container_id:
    :vartype entity_container_id: str
    """

    _validation = {
        'entity_type': {'readonly': True},
        'entity_container_id': {'readonly': True},
    }

    _attribute_map = {
        'relation_type': {'key': 'relationType', 'type': 'str'},
        'target_entity_id': {'key': 'targetEntityId', 'type': 'str'},
        'entity_type': {'key': 'entityType', 'type': 'str'},
        'entity_container_id': {'key': 'entityContainerId', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(Relationship, self).__init__(**kwargs)
        self.relation_type = kwargs.get('relation_type', None)
        self.target_entity_id = kwargs.get('target_entity_id', None)
        self.entity_type = None
        self.entity_container_id = None
