# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SparkJarTaskDto(Model):
    """SparkJarTaskDto.

    :param main_class_name:
    :type main_class_name: str
    :param parameters:
    :type parameters: list[str]
    """

    _attribute_map = {
        'main_class_name': {'key': 'main_class_name', 'type': 'str'},
        'parameters': {'key': 'parameters', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(SparkJarTaskDto, self).__init__(**kwargs)
        self.main_class_name = kwargs.get('main_class_name', None)
        self.parameters = kwargs.get('parameters', None)
