# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ValidationDataSettings(Model):
    """ValidationDataSettings.

    :param n_cross_validations:
    :type n_cross_validations: int
    :param validation_data_size:
    :type validation_data_size: float
    :param cv_split_column_names:
    :type cv_split_column_names: list[str]
    """

    _attribute_map = {
        'n_cross_validations': {'key': 'nCrossValidations', 'type': 'int'},
        'validation_data_size': {'key': 'validationDataSize', 'type': 'float'},
        'cv_split_column_names': {'key': 'cvSplitColumnNames', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(ValidationDataSettings, self).__init__(**kwargs)
        self.n_cross_validations = kwargs.get('n_cross_validations', None)
        self.validation_data_size = kwargs.get('validation_data_size', None)
        self.cv_split_column_names = kwargs.get('cv_split_column_names', None)
