from . import isp_info
from . import telecom_mixin
from . import contract
from . import crm_lead
from . import crm_lead_line
from . import previous_provider
from . import product_product
from . import product_template
from . import res_company
from . import res_config_settings
from . import sale_order
from . import service_supplier
from . import service_technology
from . import sub_state
