# Generated by Django 3.1.7 on 2021-03-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recreated_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.BigIntegerField()),
                ('old_urls', models.CharField(db_index=True, max_length=767)),
                ('new_urls', models.CharField(db_index=True, max_length=767, unique=True)),
            ],
            options={
                'db_table': 'recreated_urls',
            },
        ),
    ]
