info = {"message": "Update LS version", "commit": "1a5caacf3d319bbf843ac2fb0541f378473116cf", "date": "2022-02-04 02:11:30 +0300", "branch": "release/1.4.1", "version": "1.4.0+143.g1a5caacf.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
