# Generated by Django 3.1.6 on 2021-02-18 11:31

import django.utils.timezone
from django.db import migrations, models

import isc_common.fields.code_field


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0064_phones'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_mails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('phone', isc_common.fields.code_field.CodeStrictField()),
            ],
            options={
                'verbose_name': 'Почтовые адреса',
            },
        ),
    ]
