# Generated by Django 3.2.4 on 2021-06-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('isc_common', '0101_auto_20210517_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='size',
            field=models.BigIntegerField(default=0, verbose_name='Размер файла'),
        ),
    ]
