# file stubs/ogdf/MMVariableEmbeddingInserter/Block.py generated from classogdf_1_1_m_m_variable_embedding_inserter_1_1_block
import enum
from typing import *
from ogdf_python import ogdf, cpp
std = cpp.std
class Block(ogdf.Graph):

	m_adjBCtoG : AdjEntryArray[adjEntry] = ...

	m_forbidden : EdgeArray[ bool ] = ...

	m_isSource : NodeArray[ bool ] = ...

	m_isSplittable : NodeArray[ bool ] = ...

	m_isTarget : NodeArray[ bool ] = ...

	m_PG : PlanRepExpansion = ...

	m_pT : StaticPlanarSPQRTree = ...

	m_vBCtoG : NodeArray[node] = ...

	def __init__(self, PG : PlanRepExpansion) -> None:
		...

	def __destruct__(self) -> None:
		...

	def containsSource(self, v : node) -> node:
		...

	def containsSourceAdj(self, v : node) -> adjEntry:
		...

	def containsTarget(self, v : node) -> node:
		...

	def containsTargetAdj(self, v : node) -> adjEntry:
		...

	def __assign__(self, _ : Block) -> Block:
		...
