
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-07T16:11:47-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7518e2e0fd78286216d5bba96618d314c01e6ed1",
 "version": "v0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
