"""
fgo信息猜从者的格式：
在avatar_info的dict中
（每个名称均得带有引号，作为string（文本型）！）
"1": {"name": "xxxx",   //从者真实名字
            "other_name": ["x1", "x2", "x3", "x4", "x5"],  //从者别名
            "height": "123cm",  //从者身高
            "weight": "42kg",  //从者体重
            "stair": "xx",  //从者职介
            "like": "unknown",  //从者喜欢的事物
            "dislike": "unknown"}  //从者不喜欢的事物
"""

avatar_info = {
    "1": {"name": "阿尔托莉雅潘德拉贡",
          "other_name": ["呆毛", "Saber", "吾王", "棉被", "棉被王"],
          "height": "154cm",
          "weight": "42kg",
          "stair": "Saber",
          "like": "unknown",
          "dislike": "unknown"},
    "2": {"name": "玛修基列莱特",
          "other_name": ["盾娘", "学妹", "玛修"],
          "height": "158cm",
          "weight": "46kg",
          "stair": "Extra",
          "like": "天空的色彩，大地的气味",
          "dislike": "没有"},
    "3": {"name": "尼禄克劳狄乌斯",
          "other_name": ["尼禄", "红Saber", "殿下", "唔姆"],
          "height": "150cm",
          "weight": "42kg",
          "stair": "Saber",
          "like": "自己",
          "dislike": "节制，反叛，没落"},
    "4": {"name": "齐格飞",
          "other_name": ["对不起"],
          "height": "190cm",
          "weight": "80kg",
          "stair": "Saber",
          "like": "正义",
          "dislike": "邪恶"},
    "5": {"name": "凯撒",
          "other_name": ["胖罗马"],
          "height": "168cm",
          "weight": "154kg",
          "stair": "Saber",
          "like": "女人，罗马，世界",
          "dislike": "Saber职阶的自己"},
    "6": {"name": "阿蒂拉",
          "other_name": ["大王"],
          "height": "160cm",
          "weight": "48kg",
          "stair": "Saber",
          "like": "战斗",
          "dislike": "只会破坏的自己"},
    "7": {"name": "吉尔德雷",
          "other_name": ["吉尔", "元帅"],
          "height": "186cm",
          "weight": "91kg",
          "stair": "Saber",
          "like": "孩子",
          "dislike": "未知"},
    "8": {"name": "骑士迪昂",
          "other_name": ["迪昂"],
          "height": "157cm",
          "weight": "49kg",
          "stair": "Saber",
          "like": "御主",
          "dislike": "被人嘲笑"},
    "9": {"name": "卫宫",
          "other_name": ["红A", "Aimer", ],
          "height": "187cm",
          "weight": "78kg",
          "stair": "Archer",
          "like": "整备武器和厨房",
          "dislike": "不成熟的自己"},
    "10": {"name": "吉尔伽美什",
           "other_name": ["闪闪", "金闪闪", "英雄王", "金皮卡"],
           "height": "182cm",
           "weight": "68kg",
           "stair": "Archer",
           "like": "所有的财宝",
           "dislike": "挑战自己极限的生命"},
    "11": {"name": "罗宾汉",
           "other_name": ["绿茶"],
           "height": "175cm",
           "weight": "65kg",
           "stair": "Archer",
           "like": "搭讪",
           "dislike": "骑士道"},
    "12": {"name": "阿塔兰忒",
           "other_name": ["塔喵"],
           "height": "166cm",
           "weight": "57kg",
           "stair": "Archer",
           "like": "孩子",
           "dislike": "伤害孩子的人"},
    "13": {"name": "尤瑞艾莉",
           "other_name": ["二姐"],
           "height": "134cm",
           "weight": "30kg",
           "stair": "Archer",
           "like": "姐姐和妹妹",
           "dislike": "人"},
    "14": {"name": "阿拉什",
           "other_name": ["大英雄"],
           "height": "185cm",
           "weight": "75kg",
           "stair": "Archer",
           "like": "鸡心豆面糊",
           "dislike": "为用尽全力就结束的战斗"},
    "15": {"name": "库丘林",
           "other_name": ["大狗", "蓝色枪兵"],
           "height": "185cm",
           "weight": "72kg",
           "stair": "Lancer",
           "like": "强势的女人",
           "dislike": "背叛的家伙"},
    "16": {"name": "伊丽莎白",
           "other_name": ["红Lancer", "龙娘"],
           "height": "154cm",
           "weight": "44kg",
           "stair": "Lancer",
           "like": "偶像",
           "dislike": "逃跑，反叛，顶嘴"},
    "17": {"name": "武藏坊弁庆",
           "other_name": ["对不起我真的想不出来他有什么别称"],
           "height": "199cm",
           "weight": "88kg",
           "stair": "Lancer",
           "like": "般若汤",
           "dislike": "生气的大人"},
    "18": {"name": "列奥尼达",
           "other_name": ["炎头", "斯巴达"],
           "height": "188cm",
           "weight": "110kg",
           "stair": "Lancer",
           "like": "数学",
           "dislike": "没有脑子的人"},
    "19": {"name": "罗慕路斯",
           "other_name": ["神祖"],
           "height": "190cm",
           "weight": "140kg",
           "stair": "Lancer",
           "like": "罗马",
           "dislike": "非罗马"},
    "20": {"name": "美杜莎",
           "other_name": ["r姐"],
           "height": "172cm",
           "weight": "57kg",
           "stair": "Rider",
           "like": "读书，游泳",
           "dislike": "祖母绿，裙带菜"},
    "21": {"name": "乔尔乔斯",
           "other_name": ["乔老师"],
           "height": "180cm",
           "weight": "95kg",
           "stair": "Rider",
           "like": "用照相机摄影",
           "dislike": "谎言，虚伪"},
    "22": {"name": "爱德华蒂奇",
           "other_name": ["黑胡子"],
           "height": "210cm",
           "weight": "114kg",
           "stair": "Rider",
           "like": "与孩子玩耍",
           "dislike": "没有"},
    "23": {"name": "布狄卡",
           "other_name": ["布妈"],
           "height": "174cm",
           "weight": "62kg",
           "stair": "Rider",
           "like": "美味的食物",
           "dislike": "罗马"},
    "24": {"name": "牛若丸",
           "other_name": ["牛肉丸"],
           "height": "168cm",
           "weight": "55kg",
           "stair": "Rider",
           "like": "兄长",
           "dislike": "登高"},
    "25": {"name": "亚历山大",
           "other_name": ["幼帝"],
           "height": "151cm",
           "weight": "40kg",
           "stair": "Rider",
           "like": "书，马，希腊，海",
           "dislike": "没有"},
    "26": {"name": "玛丽",
           "other_name": ["蛋糕"],
           "height": "160cm",
           "weight": "48kg",
           "stair": "Rider",
           "like": "泡澡",
           "dislike": "断头台"},
    "27": {"name": "玛尔达",
           "other_name": ["圣女", "铁拳圣女"],
           "height": "161cm",
           "weight": "49kg",
           "stair": "Rider",
           "like": "御主能得到神的爱怜",
           "dislike": "没有"},
    "28": {"name": "美狄亚",
           "other_name": ["C妈"],
           "height": "163cm",
           "weight": "51kg",
           "stair": "Caster",
           "like": "瓶中船",
           "dislike": "只有脸的男人"},
    "29": {"name": "安徒生",
           "other_name": ["安徒生"],
           "height": "146cm",
           "weight": "39kg",
           "stair": "Caster",
           "like": "工作完成的瞬间",
           "dislike": "正在工作的时间"},
    "30": {"name": "莎士比亚",
           "other_name": ["莎翁", "莎比"],
           "height": "180cm",
           "weight": "75kg",
           "stair": "Caster",
           "like": "语言与文字",
           "dislike": "凡人"},
    "31": {"name": "梅菲斯托菲勒斯",
           "other_name": ["小丑", "恶魔"],
           "height": "188cm",
           "weight": "78kg",
           "stair": "Caster",
           "like": "惊讶的表情",
           "dislike": "和平"},
    "32": {"name": "莫扎特",
           "other_name": ["莫扎特"],
           "height": "180cm",
           "weight": "65kg",
           "stair": "Caster",
           "like": "音乐",
           "dislike": "桑松"},
    "33": {"name": "诸葛孔明",
           "other_name": ["王妃", "孔明", "二世"],
           "height": "186cm",
           "weight": "68kg",
           "stair": "Caster",
           "like": "懂事的学生，安静的教室，脑子不是只有豆腐渣的同事",
           "dislike": "粗暴的男人，没品的男人，没梦想没霸气的男人，女人也一样"},
    "34": {"name": "佐佐木小次郎",
           "other_name": ["小次郎"],
           "height": "176cm",
           "weight": "63kg",
           "stair": "Assassin",
           "like": "挥舞刀剑",
           "dislike": "内心丑恶的存在"},
    "35": {"name": "咒腕哈桑",
           "other_name": ["咒腕"],
           "height": "215cm",
           "weight": "65kg",
           "stair": "Assassin",
           "like": "整齐的房间",
           "dislike": "不具仁义忠诚的人"},
    "36": {"name": "斯忒若",
           "other_name": ["大姐"],
           "height": "134cm",
           "weight": "30kg",
           "stair": "Assassin",
           "like": "妹妹们",
           "dislike": "人类"},
    "37": {"name": "荆轲",
           "other_name": ["冠位刺客"],
           "height": "159cm",
           "weight": "48kg",
           "stair": "Assassin",
           "like": "美酒，明月，鲜花",
           "dislike": "家人"},
    "38": {"name": "桑松",
           "other_name": ["桑松"],
           "height": "178cm",
           "weight": "68kg",
           "stair": "Assassin",
           "like": "和平，幸福，慈爱",
           "dislike": "冤罪"},
    "39": {"name": "歌剧魅影",
           "other_name": ["歌剧"],
           "height": "185cm",
           "weight": "80kg",
           "stair": "Assassin",
           "like": "御主的声音",
           "dislike": "自己"},
    "40": {"name": "玛塔哈丽",
           "other_name": ["舞娘"],
           "height": "165cm",
           "weight": "49kg",
           "stair": "Assassin",
           "like": "崇高之人",
           "dislike": "用权利做挡箭牌的人"},
    "41": {"name": "卡米拉",
           "other_name": ["大龙娘"],
           "height": "168cm",
           "weight": "49kg",
           "stair": "Assassin",
           "like": "少女的鲜血",
           "dislike": "自己"},
    "42": {"name": "赫拉克勒斯",
           "other_name": ["b叔"],
           "height": "253cm",
           "weight": "311kg",
           "stair": "Berserker",
           "like": "？？？",
           "dislike": "？？？"},
    "43": {"name": "兰斯洛特",
           "other_name": ["狂兰", "长江骑士", "岳父"],
           "height": "191cm",
           "weight": "81kg",
           "stair": "Berserker",
           "like": "亚瑟",
           "dislike": "亚瑟"},
    "44": {"name": "吕布奉先",
           "other_name": ["吕布"],
           "height": "225cm",
           "weight": "153kg",
           "stair": "Berserker",
           "like": "？？？",
           "dislike": "？？？"},
    "45": {"name": "斯巴达克斯",
           "other_name": ["爱酱"],
           "height": "221cm",
           "weight": "165kg",
           "stair": "Berserker",
           "like": "反叛",
           "dislike": "压迫者"},
    "46": {"name": "坂田金时",
           "other_name": ["金时"],
           "height": "190cm",
           "weight": "88kg",
           "stair": "Berserker",
           "like": "孩子",
           "dislike": "麻烦事"},
    "47": {"name": "弗拉德三世",
           "other_name": ["大公"],
           "height": "191cm",
           "weight": "？？kg",
           "stair": "Berserker",
           "like": "吮吸鲜血",
           "dislike": "被强迫"},
    "48": {"name": "阿斯忒里俄斯",
           "other_name": ["小牛"],
           "height": "298cm",
           "weight": "150kg",
           "stair": "Berserker",
           "like": "？？？",
           "dislike": "与他有瓜葛"},
    "49": {"name": "卡里古拉",
           "other_name": ["鬼舅"],
           "height": "185cm",
           "weight": "80kg",
           "stair": "Berserker",
           "like": "女神狄安娜",
           "dislike": "？？？"},
    "50": {"name": "大流士三世",
           "other_name": ["大流士", "大表哥", "表哥"],
           "height": "345cm",
           "weight": "280kg",
           "stair": "Berserker",
           "like": "？？？",
           "dislike": "伊斯坎达尔"},
    "51": {"name": "清姬",
           "other_name": ["清姬"],
           "height": "158cm",
           "weight": "41kg",
           "stair": "Berserker",
           "like": "诚实",
           "dislike": "谎言"},
    "52": {"name": "血斧埃里克",
           "other_name": ["血斧"],
           "height": "195cm",
           "weight": "119kg",
           "stair": "Berserker",
           "like": "血",
           "dislike": "输"},
    "53": {"name": "玉藻猫",
           "other_name": ["玉藻喵"],
           "height": "160cm",
           "weight": "52kg",
           "stair": "Berserker",
           "like": "主人",
           "dislike": "与自己风格相同的对手"},
    "54": {"name": "贞德",
           "other_name": ["贞德"],
           "height": "159cm",
           "weight": "44kg",
           "stair": "Extra",
           "like": "在干草堆上睡觉",
           "dislike": "争斗"},
    "55": {"name": "俄里翁",
           "other_name": ["月神"],
           "height": "165cm",
           "weight": "44kg",
           "stair": "Archer",
           "like": "自己亲爱的",
           "dislike": "亲爱的搞外遇"},
    "56": {"name": "伊丽莎白巴托里（万圣节）",
           "other_name": ["万圣龙娘"],
           "height": "174cm",
           "weight": "44kg",
           "stair": "Caster",
           "like": "南瓜，布丁",
           "dislike": "章鱼"},
    "57": {"name": "玉藻前",
           "other_name": ["狐狸", "小玉"],
           "height": "160cm",
           "weight": "49kg",
           "stair": "Caster",
           "like": "甜蜜小家",
           "dislike": "回顾自己处理不周的事情"},
    "58": {"name": "大卫",
           "other_name": ["大卫"],
           "height": "171cm",
           "weight": "62kg",
           "stair": "Archer",
           "like": "女性和钱财",
           "dislike": "战斗"},
    "59": {"name": "赫克托耳",
           "other_name": ["赫克托耳"],
           "height": "180cm",
           "weight": "82kg",
           "stair": "Lancer",
           "like": "平凡悠闲地活下去",
           "dislike": "体力劳动"},
    "60": {"name": "弗朗西斯德雷克",
           "other_name": ["德雷克", "船长"],
           "height": "162cm",
           "weight": "55kg",
           "stair": "Rider",
           "like": "酒",
           "dislike": "正义之士，音痴"},
    "61": {"name": "安妮·伯妮＆玛莉·瑞德",
           "other_name": ["双子"],
           "height": "171/158cm",
           "weight": "54/46kg",
           "stair": "Rider",
           "like": "快乐的每一天",
           "dislike": "受到拘束"},
    "62": {"name": "美狄亚Lily",
           "other_name": ["c妈lily"],
           "height": "149cm",
           "weight": "41kg",
           "stair": "Caster",
           "like": "相亲到恋爱结婚之事",
           "dislike": "遭遇背叛"},
    "63": {"name": "冲田总司",
           "other_name": ["总司", "冲田", "樱saber"],
           "height": "158cm",
           "weight": "45kg",
           "stair": "Saber",
           "like": "团子，还有金平糖",
           "dislike": "腌萝卜（绝对不要！凶）"},
    "64": {"name": "织田信长",
           "other_name": ["信长", "nobu"],
           "height": "152cm",
           "weight": "43kg",
           "stair": "Archer",
           "like": "南蛮东西的魅力",
           "dislike": "容易放弃的人"},
    "65": {"name": "斯卡哈",
           "other_name": ["师匠", "BBA", "紫发老太婆"],
           "height": "168cm",
           "weight": "55kg",
           "stair": "Lancer",
           "like": "具备勇气之人",
           "dislike": "没有勇气之辈"},
    "66": {"name": "迪奥姆德奥迪那",
           "other_name": ["刷子", "迪卢木多"],
           "height": "184cm",
           "weight": "85kg",
           "stair": "Lancer",
           "like": "友情",
           "dislike": "野猪"},
    "67": {"name": "弗格斯·马克·罗伊",
           "other_name": ["小刚"],
           "height": "184cm",
           "weight": "90kg",
           "stair": "Saber",
           "like": "女人",
           "dislike": "嫉妒，嫉恨"},
    "68": {"name": "阿尔托莉雅潘德拉贡圣诞",
           "other_name": ["骑呆", "riber", "raber"],
           "height": "154cm",
           "weight": "52kg",
           "stair": "Rider",
           "like": "强大的存在，比如不容易坏的礼物",
           "dislike": "软弱的存在，比如稍微摆弄一下就会断的玩具"},
    "69": {"name": "童谣",
           "other_name": ["童谣"],
           "height": "137cm",
           "weight": "30kg",
           "stair": "Caster",
           "like": "皆大欢喜的结局",
           "dislike": "悲剧的结局"},
    "70": {"name": "开膛手杰克",
           "other_name": ["杰克", "女儿"],
           "height": "134cm",
           "weight": "33kg",
           "stair": "Assassin",
           "like": "在暖和的被窝睡觉",
           "dislike": "欺负人的人"},
    "71": {"name": "莫德雷德",
           "other_name": ["小莫", "逆子", "莫仔", "莫崽"],
           "height": "154cm",
           "weight": "42kg",
           "stair": "Saber",
           "like": "兜风",
           "dislike": "父王"},
    "72": {"name": "尼古拉特斯拉",
           "other_name": ["特斯拉", "特总"],
           "height": "190cm",
           "weight": "80kg",
           "stair": "Archer",
           "like": "天空",
           "dislike": "恶鬼"},
    "73": {"name": "阿尔托莉雅潘德拉贡AlterLancer",
           "other_name": ["黑枪呆", "南半球"],
           "height": "171cm",
           "weight": "57kg？",
           "stair": "Lancer",
           "like": "垃圾食品（",
           "dislike": "所持之枪"},
    "74": {"name": "冯霍恩海姆帕拉塞尔苏斯",
           "other_name": ["霍恩海姆", "豆爸"],
           "height": "183cm",
           "weight": "65kg",
           "stair": "Caster",
           "like": "赐予遍布于大地的所有心爱之子们慈悲与爱",
           "dislike": "背叛"},
    "75": {"name": "查尔斯巴贝奇",
           "other_name": ["巴贝奇"],
           "height": "250cm",
           "weight": "500kg",
           "stair": "Caster",
           "like": "能满足自身差分机引擎的未来",
           "dislike": "畏惧，嫌恶，憎恨，哀叹"},
    "76": {"name": "亨利杰基尔&海德",
           "other_name": ["杰基尔"],
           "height": "175cm",
           "weight": "60kg",
           "stair": "Assassin",
           "like": "人的善良与诚实，但，人的邪恶？",
           "dislike": "人的善良与城实？，但，人的邪恶"},
    "77": {"name": "弗兰肯斯坦",
           "other_name": ["肯娘"],
           "height": "172cm",
           "weight": "48kg",
           "stair": "Berserker",
           "like": "？？？",
           "dislike": "？？？"},
    "78": {"name": "阿周那",
           "other_name": ["周黑鸭"],
           "height": "177cm",
           "weight": "72kg",
           "stair": "Archer",
           "like": "独自一人",
           "dislike": "闯入他内心的人"},
    "79": {"name": "迦尔纳",
           "other_name": ["小太阳"],
           "height": "178cm",
           "weight": "65kg",
           "stair": "Lancer",
           "like": "友情，努力，和解",
           "dislike": "交流"},
    "80": {"name": "谜之女主角X",
           "other_name": ["x毛"],
           "height": "154cm",
           "weight": "42kg",
           "stair": "Assassin",
           "like": "Saber",
           "dislike": "除我以外的Saber"},
    "81": {"name": "芬恩麦克库尔",
           "other_name": ["芬恩"],
           "height": "181cm",
           "weight": "63kg",
           "stair": "Lancer",
           "like": "公正，正道，高洁，以及优美",
           "dislike": "背叛"},
    "82": {"name": "布伦希尔德",
           "other_name": ["布姐"],
           "height": "172cm",
           "weight": "52kg",
           "stair": "Lancer",
           "like": "没有...（刻意的）",
           "dislike": "没有..."},
    "83": {"name": "贝奥武夫",
           "other_name": ["贝奥武夫"],
           "height": "186cm",
           "weight": "81kg",
           "stair": "Berserker",
           "like": "斗殴",
           "dislike": "龙"},
    "84": {"name": "尼禄克劳狄乌斯（花嫁）",
           "other_name": ["花嫁"],
           "height": "150cm",
           "weight": "42kg",
           "stair": "Saber",
           "like": "自身",
           "dislike": "花心的人呢"},
    "85": {"name": "两仪式（Saber）",
           "other_name": ["剑式", "215"],
           "height": "160cm",
           "weight": "47kg",
           "stair": "Saber",
           "like": "御主",
           "dislike": "冰淇淋"},
    "86": {"name": "两仪式（Assassin）",
           "other_name": ["杀式", "214"],
           "height": "160cm",
           "weight": "47kg",
           "stair": "Assassin",
           "like": "不知道",
           "dislike": "那些自己命名能看到，却故意装糊涂的家伙"},
    "87": {"name": "天草四郎",
           "other_name": ["天草"],
           "height": "169cm",
           "weight": "59kg",
           "stair": "Extra",
           "like": "一切都能得到怜爱的世界",
           "dislike": "压政，蹂躏，虐杀"},
    "88": {"name": "阿斯托尔福",
           "other_name": ["阿福"],
           "height": "164cm",
           "weight": "56kg",
           "stair": "Rider",
           "like": "这世界的全部！",
           "dislike": "没~有~哦~(＾Ｕ＾)ノ~ＹＯ"},
    "89": {"name": "幼吉尔",
           "other_name": ["幼吉尔", "幼闪闪", "幼闪"],
           "height": "140cm",
           "weight": "30kg",
           "stair": "Archer",
           "like": "成熟稳重的人",
           "dislike": "刁难人的人"},
    "90": {"name": "岩窟王",
           "other_name": ["基督山伯爵", "伯爵"],
           "height": "185cm",
           "weight": "75kg",
           "stair": "Extra",
           "like": "没有意义了！",
           "dislike": "厌恶世界，哈哈哈哈哈哈"},
    "91": {"name": "南丁格尔",
           "other_name": ["南丁"],
           "height": "165cm",
           "weight": "52kg",
           "stair": "Berserker",
           "like": "清洁，卫生维持，以及健康",
           "dislike": "不卫生，卫生环境的时空，以及伤病"},
    "92": {"name": "库丘林Alter",
           "other_name": ["狂狗", "黑狗"],
           "height": "185cm",
           "weight": "72kg",
           "stair": "Berserker",
           "like": "毫无意义",
           "dislike": "敌人"},
    "93": {"name": "女王梅芙",
           "other_name": ["梅芙"],
           "height": "154cm",
           "weight": "41kg",
           "stair": "Rider",
           "like": "男人，勇士",
           "dislike": "不愿意陪伴我的人"},
    "94": {"name": "海伦娜·布拉瓦茨基",
           "other_name": ["海伦娜", "海妈", "伟大灵魂"],
           "height": "145cm",
           "weight": "38kg",
           "stair": "Caster",
           "like": "人偶（特定对象）",
           "dislike": "SPR！"},
    "95": {"name": "李书文",
           "other_name": ["李书文"],
           "height": "166cm",
           "weight": "60kg",
           "stair": "Lancer",
           "like": "和其他战士一决高下",
           "dislike": "为纯粹的杀戮冠以正义的理由"},
    "96": {"name": "托马斯爱迪生",
           "other_name": ["爱迪生", "爱迪狮", "爱总统"],
           "height": "182cm",
           "weight": "88kg",
           "stair": "Caster",
           "like": "自身发明被他人使用的瞬间",
           "dislike": "尼古拉特斯拉"},
    "97": {"name": "杰罗尼莫",
           "other_name": ["二表哥"],
           "height": "174cm",
           "weight": "76kg",
           "stair": "Caster",
           "like": "在温暖的阳光下，悠闲地睡午觉",
           "dislike": "侵略，傲慢，污蔑。"},
    "98": {"name": "比利小子",
           "other_name": ["比利"],
           "height": "158cm",
           "weight": "49kg",
           "stair": "Archer",
           "like": "快活开心的事情",
           "dislike": "吵吵闹闹"},
    "99": {"name": "贞德Alter",
           "other_name": ["黑贞"],
           "height": "159cm",
           "weight": "44kg",
           "stair": "Extra",
           "like": "在信徒们的眼前否定神明",
           "dislike": "为纯粹的杀戮冠以正义的理由"},
    "100": {"name": "安哥拉曼纽",
            "other_name": ["小安"],
            "height": "167cm",
            "weight": "58kg",
            "stair": "Extra",
            "like": "人类（作为食物x",
            "dislike": "过于认真的正义伙伴（吃下去也会坏肚子x"},
    "101": {"name": "伊斯坎达尔",
            "other_name": ["大帝"],
            "height": "212cm",
            "weight": "130kg",
            "stair": "Rider",
            "like": "征服",
            "dislike": "秘书官的唠叨"},
    "102": {"name": "卫宫Assassin",
            "other_name": ["卫宫切嗣", "切嗣", "切嗣papa"],
            "height": "175cm",
            "weight": "63kg",
            "stair": "Assassin",
            "like": "甜的东西",
            "dislike": "妄想用冠冕堂皇的方法拯救世间的人"},
    "103": {"name": "百貌哈桑",
            "other_name": ["百貌"],
            "height": "？？？cm",
            "weight": "？？？kg",
            "stair": "Assassin",
            "like": "希望有一天，脑海中的声音能安静下来，能再寂静的夜晚好好睡一觉",
            "dislike": "不清楚，毕竟一个人不擅长的事情，就是另一个人的专业"},
    "104": {"name": "爱丽斯菲尔",
            "other_name": ["爱丽", "太太"],
            "height": "158cm",
            "weight": "52kg",
            "stair": "Caster",
            "like": "那个孩子，还有，他...",
            "dislike": "辣的东西，还有那个打太极拳的神父"},
    "105": {"name": "酒吞童子",
            "other_name": ["酒吞", "一姐", "央视一姐"],
            "height": "145cm",
            "weight": "46kg",
            "stair": "Assassin",
            "like": "帅哥，比如某个金发的小家伙",
            "dislike": "低情商，怎么能问我讨厌的东西呢（"},
    "106": {"name": "玄奘三藏",
            "other_name": ["三藏", "妖僧"],
            "height": "160cm",
            "weight": "48kg",
            "stair": "Caster",
            "like": "什么都喜欢",
            "dislike": "孤身一人"},
    "107": {"name": "玄奘三藏",
            "other_name": ["三藏", "妖僧"],
            "height": "160cm",
            "weight": "48kg",
            "stair": "Caster",
            "like": "什么都喜欢",
            "dislike": "孤身一人"},
    "108": {"name": "源赖光",
            "other_name": ["奶光", "妈妈"],
            "height": "175cm",
            "weight": "？？kg",
            "stair": "Berserker",
            "like": "金锷饼",
            "dislike": "坏虫子"},
    "109": {"name": "坂田金时Rider",
            "other_name": ["骑金时", "金时"],
            "height": "190cm",
            "weight": "88kg",
            "stair": "Rider",
            "like": "爱车熊号",
            "dislike": "想不出来呢"},
    "110": {"name": "茨木童子",
            "other_name": ["茨木"],
            "height": "147cm",
            "weight": "50kg",
            "stair": "Berserker",
            "like": "共同成长，共同生活，共同向京发起数次袭击的那个同胞",
            "dislike": "放毒的酒，以及用这酒来除鬼的卑鄙武士"},
    "111": {"name": "风魔小太郎",
            "other_name": ["小太郎"],
            "height": "158cm",
            "weight": "49kg",
            "stair": "Assassin",
            "like": "手里剑、刀、锁镰、替身用的木材和火药弹、还有整理药草吧",
            "dislike": "玷污吾等风魔尊严之人"},
    "112": {"name": "奥斯曼狄斯",
            "other_name": ["太阳王", "拉二"],
            "height": "179cm",
            "weight": "65kg",
            "stair": "Rider",
            "like": "地上的一切（被我支配的一切）都是平等的，无所谓优劣",
            "dislike": "我在地上的肉体过于脆弱"},
    "113": {"name": "阿尔托莉雅潘德拉贡Rider",
            "other_name": ["白枪呆", "北半球"],
            "height": "171cm",
            "weight": "57kg？",
            "stair": "Lancer",
            "like": "想不出来",
            "dislike": "想不出来呢"},
    "114": {"name": "尼托克丽丝",
            "other_name": ["尼托", "大不敬"],
            "height": "162cm",
            "weight": "51kg",
            "stair": "Caster",
            "like": "映照无限存在的黑暗之镜",
            "dislike": "自己的急躁和武断"},
    "115": {"name": "兰斯洛特Saber",
            "other_name": ["兰斯洛特", "剑兰", "长江骑士", "岳父"],
            "height": "191cm",
            "weight": "81kg",
            "stair": "Saber",
            "like": "足以引火焚身的恋爱",
            "dislike": "对王不贞的自身"},
    "116": {"name": "坂田金时Rider",
            "other_name": ["骑金时", "金时"],
            "height": "190cm",
            "weight": "88kg",
            "stair": "Rider",
            "like": "爱车熊号",
            "dislike": "想不出来呢"},
    "117": {"name": "崔斯坦",
            "other_name": ["老崔", "崔悲伤"],
            "height": "186cm",
            "weight": "78kg",
            "stair": "Archer",
            "like": "爱",
            "dislike": "口无遮拦的话语，比如，不懂人心之类的"},
    "118": {"name": "高文",
            "other_name": ["gay文", "不夜骑士"],
            "height": "180cm",
            "weight": "78kg",
            "stair": "Saber",
            "like": "对骑士王的忠诚",
            "dislike": "年长的...不，没什么"},
    "119": {"name": "静谧哈桑",
            "other_name": ["静谧"],
            "height": "161cm",
            "weight": "42kg",
            "stair": "Assassin",
            "like": "小动物，鲜花，虽然我从来没碰过它们",
            "dislike": "我自己"},
    "120": {"name": "俵藤太",
            "other_name": ["饭缸"],
            "height": "183cm",
            "weight": "98kg",
            "stair": "Archer",
            "like": "你应该知道的（谜语人x）",
            "dislike": "没法吃的东西"},
    "121": {"name": "贝德维尔",
            "other_name": ["小贝"],
            "height": "187cm",
            "weight": "88kg",
            "stair": "Saber",
            "like": "蒸蔬菜，但我已经将一切都献给了王",
            "dislike": "想不大出来，即使是敌人，也不是憎恶的存在"},
    "122": {"name": "莱昂纳多达芬奇",
            "other_name": ["达芬奇", "大番茄", "奸商"],
            "height": "160cm",
            "weight": "40kg",
            "stair": "Caster",
            "like": "我的外貌",
            "dislike": "企图烧却世界的家伙"},
    "123": {"name": "玉藻前Lancer",
            "other_name": ["枪小玉", "枪玉", "枪狐狸", "水狐狸"],
            "height": "160cm",
            "weight": "49kg",
            "stair": "Lancer",
            "like": "夏日的浪漫！",
            "dislike": "螃蟹，龙虾，还有特产商店肆意抬价的行为"},
    "124": {"name": "静谧哈桑",
            "other_name": ["静谧"],
            "height": "161cm",
            "weight": "42kg",
            "stair": "Assassin",
            "like": "小动物，鲜花，虽然我从来没碰过它们",
            "dislike": "我自己"},
    "125": {"name": "阿尔托莉雅潘德拉贡Archer",
            "other_name": ["水呆", "水弓呆", "弓呆"],
            "height": "154cm",
            "weight": "42kg",
            "stair": "Archer",
            "like": "没有障碍物的场地，可以尽请相互射击",
            "dislike": "潜到背后的Assassin推手，或是从远处瞄准射击的Caster狙击手未免有些……运动就该愉快地从正面硬拼才对"},
    "126": {"name": "玛丽安托瓦内特Caster",
            "other_name": ["玛丽", "蛋糕", "泳装蛋糕"],
            "height": "160cm",
            "weight": "48kg",
            "stair": "Caster",
            "like": "沙滩排球",
            "dislike": "过强的阳光"},
    "127": {"name": "安妮·伯妮＆玛莉·瑞德(Archer)",
            "other_name": ["双子", "弓双子"],
            "height": "171/158cm",
            "weight": "54/46kg",
            "stair": "Archer",
            "like": "财宝，还有大海",
            "dislike": "异性失礼的视线，不过御主是例外哦"},
    "128": {"name": "莫德雷德Rider",
            "other_name": ["小莫", "逆子", "莫仔", "莫崽"],
            "height": "154cm",
            "weight": "42kg",
            "stair": "Rider",
            "like": "财宝，还有大海",
            "dislike": "异性失礼的视线，不过御主是例外哦"},
    "129": {"name": "安妮·伯妮＆玛莉·瑞德(Archer)",
            "other_name": ["双子", "弓双子"],
            "height": "171/158cm",
            "weight": "54/46kg",
            "stair": "Archer",
            "like": "财宝，还有大海",
            "dislike": "异性失礼的视线，不过御主是例外哦"},
    "130": {"name": "斯卡哈Assassin",
            "other_name": ["斯卡哈", "枪师匠", "紫发老婆", "紫发老太婆"],
            "height": "168cm",
            "weight": "55kg",
            "stair": "Assassin",
            "like": "游泳",
            "dislike": "男人们犀利的视线"},
    "131": {"name": "清姬Lancer",
            "other_name": ["清姬", "枪清姬", "水清姬"],
            "height": "158cm",
            "weight": "41kg",
            "stair": "Lancer",
            "like": "敲钟",
            "dislike": "以城市之心向御主表白的人"},
    "132": {"name": "玛尔达Ruler",
            "other_name": ["玛尔达", "马达", "圣女", "铁拳圣女"],
            "height": "161cm",
            "weight": "49kg",
            "stair": "Extra",
            "like": "？？？",
            "dislike": "没有，请原谅我,,,"},
    "133": {"name": "伊莉雅丝菲尔·冯·爱因兹贝伦",
            "other_name": ["伊莉雅", "yly"],
            "height": "133cm",
            "weight": "29kg",
            "stair": "Caster",
            "like": "夏天，因为我是在夏天出生的",
            "dislike": "做坏事的小黑"},
    "134": {"name": "克洛伊·冯·爱因兹贝伦",
            "other_name": ["小黑"],
            "height": "133cm",
            "weight": "29kg",
            "stair": "Archer",
            "like": "给我大量魔力的人",
            "dislike": "犹豫不决时的伊莉雅"},
    "135": {"name": "伊丽莎白·巴托里〔勇者〕",
            "other_name": ["勇士龙娘", "龙娘"],
            "height": "154cm",
            "weight": "48kg",
            "stair": "Saber",
            "like": "漫游诸国的冒险",
            "dislike": "从剑上发射光炮的武器，明明是Lancer却骑马的家伙，明明是Caster却很能打的家伙"},
    "136": {"name": "克娄巴特拉",
            "other_name": ["皇后"],
            "height": "171cm",
            "weight": "58kg",
            "stair": "Archer",
            "like": "美丽的东西，比如梅杰德神",
            "dislike": "不想回答"},
    "137": {"name": "弗拉德三世Extra",
            "other_name": ["大公", "枪大公"],
            "height": "191cm",
            "weight": "90kg",
            "stair": "Lancer",
            "like": "礼拜，还有妻子的幸福",
            "dislike": "沉溺于欲望，嘲笑尊严，对欺瞒毫无自觉的不知廉耻之人"},
    "138": {"name": "贞德Alter Santa Lily",
            "other_name": ["幼贞"],
            "height": "141cm",
            "weight": "39kg",
            "stair": "Lancer",
            "like": "圣诞老人的行为！Santa，Santer，Santest！",
            "dislike": "万圣节！而且南瓜布丁还莫名好吃"},
    "139": {"name": "伊什塔尔",
            "other_name": ["弓凛"],
            "height": "133cm",
            "weight": "29kg",
            "stair": "Archer",
            "like": "不告诉你",
            "dislike": "浪费，重大损失，疏忽过失"},
    "140": {"name": "恩奇都",
            "other_name": ["小恩", "天之锁"],
            "height": "？？？cm",
            "weight": "？？？kg",
            "stair": "Lancer",
            "like": "没想过",
            "dislike": "锈斑，还有霉点什么的"},
    "141": {"name": "魁札尔·科亚特尔",
            "other_name": ["魁扎尔", "羽蛇神", "颜艺大姐姐"],
            "height": "181cm",
            "weight": "64kg",
            "stair": "Rider",
            "like": "人类，一定要繁荣哦",
            "dislike": "蜘蛛，还有，豹子"},
    "142": {"name": "吉尔伽美神Caster",
            "other_name": ["贤王"],
            "height": "182cm",
            "weight": "68kg",
            "stair": "Caster",
            "like": "世间所有的财宝",
            "dislike": "导致这次情况的家伙，让我被迫这样现界"},
    "143": {"name": "恩奇都",
            "other_name": ["小恩", "天之锁"],
            "height": "？？？cm",
            "weight": "？？？kg",
            "stair": "Lancer",
            "like": "没想过",
            "dislike": "锈斑，还有霉点什么的"},
    "144": {"name": "美杜莎Lancer",
            "other_name": ["r姐Lily", "安娜", "小美杜莎"],
            "height": "134cm",
            "weight": "30kg？",
            "stair": "Lancer",
            "like": "游泳",
            "dislike": "被海藻缠住脚，尤其讨厌裙带菜"},
    "145": {"name": "戈尔贡",
            "other_name": ["戈耳工"],
            "height": "172+？？cm",
            "weight": "57+？？kg",
            "stair": "Extra",
            "like": "人类的痛苦",
            "dislike": "镜子"},
    "146": {"name": "豹人",
            "other_name": ["大河"],
            "height": "165cm",
            "weight": "？？kg",
            "stair": "Lancer",
            "like": "一日三餐美味的食物，充足的睡眠",
            "dislike": "狮子"},
    "147": {"name": "梅林",
            "other_name": ["梅林"],
            "height": "178cm",
            "weight": "68kg",
            "stair": "Caster",
            "like": "人类，恶作剧，还有女孩子",
            "dislike": "Grand Caster"},
    "148": {"name": "所罗门",
            "other_name": ["医生"],
            "height": "178cm",
            "weight": "75kg",
            "stair": "Caster",
            "like": "或许，他会喜欢我一直为他留着的草莓蛋糕",
            "dislike": "？？？"},
    "149": {"name": "宫本武藏",
            "other_name": ["武藏"],
            "height": "167cm",
            "weight": "56kg",
            "stair": "Saber",
            "like": "剑，剑的修行，还有乌冬面！",
            "dislike": "为了自己高兴而践踏他人尊严的家伙，还有在别人饥饿的时候发动袭击的人！"},
    "150": {"name": "山中老人",
            "other_name": ["爷爷", "王哈"],
            "height": "220cm",
            "weight": "？？kg",
            "stair": "Assassin",
            "like": "首级",
            "dislike": "怠惰，堕落，劣化"},
    "151": {"name": "谜之女主角XAlter",
            "other_name": ["bx", "BX"],
            "height": "154cm",
            "weight": "42kg",
            "stair": "Berserker",
            "like": "手工糕点",
            "dislike": "女主角X"},
    "152": {"name": "莫里亚蒂",
            "other_name": ["教授", "新宿的Archer"],
            "height": "175cm",
            "weight": "68kg",
            "stair": "Archer",
            "like": "邪恶的计划！还有数学",
            "dislike": "猎鹿帽，当然，还有福尔摩斯"},
    "153": {"name": "卫宫Alter",
            "other_name": ["黑A"],
            "height": "187cm",
            "weight": "78kg",
            "stair": "Archer",
            "like": "忘了",
            "dislike": "多到已经分不清了"},
    "154": {"name": "黑森罗伯",
            "other_name": ["狼王", "新宿的Avenger"],
            "height": "181cm",
            "weight": "99kg",
            "stair": "Extra",
            "like": "？？？",
            "dislike": "？？！"},
    "155": {"name": "燕青",
            "other_name": ["小乙哥", "新宿的Assassin"],
            "height": "171cm",
            "weight": "63kg",
            "stair": "Assassin",
            "like": "相扑，拳斗，美酒，佳肴，音乐",
            "dislike": "压制，以及不听忠告的主人"},
    "156": {"name": "亚瑟潘德拉贡",
            "other_name": ["亚瑟", "旧剑"],
            "height": "181cm",
            "weight": "68kg",
            "stair": "Saber",
            "like": "想不出来",
            "dislike": "也想不出来，对不起"},
    "157": {"name": "土方岁三",
            "other_name": ["土三", "副组长"],
            "height": "187cm",
            "weight": "75kg",
            "stair": "Berserker",
            "like": "腌萝卜",
            "dislike": "萨摩和常州，就是那群胆小的幕丞"},
    "158": {"name": "茶茶",
            "other_name": ["茶茶"],
            "height": "138cm",
            "weight": "34kg",
            "stair": "Berserker",
            "like": "豪华绚烂金光闪闪的东西！还有红豆年糕汤",
            "dislike": "德川！绝对不可原谅"},
    "159": {"name": "Meltryllis",
            "other_name": ["莉莉丝", "溶解莉莉丝"],
            "height": "190cm",
            "weight": "33kg",
            "stair": "Extra",
            "like": "模型，观赏人偶",
            "dislike": "人类"},
    "160": {"name": "Passionlip",
            "other_name": ["热情迷唇", "帕森莉普"],
            "height": "156cm",
            "weight": "1000kg",
            "stair": "Extra",
            "like": "迫害东西",
            "dislike": "没什么"},
    "161": {"name": "铃鹿御前",
            "other_name": ["铃鹿", "jk", "jk狐狸"],
            "height": "164cm",
            "weight": "51kg",
            "stair": "Saber",
            "like": "恋爱或者恋爱故事以及优秀的男友什么的，和优秀的男友约会什么的，还有和优秀的男友聊天什么的",
            "dislike": "对自己谈的恋爱说三道四，还有看不起我最喜欢的男友"},
    "162": {"name": "BB",
            "other_name": ["屑AI"],
            "height": "156cm",
            "weight": "46kg",
            "stair": "Extra",
            "like": "当然是前辈啦！啊，但是前辈也有种类之分，「不行，好高贵」系前辈和「没办法，只能帮帮他了」系前辈比较好。御主究竟算哪种呢，那就任君想象啦♡",
            "dislike": "人类"},
    "163": {"name": "杀生院祈荒",
            "other_name": ["杀生院"],
            "height": "166cm",
            "weight": "53kg？",
            "stair": "Extra",
            "like": "各位人类，还有...童话",
            "dislike": "嘴巴狠毒的怪癖悲观主义"},
    "164": {"name": "山鲁佐德",
            "other_name": ["1001", "不夜城的Caster"],
            "height": "168cm",
            "weight": "58kg",
            "stair": "Caster",
            "like": "安全与安心",
            "dislike": "死去"},
    "165": {"name": "武则天",
            "other_name": ["女帝", "不夜城的Assassin"],
            "height": "138cm",
            "weight": "35kg",
            "stair": "Assassin",
            "like": "自己的国家",
            "dislike": "猫和幽灵"},
    "166": {"name": "彭忒西勒亚",
            "other_name": ["ceo", "CEO", "黄金国的Berserker"],
            "height": "158cm",
            "weight": "49kg",
            "stair": "Berserker",
            "like": "能认真决胜负的战场，优秀的部下，尚未得见的强敌",
            "dislike": "赫拉克勒斯，阿喀琉斯....尽管我承认他们都是强者"},
    "167": {"name": "哥伦布",
            "other_name": ["反抗军的Rider"],
            "height": "180cm",
            "weight": "84kg",
            "stair": "Rider",
            "like": "金钱，地位和名声",
            "dislike": "不听船长命令的船员"},
    "168": {"name": "武则天",
            "other_name": ["女帝", "不夜城的Assassin"],
            "height": "138cm",
            "weight": "35kg",
            "stair": "Assassin",
            "like": "自己的国家",
            "dislike": "猫和幽灵"},
    "169": {"name": "夏洛克福尔摩斯",
            "other_name": ["福尔摩斯", "老福"],
            "height": "183cm",
            "weight": "65kg",
            "stair": "Extra",
            "like": "搜查，以及...",
            "dislike": "你觉得呢？这是常识啊"},
    "170": {"name": "保罗班扬",
            "other_name": ["保罗", "班扬"],
            "height": "？？？cm",
            "weight": "？？？kg",
            "stair": "Berserker",
            "like": "大家都露出笑容！还有烤薄饼",
            "dislike": "讨厌我的人"},
    "171": {"name": "尼禄克劳狄乌斯Caster",
            "other_name": ["水尼禄", "水尼"],
            "height": "150cm",
            "weight": "42kg",
            "stair": "Caster",
            "like": "在水边依然闪耀的那朵红色蔷薇（自己",
            "dislike": "不平易近人的某位女仆"},
    "172": {"name": "弗兰肯斯坦Saber",
            "other_name": ["弗兰"],
            "height": "172cm",
            "weight": "48kg",
            "stair": "Saber",
            "like": "凉爽~！",
            "dislike": "酷热~！"},
    "173": {"name": "尼托克丽丝Assassin",
            "other_name": ["尼托", "大不敬", "水尼托"],
            "height": "162cm",
            "weight": "51kg",
            "stair": "Assassin",
            "like": "在水边游泳",
            "dislike": "大不敬"},
    "174": {"name": "织田信长Berserker",
            "other_name": ["信长", "狂信", "狂信长"],
            "height": "152cm",
            "weight": "44kg",
            "stair": "Berserker",
            "like": "海之家的炒面和拉面",
            "dislike": "味道很淡的食物"},
    "175": {"name": "阿尔托莉雅潘德拉贡AlterRider",
            "other_name": ["黑骑呆", "水黑呆"],
            "height": "154cm",
            "weight": "42kg",
            "stair": "Rider",
            "like": "冰棍",
            "dislike": "料理"},
    "176": {"name": "海伦娜布拉瓦茨基Archer",
            "other_name": ["海伦娜", "海妈", "伟大灵魂"],
            "height": "145cm",
            "weight": "38kg",
            "stair": "Archer",
            "like": "咻~地驰骋，还有用NYARF尽情喷水",
            "dislike": "现在没什么（其实有，是SPR"},
    "177": {"name": "源赖光Lancer",
            "other_name": ["源赖光", "奶光"],
            "height": "175cm",
            "weight": "？？kg",
            "stair": "Lancer",
            "like": "维持风纪，让迦勒底保持平稳",
            "dislike": "风纪被扰乱"},
    "178": {"name": "伊什塔尔Rider",
            "other_name": ["伊什塔尔", "骑凛"],
            "height": "159cm",
            "weight": "47kg",
            "stair": "Rider",
            "like": "节日，尤其是能取悦更多人的节日",
            "dislike": "浪费，重大损失和失误"},
    "179": {"name": "帕尔瓦蒂",
            "other_name": ["樱", "枪樱"],
            "height": "156cm",
            "weight": "46kg",
            "stair": "Lancer",
            "like": "料理",
            "dislike": "裙带菜"},
    "180": {"name": "巴御前",
            "other_name": ["巴妈", "鲅鱼圈"],
            "height": "162cm",
            "weight": "50kg",
            "stair": "Archer",
            "like": "义仲大人",
            "dislike": "范赖，源义经，还有赖朝公"},
    "181": {"name": "望月千代女",
            "other_name": ["千代女"],
            "height": "154cm",
            "weight": "46kg",
            "stair": "Assassin",
            "like": "没有好恶（就食物而言",
            "dislike": "战争，盛时大人也不会喜欢..."},
    "182": {"name": "宝藏院胤舜",
            "other_name": ["宝藏院"],
            "height": "177cm",
            "weight": "79kg",
            "stair": "Lancer",
            "like": "自己的枪",
            "dislike": "毫无意义的杀生"},
    "183": {"name": "柳生但马守宗矩",
            "other_name": ["柳生", "老爷子"],
            "height": "181cm",
            "weight": "71kg",
            "stair": "Saber",
            "like": "？？？",
            "dislike": "多余的存在"},
    "184": {"name": "加藤段藏",
            "other_name": ["段藏", "加藤"],
            "height": "165cm",
            "weight": "45kg?",
            "stair": "Assassin",
            "like": "风",
            "dislike": "黑色的太阳"},
    "185": {"name": "机械伊丽亲",
            "other_name": ["机械龙娘", "ae龙娘"],
            "height": "156cm",
            "weight": "4000kg",
            "stair": "Extra",
            "like": "井然有序的支配体制，以及，美丽的钢铁",
            "dislike": "毫无责任心的 领主，不好好工作的贵族，以及失控的自己"},
    "186": {"name": "喀尔刻",
            "other_name": ["姑姑"],
            "height": "147cm",
            "weight": "39kg",
            "stair": "Caster",
            "like": "麦粥“休刻翁",
            "dislike": "奥德修斯"},
    "187": {"name": "哪吒",
            "other_name": ["三太子"],
            "height": "164cm",
            "weight": "57kg",
            "stair": "Lancer",
            "like": "午睡",
            "dislike": "愚蠢的自己"},
    "188": {"name": "示巴女王",
            "other_name": ["示巴"],
            "height": "173cm",
            "weight": "59kg",
            "stair": "Caster",
            "like": "在迦勒底养骆驼",
            "dislike": "我付钱"},
    "189": {"name": "阿比盖尔威廉姆斯",
            "other_name": ["阿比盖尔", "阿比", "开发者的女儿（不是"],
            "height": "152cm",
            "weight": "44kg",
            "stair": "Extra",
            "like": "烤薄饼",
            "dislike": "狗"},
    "190": {"name": "埃列什基伽勒",
            "other_name": ["艾蕾", "枪凛", "冥界之花"],
            "height": "159cm",
            "weight": "47kg",
            "stair": "Lancer",
            "like": "登山，制作牢笼",
            "dislike": "伊什塔尔与奢侈无能的人类"},
    "191": {"name": "阿蒂拉theSan[ta]",
            "other_name": ["圣诞大王", "大王", "阿蒂拉"],
            "height": "160cm",
            "weight": "48kg",
            "stair": "Archer",
            "like": "羊毛，雪，棉花糖，也就是轻飘飘的东西！",
            "dislike": "冰冷的冰淇淋和啰嗦的家伙"},
    "192": {"name": "葛饰北斋",
            "other_name": ["北斋", "阿荣"],
            "height": "162cm",
            "weight": "51kg",
            "stair": "Extra",
            "like": "美人，虽然我什么都愿意画",
            "dislike": "郁闷烦躁的氛围"},
    "193": {"name": "塞弥拉弥斯",
            "other_name": ["女帝"],
            "height": "169cm",
            "weight": "51kg?",
            "stair": "Assassin",
            "like": "挖洞",
            "dislike": "粗暴的男人"},
    "194": {"name": "浅上藤乃",
            "other_name": ["藤乃"],
            "height": "157cm",
            "weight": "51kg",
            "stair": "Archer",
            "like": "恐怖电影",
            "dislike": "不知道，因为我的痛觉已经...没什么，如果真要说害怕的话，那就是式小姐。"},
    "195": {"name": "阿斯塔纳西娅",
            "other_name": ["皇女"],
            "height": "158cm",
            "weight": "40kg",
            "stair": "Caster",
            "like": "和维一起生活",
            "dislike": "粗野，野蛮，蛮横的士兵们"},
    "196": {"name": "阿塔兰忒Alter",
            "other_name": ["狂塔"],
            "height": "166cm",
            "weight": "57kg",
            "stair": "Berserker",
            "like": "孩子们",
            "dislike": "避而不看美丽之物的圣女"},
    "197": {"name": "阿维斯布隆",
            "other_name": ["阿伟", "阿维"],
            "height": "161cm",
            "weight": "52kg",
            "stair": "Caster",
            "like": "撰写诗歌",
            "dislike": "被人迫害"},
    "198": {"name": "安东尼奥萨列里",
            "other_name": ["萨列里"],
            "height": "181cm",
            "weight": "65kg",
            "stair": "Extra",
            "like": "演奏音乐",
            "dislike": "莫扎特"},
    "199": {"name": "伊凡雷帝",
            "other_name": ["雷帝"],
            "height": "531cm",
            "weight": "2548kg",
            "stair": "Rider",
            "like": "阿斯塔纳西亚",
            "dislike": "不爱神明，在国内专横的贵族们"},
    "200": {"name": "阿喀琉斯",
            "other_name": ["脚后跟", "团长", "阿脚"],
            "height": "185cm",
            "weight": "97kg",
            "stair": "Rider",
            "like": "战斗",
            "dislike": "自由行动"},
    "201": {"name": "喀戎",
            "other_name": ["马老师", "马永六"],
            "height": "179cm",
            "weight": "81kg",
            "stair": "Archer",
            "like": "交谈",
            "dislike": "蛇，还有毒（不要告诉赫拉克勒斯哦"},
    "202": {"name": "齐格",
            "other_name": ["齐格"],
            "height": "165cm",
            "weight": "53kg",
            "stair": "Caster",
            "like": "存在于此",
            "dislike": "没有"},
    "203": {"name": "七海博世",
            "other_name": ["大家的RBQ", "布丁的开发者"],
            "height": "163cm",
            "weight": "44kg",
            "stair": "developer",
            "like": "小王子，戈尔德鲁夫",
            "dislike": "甜食"},
    "204": {"name": "冲田总司Alter",
            "other_name": ["魔总"],
            "height": "163cm",
            "weight": "51kg",
            "stair": "Extra",
            "like": "上次在食堂吃的关东煮，那个很好吃。尤其是白色的，叫什么来着……对，是竹轮麸。那种柔韧的口感很棒。……但是，不需要芥末。辣。",
            "dislike": "之前在商店抽奖时全都没中。在抽奖前明明还不怎么想要，但实际没抽中后就感到非常不甘心。不甘心。"},
    "205": {"name": "酥和侠",
            "other_name": ["rbq", "布丁的开发者"],
            "height": "193cm",
            "weight": "65kg",
            "stair": "developer",
            "like": "奶茶",
            "dislike": "蘑菇"},
    "206": {"name": "冈田以藏",
            "other_name": ["以藏"],
            "height": "174cm",
            "weight": "65kg",
            "stair": "Assassin",
            "like": "酒和赌博",
            "dislike": "明明什么才华都没有，却自认为了不起的人，还有味道很冲的蔬菜"},
    "207": {"name": "坂本龙马",
            "other_name": ["龙马"],
            "height": "178cm",
            "weight": "72kg",
            "stair": "Rider",
            "like": "鱼的刺身，还有酒",
            "dislike": "大或小的悲伤之事，还有青蛙"},
    "208": {"name": "拿破仑",
            "other_name": ["拿皇"],
            "height": "189cm",
            "weight": "92kg",
            "stair": "Archer",
            "like": "雪茄，书籍，还有好女人",
            "dislike": "巴哥犬，尽管我至今仍爱着约瑟芬..."},
    "209": {"name": "齐格鲁德",
            "other_name": ["西哥"],
            "height": "178cm",
            "weight": "79kg",
            "stair": "Saber",
            "like": "雪景",
            "dislike": "小动物（不过没到讨厌的程度"},
    "210": {"name": "瓦尔基里",
            "other_name": ["女武神"],
            "height": "159cm",
            "weight": "46kg",
            "stair": "Lancer",
            "like": "勇士的灵魂",
            "dislike": "没有（因为是服从命令的存在"},
    "211": {"name": "斯卡哈斯卡蒂",
            "other_name": ["斯卡蒂", "c师匠", "cba", "CBA"],
            "height": "162cm",
            "weight": "50kg",
            "stair": "Caster",
            "like": "冬天，还有春天",
            "dislike": "火焰，尽管奥丁说那是人类需要的"},
    "212": {"name": "贞德Archer",
            "other_name": ["水贞", "贞德", "金针菇", "鲸贞姑"],
            "height": "159cm",
            "weight": "44kg",
            "stair": "Archer",
            "like": "和海豚戏耍，鲸鱼也很好",
            "dislike": "冬天（尽管很想尝试圣诞节穿泳装"},
    "213": {"name": "茨木童子Lancer",
            "other_name": ["茨木"],
            "height": "147cm",
            "weight": "50kg",
            "stair": "Lancer",
            "like": "咬上去，无情地啃噬，咬碎，边品味边吞下……哈哈哈。甜美得妙不可言！倘若能和酒吞一起品尝，更是至高无上的……",
            "dislike": "母亲的笑容，因为我一次都没见过"},
    "214": {"name": "牛若丸Assassin",
            "other_name": ["牛肉丸"],
            "height": "168cm",
            "weight": "55kg",
            "stair": "Assassin",
            "like": "山里的动物们，还有恶作剧",
            "dislike": "平时不喜欢高处，但是现在喜欢，现在应该只讨厌敌人了"},
    "215": {"name": "贞德AlterBerserker",
            "other_name": ["黑贞", "水黑贞", "狂贞"],
            "height": "159cm",
            "weight": "44kg",
            "stair": "Berserker",
            "like": "漫画，还有画同人志",
            "dislike": "圣女变成的海豚女，不，应该是鲸鱼女"},
    "216": {"name": "BB",
            "other_name": ["bb", "水bb", "屑AI"],
            "height": "156cm~？？cm",
            "weight": "46kg~？？kg",
            "stair": "Extra",
            "like": "粗糙的玩具",
            "dislike": "人类关键时候的态度改变"},
    "217": {"name": "女王梅芙Saber",
            "other_name": ["梅芙", "泳装梅芙"],
            "height": "154cm",
            "weight": "41kg",
            "stair": "Saber",
            "like": "鸡尾酒",
            "dislike": "库丘林"},
    "218": {"name": "谜之女主角XX",
            "other_name": ["xx毛"],
            "height": "154cm",
            "weight": "48kg",
            "stair": "Extra",
            "like": "假日与当地美食，还有地球的特产",
            "dislike": "Saber"},
    "219": {"name": "迪尔姆德奥迪那Saber",
            "other_name": ["迪卢木多", "剑刷"],
            "height": "184cm",
            "weight": "85kg",
            "stair": "Saber",
            "like": "与朋友畅谈",
            "dislike": "主公的嫉妒"},
    "220": {"name": "志度内",
            "other_name": ["熊伊莉雅", "熊伊", "开发者的宝贝女儿（夹带私货x"],
            "height": "133cm",
            "weight": "34kg",
            "stair": "Extra",
            "like": "雪，虽然很冷，但是软绵绵的",
            "dislike": "寒冷，尽管现在已经感觉不到了"},
    "221": {"name": "酒吞童子Caster",
            "other_name": ["术酒吞", "酒吞"],
            "height": "145cm",
            "weight": "46kg",
            "stair": "Caster",
            "like": "这身衣裳，尽管平时穿的衣服布料不多",
            "dislike": "唠叨"},
    "222": {"name": "项羽",
            "other_name": ["项羽"],
            "height": "310cm",
            "weight": "480kg",
            "stair": "Berserker",
            "like": "我不被需要的那一天，能陷入沉睡",
            "dislike": "虚伪的安宁"},
    "223": {"name": "兰陵王",
            "other_name": ["兰陵王"],
            "height": "172cm",
            "weight": "55kg",
            "stair": "Saber",
            "like": "照顾马匹",
            "dislike": "遭到怀疑"},
    "224": {"name": "秦良玉",
            "other_name": ["秦良玉"],
            "height": "166cm",
            "weight": "46kg",
            "stair": "Lancer",
            "like": "和平，农业，还有御主的笑容",
            "dislike": "盗贼，讨厌死了！"},
    "225": {"name": "始皇帝",
            "other_name": ["嬴政", "政哥哥"],
            "height": "180cm",
            "weight": "65kg",
            "stair": "Extra",
            "like": "水银（永劫不灭的象征",
            "dislike": "水银（很难吃"},
    "226": {"name": "虞美人",
            "other_name": ["芥锥子", "老芥"],
            "height": "160cm",
            "weight": "49kg",
            "stair": "Assassin",
            "like": "无言的生命，以应有的形象讴歌短暂春日的存在。这种存在方式令人怜爱。永不终结的生命之连锁。尽管我只是个旁观者。",
            "dislike": "人类"},
    "227": {"name": "赤兔马",
            "other_name": ["孽畜"],
            "height": "250cm",
            "weight": "400kg以上",
            "stair": "Rider",
            "like": "胡萝卜",
            "dislike": "没有资格的人骑在背上"},
    "228": {"name": "布拉达曼特",
            "other_name": ["屁股枪", "尻枪"],
            "height": "170cm",
            "weight": "55kg",
            "stair": "Lancer",
            "like": "鲁杰罗",
            "dislike": "魔术师，但是御主另当别论，因为您身上有花之魔术师的气息啊！"},
    "229": {"name": "魁扎尔科亚特尔（桑巴/圣诞）",
            "other_name": ["羽蛇神", "圣诞大姐姐"],
            "height": "181cm",
            "weight": "64kg",
            "stair": "Extra",
            "like": "圣诞，摔跤，还有桑巴",
            "dislike": "蜘蛛型面具"},
    "230": {"name": "红阎魔",
            "other_name": ["小麻雀"],
            "height": "130cm",
            "weight": "？？kg",
            "stair": "Saber",
            "like": "稻谷啾，特别是饭团",
            "dislike": "欺负弱小啾，还有撒谎。不过善意的谎言是可以原谅的，毕竟谎言本身就是无可奈何啾事"},
    "231": {"name": "李书文",
            "other_name": ["李大师"],
            "height": "166cm",
            "weight": "58kg",
            "stair": "Assassin",
            "like": "家人",
            "dislike": "计算都不会的笨蛋"},
    "232": {"name": "美游艾德菲尔特",
            "other_name": ["美游"],
            "height": "134cm",
            "weight": "30kg",
            "stair": "Caster",
            "like": "伊莉雅，哥哥，露维娅...还有蓝宝石",
            "dislike": "还不太明白讨厌这种感情"},
    "233": {"name": "紫式部",
            "other_name": ["紫式部"],
            "height": "163cm",
            "weight": "51kg",
            "stair": "Caster",
            "like": "竹取物语，伊势物语！还有哈姆雷特，李尔王，红楼梦，小美人鱼....",
            "dislike": "不爱惜书籍的人"},
    "234": {"name": "Kingprotea",
            "other_name": ["帝王花"],
            "height": "5~？？cm",
            "weight": "？？kg",
            "stair": "Extra",
            "like": "梦想成为可爱的新娘",
            "dislike": "比我还巨大的物体"},
    "235": {"name": "迦摩",
            "other_name": ["夹馍"],
            "height": "156cm",
            "weight": "46kg",
            "stair": "Assassin",
            "like": "认真的人，或是严肃的人都在我面前堕落",
            "dislike": "帕尔瓦蒂和她丈夫"},
    "236": {"name": "司马懿",
            "other_name": ["莱妮丝", "一抹多", "懿抹多"],
            "height": "149cm",
            "weight": "42kg",
            "stair": "Rider",
            "like": "他人的不幸，尤其是让那些老实人心情郁闷偏离人生正规的时候",
            "dislike": "平静的人生，意料之内的事，以及一成不变的发展"},
    "237": {"name": "阿斯特赖亚",
            "other_name": ["露维娅", "金钻头"],
            "height": "160cm",
            "weight": "49kg",
            "stair": "Extra",
            "like": "夺走他人重要的东西（尽管不符合自身身份",
            "dislike": "没有尊严的存在"},
    "238": {"name": "格蕾",
            "other_name": ["格蕾"],
            "height": "154cm",
            "weight": "42kg",
            "stair": "Assassin",
            "like": "安静的房间，烟卷的味道，古书的尾刀，还有大家热闹交谈的教室",
            "dislike": "明明已经死了，却在地面行走的东西"},
    "239": {"name": "伟大的石像神",
            "other_name": ["伽内什", "吉娜可", "大象"],
            "height": "153cm",
            "weight": "82kg",
            "stair": "Extra",
            "like": "深夜品尝的薯片，冰淇淋，当然如果要给我送礼，游戏卡也不错",
            "dislike": "工作，现充"},
    "240": {"name": "拉克什米芭伊",
            "other_name": ["拉克什米", "印度贞德", "章西女王"],
            "height": "159cm",
            "weight": "44kg",
            "stair": "Saber",
            "like": "我的祖国章西",
            "dislike": "抽签或者赌博，因为赢不了"},
    "241": {"name": "威廉退尔",
            "other_name": ["威廉", "开发者老公（夹带私货x"],
            "height": "175cm",
            "weight": "69kg",
            "stair": "Archer",
            "like": "进山，打猎，回家后有家人迎接",
            "dislike": "毫无意义自大的家伙，比如让人对自己帽子低头行礼的混账总督"},
    "242": {"name": "阿周那Alter",
            "other_name": ["狂黑鸭", "芭娜娜", "狂娜", "banana"],
            "height": "177cm",
            "weight": "82kg",
            "stair": "Berser",
            "like": "没有（因为断绝好恶",
            "dislike": "没有（理由同上"},
    "243": {"name": "马嘶",
            "other_name": ["马嘶"],
            "height": "188cm",
            "weight": "81kg",
            "stair": "Archer",
            "like": "战斗",
            "dislike": "战斗"},
    "244": {"name": "阿斯克勒庇俄斯",
            "other_name": ["医神"],
            "height": "170cm",
            "weight": "60kg",
            "stair": "Caster",
            "like": "医术的进步，希望给予那些命运遭诸神玩弄的人类以最起码的...",
            "dislike": "愚蠢的患者和愚蠢的诸神"},
    "245": {"name": "织田信长Avenger",
            "other_name": ["魔王信长"],
            "height": "？？？cm",
            "weight": "？？？kg",
            "stair": "Extra",
            "like": "美味的南蛮点心/铁炮/人类",
            "dislike": "一昧依靠神佛的人/遇事乱成一团什么都不做的家伙/寡淡的食物"},

}
