# file stubs/ogdf/ClusterPlanarizationLayout/ClusterPosition.py generated from structogdf_1_1_cluster_planarization_layout_1_1_cluster_position
import enum
from typing import *
from ogdf_python import ogdf, cpp
std = cpp.std
class ClusterPosition(object):

	m_height : float = ...

	m_maxx : float = ...

	m_maxy : float = ...

	m_minx : float = ...

	m_miny : float = ...

	m_width : float = ...
