from aioworkers.core.plugin import search_plugins as search_plugins
from typing import Any

logger: Any
ASGIApp: Any

class AsgiMiddleware:
    app: Any
    context: Any
    def __init__(self, app: ASGIApp, plugin: str = ..., context=...) -> None: ...
    async def __call__(self, scope, receive, send) -> None: ...
    async def lifespan(self, receive, send): ...
    async def startup(self) -> None: ...
    async def shutdown(self) -> None: ...
