from django.db.models import Model, IntegerField, AutoField, CharField, TextField, DateTimeField, DateField


class Clubs(Model):
    active = IntegerField()
    additional_file = CharField(max_length=255, blank=True, null=True)
    basket_id = IntegerField(blank=True, null=True)
    club_id = AutoField(primary_key=True)
    contact_id = IntegerField(blank=True, null=True)
    contact_id2 = IntegerField(blank=True, null=True)
    created_date = DateField(blank=True, null=True)
    edited_by_id = IntegerField(blank=True, null=True)
    interregion = IntegerField(blank=True, null=True)
    last_edit_date = DateTimeField(blank=True, null=True)
    league_id = IntegerField()
    logo1 = CharField(max_length=255, blank=True, null=True)
    logo2 = CharField(max_length=255, blank=True, null=True)
    name = CharField(max_length=40, blank=True, null=True)
    name_en = CharField(max_length=255)
    national = IntegerField()
    old_base_id = CharField(max_length=10, blank=True, null=True)
    optional_property = IntegerField(blank=True, null=True)
    photo = CharField(max_length=255)
    previous_id = IntegerField()
    region_id = IntegerField()
    shirt150_1 = CharField(max_length=255)
    shirt150_2 = CharField(max_length=255)
    shirt150_3 = CharField(max_length=255)
    shirt150_4 = CharField(max_length=255)
    shirt40_1 = CharField(max_length=255)
    shirt40_2 = CharField(max_length=255)
    shirt40_3 = CharField(max_length=255)
    shirt40_4 = CharField(max_length=255)
    shirt_keeper1 = CharField(max_length=255)
    shirt_keeper2 = CharField(max_length=255)
    shirt_winter1 = CharField(max_length=255)
    shirt_winter2 = CharField(max_length=255)
    shirts = CharField(max_length=50, blank=True, null=True)
    shirts2 = CharField(max_length=50, blank=True, null=True)
    shirts_winter = CharField(max_length=50, blank=True, null=True)
    shirts_winter2 = CharField(max_length=50, blank=True, null=True)
    short_name = CharField(max_length=20, blank=True, null=True)
    shorts = CharField(max_length=50, blank=True, null=True)
    shorts2 = CharField(max_length=50, blank=True, null=True)
    site = CharField(max_length=30, blank=True, null=True)
    socks = CharField(max_length=50, blank=True, null=True)
    socks2 = CharField(max_length=50, blank=True, null=True)
    sort_by_number = IntegerField(blank=True, null=True)
    sorting_id = IntegerField(blank=True, null=True)
    superclub = IntegerField()
    text = TextField()
    unique_id = CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'clubs'
