# file stubs/ogdf/NodeMerge.py generated from structogdf_1_1_node_merge
import enum
from typing import *
from ogdf_python import ogdf, cpp
std = cpp.std
class NodeMerge(object):

	m_changedEdges : List[  int ] = ...

	m_changedNodes : List[  int ] = ...

	m_deletedEdges : List[  int ] = ...

	m_doubleWeight : Dict[  int, float ] = ...

	m_level : int = ...

	m_mergedNode : int = ...

	m_position : List[ std.pair[  int, float ] ] = ...

	m_radius : Dict[  int, float ] = ...

	m_source : Dict[  int,  int ] = ...

	m_target : Dict[  int,  int ] = ...

	def __init__(self, level : int) -> None:
		...

	def __destruct__(self) -> None:
		...
