# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tecton_proto/data/user_deployment_settings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tecton_proto.common import secret_pb2 as tecton__proto_dot_common_dot_secret__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tecton_proto/data/user_deployment_settings.proto',
  package='tecton_proto.data',
  syntax='proto2',
  serialized_options=b'\n\017com.tecton.dataP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0tecton_proto/data/user_deployment_settings.proto\x12\x11tecton_proto.data\x1a tecton_proto/common/secret.proto\"\xcd\x01\n\x16UserDeploymentSettings\x12G\n user_deployment_settings_version\x18\x01 \x01(\x05R\x1duserDeploymentSettingsVersion\x12R\n\x11\x64\x61tabricks_config\x18\x02 \x01(\x0b\x32#.tecton_proto.data.DatabricksConfigH\x00R\x10\x64\x61tabricksConfigB\x16\n\x14\x64\x61ta_platform_config\"q\n\x10\x44\x61tabricksConfig\x12#\n\rworkspace_url\x18\x01 \x01(\tR\x0cworkspaceUrl\x12\x38\n\tapi_token\x18\x02 \x01(\x0b\x32\x1b.tecton_proto.common.SecretR\x08\x61piTokenB\x13\n\x0f\x63om.tecton.dataP\x01'
  ,
  dependencies=[tecton__proto_dot_common_dot_secret__pb2.DESCRIPTOR,])




_USERDEPLOYMENTSETTINGS = _descriptor.Descriptor(
  name='UserDeploymentSettings',
  full_name='tecton_proto.data.UserDeploymentSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_deployment_settings_version', full_name='tecton_proto.data.UserDeploymentSettings.user_deployment_settings_version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='userDeploymentSettingsVersion', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='databricks_config', full_name='tecton_proto.data.UserDeploymentSettings.databricks_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='databricksConfig', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data_platform_config', full_name='tecton_proto.data.UserDeploymentSettings.data_platform_config',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=106,
  serialized_end=311,
)


_DATABRICKSCONFIG = _descriptor.Descriptor(
  name='DatabricksConfig',
  full_name='tecton_proto.data.DatabricksConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace_url', full_name='tecton_proto.data.DatabricksConfig.workspace_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='workspaceUrl', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='api_token', full_name='tecton_proto.data.DatabricksConfig.api_token', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='apiToken', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=426,
)

_USERDEPLOYMENTSETTINGS.fields_by_name['databricks_config'].message_type = _DATABRICKSCONFIG
_USERDEPLOYMENTSETTINGS.oneofs_by_name['data_platform_config'].fields.append(
  _USERDEPLOYMENTSETTINGS.fields_by_name['databricks_config'])
_USERDEPLOYMENTSETTINGS.fields_by_name['databricks_config'].containing_oneof = _USERDEPLOYMENTSETTINGS.oneofs_by_name['data_platform_config']
_DATABRICKSCONFIG.fields_by_name['api_token'].message_type = tecton__proto_dot_common_dot_secret__pb2._SECRET
DESCRIPTOR.message_types_by_name['UserDeploymentSettings'] = _USERDEPLOYMENTSETTINGS
DESCRIPTOR.message_types_by_name['DatabricksConfig'] = _DATABRICKSCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserDeploymentSettings = _reflection.GeneratedProtocolMessageType('UserDeploymentSettings', (_message.Message,), {
  'DESCRIPTOR' : _USERDEPLOYMENTSETTINGS,
  '__module__' : 'tecton_proto.data.user_deployment_settings_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.data.UserDeploymentSettings)
  })
_sym_db.RegisterMessage(UserDeploymentSettings)

DatabricksConfig = _reflection.GeneratedProtocolMessageType('DatabricksConfig', (_message.Message,), {
  'DESCRIPTOR' : _DATABRICKSCONFIG,
  '__module__' : 'tecton_proto.data.user_deployment_settings_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.data.DatabricksConfig)
  })
_sym_db.RegisterMessage(DatabricksConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
