from collections.abc import Generator
from typing import Any

cached_property = property
SIZE: Any
logger: Any

def import_name(stref: str): ...
def import_uri(obj): ...
def module_path(str_module, return_str: bool = ...): ...
def method_replicate_result(key): ...
def monkey_close(loop) -> Generator[None, None, None]: ...
def try_read(n, fd, timeout: int = ...): ...
def load_from_fd(fd): ...
def dump_to_fd(fd, data) -> None: ...
def mapping_repr(*maps, indent: int = ..., **kwargs): ...
def random_seed() -> None: ...
