# Generated by Django 3.1.7 on 2021-03-26 09:48

from django.db import migrations

import isc_common.fields.code_field


class Migration(migrations.Migration):
    dependencies = [
        ('tracker', '0085_auto_20210301_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages_importance',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
        migrations.AlterField(
            model_name='messages_state',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
    ]
