# Generated by Django 3.2.6 on 2021-08-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0092_alter_messages_files_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages_files',
            name='size',
            field=models.BigIntegerField(default=None, verbose_name='Размер файла'),
        ),
    ]
