
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-07T12:12:39-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5b81917099ac525b7c9cf0980db9eb8bc711440",
 "version": "0.3.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
