/* Generated by Nim Compiler v1.6.2 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <pthread.h>
#include <sys/types.h>
#define _GNU_SOURCE
#include <pthread.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw;
typedef struct tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw;
typedef struct tyObject_Thread__aCkJjuuA9audHPimgL5uPkg tyObject_Thread__aCkJjuuA9audHPimgL5uPkg;
typedef struct tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg;
typedef struct tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw;
typedef struct tyObject_ThreadPoolState__jN9benzGjAA9bryIHC1FGnZA tyObject_ThreadPoolState__jN9benzGjAA9bryIHC1FGnZA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tySequence__aNpJjaoUowCQc7fBn3wtDQ tySequence__aNpJjaoUowCQc7fBn3wtDQ;
typedef struct tyObject_ResourceExhaustedError__KFG1Y2EPzgtJWwuYhMD0Fw tyObject_ResourceExhaustedError__KFG1Y2EPzgtJWwuYhMD0Fw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Barrier Barrier;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef long long tyArray__xLtLuIT9aUkeKRzzMNC75Vw[6];
typedef long tyArray__xDUyu9aScDpt0JZLU6q9aEZQ[5];
struct tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw {
pthread_cond_t c;
pthread_mutex_t L;
NI counter;
};
typedef N_NIMCALL_PTR(void, tyProc__nSqh6BBL9cSEu9bcR48Z72QA) (tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* m);
struct tyObject_Thread__aCkJjuuA9audHPimgL5uPkg {
tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg* core;
unsigned long sys;
tyProc__nSqh6BBL9cSEu9bcR48Z72QA dataFn;
tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* data;
};
typedef tyObject_Thread__aCkJjuuA9audHPimgL5uPkg tyArray__VzdKMWiVX55GSra4f1dzcQ[256];
typedef tyObject_Thread__aCkJjuuA9audHPimgL5uPkg tyArray__0x6EwkmjS0RXNUNMOfdG9cg[32];
typedef N_NIMCALL_PTR(void, tyProc__fhqfcnDhIcLpBpSTVsWEZg) (void* thread, void* args);
typedef void* tyArray__2PWyF6nokyTyhzmcY3ON3w[128];
struct tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw {
NI len;
pthread_mutex_t lock;
tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw empty;
tyArray__2PWyF6nokyTyhzmcY3ON3w data;
};
struct tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw {
tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw taskArrived;
tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw taskStarted;
tyProc__fhqfcnDhIcLpBpSTVsWEZg f;
void* data;
NIM_BOOL ready;
NIM_BOOL initialized;
NIM_BOOL shutdown;
tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw q;
tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw readyForTask;
};
typedef tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw tyArray__5sGw9aMSI320X9cbYIDJFEOQ[256];
typedef tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw tyArray__W9bX58rb2TvIPS9bAprPBVQg[32];
struct tyObject_ThreadPoolState__jN9benzGjAA9bryIHC1FGnZA {
NI calls;
};
struct tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg {
char dummy;
};
typedef long tyArray__9bHLTaF4N8HxB6CQBwt9a68g[7];
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_ThreadType__H77H4LSuveAOpXr9bJRsUtw;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef long tyArray__TcvIiMAJvcwzNLsZkfnFnQ[25];
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef N_CLOSURE_PTR(void, TM__Qzgg5NBLvccay07XFph3Rw_8) (void);
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ResourceExhaustedError__KFG1Y2EPzgtJWwuYhMD0Fw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
typedef NU8 tyEnum_ThreadPoolAdvice__vD9cAMuSmfH29a9al5Q9cUZCig;
struct Barrier {
NI entered;
tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw cv;
NIM_ALIGN(64) NI left;
NIM_ALIGN(64) NIM_BOOL interest;
};
typedef int tyArray__hxJupwhxfpZMyjfyvw0J9ag[1];
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__aNpJjaoUowCQc7fBn3wtDQ {
  TGenericSeq Sup;
  tyProc__HzVCwACFYM9cx9aV62PdjtuA data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
static N_INLINE(void, initLock__coreZlocks_64)(pthread_mutex_t* lock);
N_LIB_PRIVATE N_NIMCALL(void, initSemaphore__pureZconcurrencyZthreadpool_9)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv);
static N_INLINE(void, initCond__coreZlocks_75)(pthread_cond_t* cond);
N_LIB_PRIVATE N_NIMCALL(void, setup__pureZconcurrencyZthreadpool_558)(void);
N_LIB_PRIVATE N_NIMCALL(NI, ncpicountProcessors)(void);
N_LIB_PRIVATE N_NOINLINE(void, activateWorkerThread__pureZconcurrencyZthreadpool_452)(NI i);
N_LIB_PRIVATE N_NIMCALL(void, createThread__pureZconcurrencyZthreadpool_461)(tyObject_Thread__aCkJjuuA9audHPimgL5uPkg* t, tyProc__nSqh6BBL9cSEu9bcR48Z72QA tp, tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* param);
N_LIB_PRIVATE N_NOCONV(void*, allocShared0Impl__system_1758)(NI size);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__systemZassertions_56)(NimStringDesc* msg);
N_LIB_PRIVATE N_NOCONV(void*, threadProcWrapper__pureZconcurrencyZthreadpool_482)(void* closure);
N_LIB_PRIVATE N_NIMCALL(void, threadProcWrapStackFrame__pureZconcurrencyZthreadpool_496)(tyObject_Thread__aCkJjuuA9audHPimgL5uPkg* thrd);
N_LIB_PRIVATE N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
N_LIB_PRIVATE N_NIMCALL(void, initGC__system_2685)(void);
N_LIB_PRIVATE N_NIMCALL(void, threadProcWrapDispatch__pureZconcurrencyZthreadpool_500)(tyObject_Thread__aCkJjuuA9audHPimgL5uPkg* thrd);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(void, genericDeepCopy)(void* dest, void* src, TNimType* mt);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(void, threadTrouble__system_2849)(void);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5839)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5801)(void* usr);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, decRef__system_5846)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5844)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5795)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, nimLeaveFinally)(void);
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(void, deallocOsPages__system_2848)(void);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, slave__pureZconcurrencyZthreadpool_331)(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w);
static N_INLINE(NI, atomicDec__system_2310)(NI* memLoc, NI x);
N_LIB_PRIVATE N_NIMCALL(void, nossleep)(NI milsecs);
N_LIB_PRIVATE N_NIMCALL(void, signal__pureZconcurrencyZthreadpool_19)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv);
static N_INLINE(void, acquire__coreZlocks_71)(pthread_mutex_t* lock);
static N_INLINE(void, release__coreZlocks_73)(pthread_mutex_t* lock);
static N_INLINE(void, signal__coreZlocks_82)(pthread_cond_t* cond);
N_LIB_PRIVATE N_NIMCALL(void, blockUntil__pureZconcurrencyZthreadpool_13)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv);
static N_INLINE(void, wait__coreZlocks_79)(pthread_cond_t* cond, pthread_mutex_t* lock);
N_LIB_PRIVATE N_NIMCALL(void, cleanFlowVars__pureZconcurrencyZthreadpool_116)(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w);
N_LIB_PRIVATE N_NIMCALL(void, nimGCunref)(void* p);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, selectWorker__pureZconcurrencyZthreadpool_84)(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w, tyProc__fhqfcnDhIcLpBpSTVsWEZg fn, void* data);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, cas__pureZconcurrencyZthreadpool_89)(NIM_BOOL* p, NIM_BOOL oldValue, NIM_BOOL newValue);
static N_INLINE(NIM_BOOL, tryAcquire__coreZlocks_68)(pthread_mutex_t* lock);
static N_INLINE(NI, atomicInc__system_2307)(NI* memLoc, NI x);
N_LIB_PRIVATE N_NIMCALL(tyEnum_ThreadPoolAdvice__vD9cAMuSmfH29a9al5Q9cUZCig, advice__pureZconcurrencyZcpuload_11)(tyObject_ThreadPoolState__jN9benzGjAA9bryIHC1FGnZA* s);
static N_INLINE(void, destroySemaphore__pureZconcurrencyZthreadpool_11)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv);
static N_INLINE(void, deinitCond__coreZlocks_77)(pthread_cond_t* cond);
static N_INLINE(void, deinitLock__coreZlocks_66)(pthread_mutex_t* lock);
STRING_LITERAL(TM__Qzgg5NBLvccay07XFph3Rw_2, "threads.nim(323, 14) `pthread_attr_init(a) == 0` ", 49);
STRING_LITERAL(TM__Qzgg5NBLvccay07XFph3Rw_3, "threads.nim(327, 15) `setstacksizeResult == 0` ", 47);
N_LIB_PRIVATE TNimType NTIworker__AqHEWWcw2VBFjoa2Hp8Akw_;
N_LIB_PRIVATE TNimType NTIsemaphore__sx9abLHOwgGDBH9bpoqw2ezw_;
extern TNimType NTIsyscondobj__keOjwH3s9bnYBEeyteQLwbw_;
extern TNimType NTIsyslockobj__9bxnxao7MiiLOwO9aLAh9a3og_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTIworkerproc__fhqfcnDhIcLpBpSTVsWEZg_;
extern TNimType NTIpointer__vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_;
N_LIB_PRIVATE TNimType NTItofreequeue__5COJP8EWIaAuXvZlDbQZmw_;
N_LIB_PRIVATE TNimType NTIarrayL48OO495055_pointerT__2PWyF6nokyTyhzmcY3ON3w_;
N_LIB_PRIVATE TNimType NTIptrworker__CyNApV6Mfiphj5eUnH5G1A_;
extern TNimType NTIrefresourceexhaustederror__M8bPR1OE5OXPYGyQdVHfTg_;
extern TNimType NTIresourceexhaustederror__KFG1Y2EPzgtJWwuYhMD0Fw_;
STRING_LITERAL(TM__Qzgg5NBLvccay07XFph3Rw_9, "cannot create thread", 20);
STRING_LITERAL(TM__Qzgg5NBLvccay07XFph3Rw_10, "threads.nim(330, 14) `pthread_attr_destroy(a) == 0` ", 52);
N_LIB_PRIVATE NI currentPoolSize__pureZconcurrencyZthreadpool_304;
N_LIB_PRIVATE NI maxPoolSize__pureZconcurrencyZthreadpool_305 = ((NI) 256);
N_LIB_PRIVATE NI minPoolSize__pureZconcurrencyZthreadpool_306 = ((NI) 4);
N_LIB_PRIVATE tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw gSomeReady__pureZconcurrencyZthreadpool_307;
N_LIB_PRIVATE tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* readyWorker__pureZconcurrencyZthreadpool_308;
N_LIB_PRIVATE pthread_mutex_t numSlavesLock__pureZconcurrencyZthreadpool_309;
N_LIB_PRIVATE NI numSlavesRunning__pureZconcurrencyZthreadpool_310;
N_LIB_PRIVATE NI numSlavesWaiting__pureZconcurrencyZthreadpool_311;
N_LIB_PRIVATE NIM_THREADVAR NIM_BOOL isSlave__pureZconcurrencyZthreadpool_312;
N_LIB_PRIVATE tyArray__VzdKMWiVX55GSra4f1dzcQ workers__pureZconcurrencyZthreadpool_369;
N_LIB_PRIVATE tyArray__0x6EwkmjS0RXNUNMOfdG9cg distinguished__pureZconcurrencyZthreadpool_372;
N_LIB_PRIVATE tyArray__5sGw9aMSI320X9cbYIDJFEOQ workersData__pureZconcurrencyZthreadpool_370;
N_LIB_PRIVATE tyArray__W9bX58rb2TvIPS9bAprPBVQg distinguishedData__pureZconcurrencyZthreadpool_373;
N_LIB_PRIVATE tyObject_ThreadPoolState__jN9benzGjAA9bryIHC1FGnZA state__pureZconcurrencyZthreadpool_576;
N_LIB_PRIVATE pthread_mutex_t stateLock__pureZconcurrencyZthreadpool_577;
N_LIB_PRIVATE pthread_mutex_t distinguishedLock__pureZconcurrencyZthreadpool_607;
extern NIM_THREADVAR tyEnum_ThreadType__H77H4LSuveAOpXr9bJRsUtw threadType__system_2813;
extern NIM_THREADVAR TSafePoint* excHandler__system_3091;
extern NIM_THREADVAR TSafePoint* excHandler__system_3091;
extern NIM_THREADVAR TSafePoint* excHandler__system_3091;
extern NIM_THREADVAR TSafePoint* excHandler__system_3091;
extern NIM_THREADVAR Exception* currException__system_3092;
extern NIM_THREADVAR Exception* currException__system_3092;
extern NIM_THREADVAR tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5738;
extern NIM_THREADVAR tySequence__aNpJjaoUowCQc7fBn3wtDQ* threadDestructionHandlers__system_2829;
extern NIM_THREADVAR tySequence__aNpJjaoUowCQc7fBn3wtDQ* threadDestructionHandlers__system_2829;
static N_INLINE(void, initLock__coreZlocks_64)(pthread_mutex_t* lock) {
	pthread_mutex_init(lock, ((pthread_mutexattr_t*) NIM_NIL));
}
static N_INLINE(void, initCond__coreZlocks_75)(pthread_cond_t* cond) {
	pthread_cond_init(cond, ((pthread_condattr_t*) NIM_NIL));
}
N_LIB_PRIVATE N_NIMCALL(void, initSemaphore__pureZconcurrencyZthreadpool_9)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	initCond__coreZlocks_75((&(*cv).c));
	initLock__coreZlocks_64((&(*cv).L));
}
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).prev = excHandler__system_3091;
	excHandler__system_3091 = s;
}
static N_INLINE(void, popSafePoint)(void) {
	excHandler__system_3091 = (*excHandler__system_3091).prev;
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__system_5839)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5801)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5844)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT__system_5795((&gch__system_5738.zct), c);
}
static N_INLINE(void, decRef__system_5846)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_5844(c);
	}
	LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5801(src);
		incRef__system_5839(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5801((*dest));
		decRef__system_5846(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException__system_3092), (*currException__system_3092).up);
}
N_LIB_PRIVATE N_NIMCALL(void, threadProcWrapDispatch__pureZconcurrencyZthreadpool_500)(tyObject_Thread__aCkJjuuA9audHPimgL5uPkg* thrd) {
	TSafePoint TM__Qzgg5NBLvccay07XFph3Rw_4;
	tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* volatile x;
	tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* T1_;
	pushSafePoint(&TM__Qzgg5NBLvccay07XFph3Rw_4);
	TM__Qzgg5NBLvccay07XFph3Rw_4.status = setjmp(TM__Qzgg5NBLvccay07XFph3Rw_4.context);
	if (TM__Qzgg5NBLvccay07XFph3Rw_4.status == 0) {
	x = (tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw*)0;
	T1_ = (tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw*)0;
	T1_ = (*thrd).data;
	genericDeepCopy((void*)(&x), (void*)(&T1_), (&NTIptrworker__CyNApV6Mfiphj5eUnH5G1A_));
	(*thrd).dataFn(x);
	popSafePoint();
	}
	else {
		popSafePoint();
		{
			TM__Qzgg5NBLvccay07XFph3Rw_4.status = 0;
			threadTrouble__system_2849();
			popCurrentException();
		}
	}
	{
		{
			NI iX60gensym66_;
			NI colontmp_;
			NI T6_;
			NI res;
			iX60gensym66_ = (NI)0;
			colontmp_ = (NI)0;
			T6_ = (threadDestructionHandlers__system_2829 ? threadDestructionHandlers__system_2829->Sup.len : 0);
			colontmp_ = (NI)(T6_ - ((NI) 1));
			res = colontmp_;
			{
				while (1) {
					if (!(((NI) 0) <= res)) goto LA8;
					iX60gensym66_ = res;
					threadDestructionHandlers__system_2829->data[iX60gensym66_].ClE_0? threadDestructionHandlers__system_2829->data[iX60gensym66_].ClP_0(threadDestructionHandlers__system_2829->data[iX60gensym66_].ClE_0):((TM__Qzgg5NBLvccay07XFph3Rw_8)(threadDestructionHandlers__system_2829->data[iX60gensym66_].ClP_0))();
					res -= ((NI) 1);
				} LA8: ;
			}
		}
		if (TM__Qzgg5NBLvccay07XFph3Rw_4.status != 0) nimLeaveFinally();
	}
	if (TM__Qzgg5NBLvccay07XFph3Rw_4.status != 0) reraiseException();
}
N_LIB_PRIVATE N_NIMCALL(void, threadProcWrapStackFrame__pureZconcurrencyZthreadpool_496)(tyObject_Thread__aCkJjuuA9audHPimgL5uPkg* thrd) {
	void* volatile p;
	p = (void*)0;
	nimGC_setStackBottom(((void*) ((&p))));
	initGC__system_2685();
	threadType__system_2813 = ((tyEnum_ThreadType__H77H4LSuveAOpXr9bJRsUtw) 1);
	threadProcWrapDispatch__pureZconcurrencyZthreadpool_500(thrd);
	deallocOsPages__system_2848();
}
N_LIB_PRIVATE N_NOCONV(void*, threadProcWrapper__pureZconcurrencyZthreadpool_482)(void* closure) {
	void* result;
	tyObject_Thread__aCkJjuuA9audHPimgL5uPkg* thrdX60gensym67_;
	tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg* coreX60gensym67_;
	result = (void*)0;
	thrdX60gensym67_ = ((tyObject_Thread__aCkJjuuA9audHPimgL5uPkg*) (closure));
	coreX60gensym67_ = (*thrdX60gensym67_).core;
	threadProcWrapStackFrame__pureZconcurrencyZthreadpool_496(thrdX60gensym67_);
	(*thrdX60gensym67_).core = ((tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg*) NIM_NIL);
	(*thrdX60gensym67_).dataFn = NIM_NIL;
	deallocShared(((void*) (coreX60gensym67_)));
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5801(p);
	decRef__system_5846(T1_);
}
N_LIB_PRIVATE N_NIMCALL(void, createThread__pureZconcurrencyZthreadpool_461)(tyObject_Thread__aCkJjuuA9audHPimgL5uPkg* t, tyProc__nSqh6BBL9cSEu9bcR48Z72QA tp, tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* param) {
	void* T1_;
	pthread_attr_t a;
	int setstacksizeResult;
	T1_ = (void*)0;
	T1_ = allocShared0Impl__system_1758(((NI) 1));
	(*t).core = ((tyObject_GcThread__hgJQSlfXDOK3SwSHjeZBXg*) (T1_));
	(*t).data = param;
	(*t).dataFn = tp;
	{
		int T4_;
		T4_ = (int)0;
		T4_ = pthread_attr_init((&a));
		if (!!((T4_ == ((NI32) 0)))) goto LA5_;
		failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__Qzgg5NBLvccay07XFph3Rw_2));
	}
	LA5_: ;
	setstacksizeResult = pthread_attr_setstacksize((&a), ((NI) 2093056));
	{
		if (!!((setstacksizeResult == ((NI32) 0)))) goto LA9_;
		failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__Qzgg5NBLvccay07XFph3Rw_3));
	}
	LA9_: ;
	{
		int T13_;
		tyObject_ResourceExhaustedError__KFG1Y2EPzgtJWwuYhMD0Fw* T16_;
		NimStringDesc* T17_;
		T13_ = (int)0;
		T13_ = pthread_create((&(*t).sys), (&a), threadProcWrapper__pureZconcurrencyZthreadpool_482, ((void*) (t)));
		if (!!((T13_ == ((NI32) 0)))) goto LA14_;
		T16_ = NIM_NIL;
		T16_ = (tyObject_ResourceExhaustedError__KFG1Y2EPzgtJWwuYhMD0Fw*) newObj((&NTIrefresourceexhaustederror__M8bPR1OE5OXPYGyQdVHfTg_), sizeof(tyObject_ResourceExhaustedError__KFG1Y2EPzgtJWwuYhMD0Fw));
		(*T16_).Sup.Sup.Sup.m_type = (&NTIresourceexhaustederror__KFG1Y2EPzgtJWwuYhMD0Fw_);
		(*T16_).Sup.Sup.name = "ResourceExhaustedError";
		T17_ = NIM_NIL;
		T17_ = (*T16_).Sup.Sup.message; (*T16_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__Qzgg5NBLvccay07XFph3Rw_9));
		if (T17_) nimGCunrefNoCycle(T17_);
		asgnRef((void**) (&(*T16_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T16_, "ResourceExhaustedError", "createThread", "threads.nim", 329);
	}
	LA14_: ;
	{
		int T20_;
		T20_ = (int)0;
		T20_ = pthread_attr_destroy((&a));
		if (!!((T20_ == ((NI32) 0)))) goto LA21_;
		failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__Qzgg5NBLvccay07XFph3Rw_10));
	}
	LA21_: ;
}
static N_INLINE(NI, atomicDec__system_2310)(NI* memLoc, NI x) {
	NI result;
	result = (NI)0;
	result = __atomic_sub_fetch(memLoc, x, __ATOMIC_RELAXED);
	return result;
}
static N_INLINE(void, acquire__coreZlocks_71)(pthread_mutex_t* lock) {
	pthread_mutex_lock(lock);
}
static N_INLINE(void, release__coreZlocks_73)(pthread_mutex_t* lock) {
	pthread_mutex_unlock(lock);
}
static N_INLINE(void, signal__coreZlocks_82)(pthread_cond_t* cond) {
	pthread_cond_signal(cond);
}
N_LIB_PRIVATE N_NIMCALL(void, signal__pureZconcurrencyZthreadpool_19)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	acquire__coreZlocks_71((&(*cv).L));
	(*cv).counter += ((NI) 1);
	release__coreZlocks_73((&(*cv).L));
	signal__coreZlocks_82((&(*cv).c));
}
static N_INLINE(void, wait__coreZlocks_79)(pthread_cond_t* cond, pthread_mutex_t* lock) {
	int T1_;
	T1_ = (int)0;
	T1_ = pthread_cond_wait(cond, lock);
	(void)(T1_);
}
N_LIB_PRIVATE N_NIMCALL(void, blockUntil__pureZconcurrencyZthreadpool_13)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	acquire__coreZlocks_71((&(*cv).L));
	{
		while (1) {
			if (!((*cv).counter <= ((NI) 0))) goto LA2;
			wait__coreZlocks_79((&(*cv).c), (&(*cv).L));
		} LA2: ;
	}
	(*cv).counter -= ((NI) 1);
	release__coreZlocks_73((&(*cv).L));
}
N_LIB_PRIVATE N_NIMCALL(void, cleanFlowVars__pureZconcurrencyZthreadpool_116)(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w) {
	tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw* q;
	q = (&(*w).q);
	acquire__coreZlocks_71((&(*q).lock));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < (*q).len)) goto LA3;
				i = i_2;
				if (((RootObj*) ((*q).data[(i)- 0]))) { nimGCunref(((RootObj*) ((*q).data[(i)- 0]))); }
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	(*q).len = ((NI) 0);
	release__coreZlocks_73((&(*q).lock));
}
N_LIB_PRIVATE N_NIMCALL(void, slave__pureZconcurrencyZthreadpool_331)(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w) {
	isSlave__pureZconcurrencyZthreadpool_312 = NIM_TRUE;
	{
		while (1) {
			TSafePoint TM__Qzgg5NBLvccay07XFph3Rw_11;
			TSafePoint TM__Qzgg5NBLvccay07XFph3Rw_12;
			{
				NI T7_;
				if (!(*w).shutdown) goto LA5_;
				(*w).shutdown = NIM_FALSE;
				T7_ = (NI)0;
				T7_ = atomicDec__system_2310((&currentPoolSize__pureZconcurrencyZthreadpool_304), ((NI) 1));
				{
					while (1) {
						{
							if (!!(((*w).data == NIM_NIL))) goto LA12_;
							nossleep(((NI) 100));
						}
						goto LA10_;
						LA12_: ;
						{
							goto LA8;
						}
						LA10_: ;
					}
				} LA8: ;
				goto LA1;
			}
			LA5_: ;
			__atomic_store_n((&(*w).ready), NIM_TRUE, __ATOMIC_SEQ_CST);
			readyWorker__pureZconcurrencyZthreadpool_308 = w;
			signal__pureZconcurrencyZthreadpool_19((&gSomeReady__pureZconcurrencyZthreadpool_307));
			blockUntil__pureZconcurrencyZthreadpool_13((&(*w).taskArrived));
			acquire__coreZlocks_71((&numSlavesLock__pureZconcurrencyZthreadpool_309));
			pushSafePoint(&TM__Qzgg5NBLvccay07XFph3Rw_11);
			TM__Qzgg5NBLvccay07XFph3Rw_11.status = setjmp(TM__Qzgg5NBLvccay07XFph3Rw_11.context);
			if (TM__Qzgg5NBLvccay07XFph3Rw_11.status == 0) {
			numSlavesRunning__pureZconcurrencyZthreadpool_310 += ((NI) 1);
			popSafePoint();
			}
			else {
				popSafePoint();
			}
			{
				release__coreZlocks_73((&numSlavesLock__pureZconcurrencyZthreadpool_309));
				if (TM__Qzgg5NBLvccay07XFph3Rw_11.status != 0) nimLeaveFinally();
			}
			if (TM__Qzgg5NBLvccay07XFph3Rw_11.status != 0) reraiseException();
			(*w).f(((void*) (w)), (*w).data);
			acquire__coreZlocks_71((&numSlavesLock__pureZconcurrencyZthreadpool_309));
			pushSafePoint(&TM__Qzgg5NBLvccay07XFph3Rw_12);
			TM__Qzgg5NBLvccay07XFph3Rw_12.status = setjmp(TM__Qzgg5NBLvccay07XFph3Rw_12.context);
			if (TM__Qzgg5NBLvccay07XFph3Rw_12.status == 0) {
			numSlavesRunning__pureZconcurrencyZthreadpool_310 -= ((NI) 1);
			popSafePoint();
			}
			else {
				popSafePoint();
			}
			{
				release__coreZlocks_73((&numSlavesLock__pureZconcurrencyZthreadpool_309));
				if (TM__Qzgg5NBLvccay07XFph3Rw_12.status != 0) nimLeaveFinally();
			}
			if (TM__Qzgg5NBLvccay07XFph3Rw_12.status != 0) reraiseException();
			{
				if (!!(((*w).q.len == ((NI) 0)))) goto LA21_;
				cleanFlowVars__pureZconcurrencyZthreadpool_116(w);
			}
			LA21_: ;
		}
	} LA1: ;
}
N_LIB_PRIVATE N_NOINLINE(void, activateWorkerThread__pureZconcurrencyZthreadpool_452)(NI i) {
	initSemaphore__pureZconcurrencyZthreadpool_9((&workersData__pureZconcurrencyZthreadpool_370[(i)- 0].taskArrived));
	initSemaphore__pureZconcurrencyZthreadpool_9((&workersData__pureZconcurrencyZthreadpool_370[(i)- 0].taskStarted));
	workersData__pureZconcurrencyZthreadpool_370[(i)- 0].initialized = NIM_TRUE;
	initSemaphore__pureZconcurrencyZthreadpool_9((&workersData__pureZconcurrencyZthreadpool_370[(i)- 0].q.empty));
	initLock__coreZlocks_64((&workersData__pureZconcurrencyZthreadpool_370[(i)- 0].q.lock));
	createThread__pureZconcurrencyZthreadpool_461((&workers__pureZconcurrencyZthreadpool_369[(i)- 0]), slave__pureZconcurrencyZthreadpool_331, (&workersData__pureZconcurrencyZthreadpool_370[(i)- 0]));
}
N_LIB_PRIVATE N_NIMCALL(void, setup__pureZconcurrencyZthreadpool_558)(void) {
	NI p;
	p = ncpicountProcessors();
	currentPoolSize__pureZconcurrencyZthreadpool_304 = ((p <= ((NI) 256)) ? p : ((NI) 256));
	readyWorker__pureZconcurrencyZthreadpool_308 = (&workersData__pureZconcurrencyZthreadpool_370[(((NI) 0))- 0]);
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < currentPoolSize__pureZconcurrencyZthreadpool_304)) goto LA3;
				i = i_2;
				activateWorkerThread__pureZconcurrencyZthreadpool_452(i);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, cas__pureZconcurrencyZthreadpool_89)(NIM_BOOL* p, NIM_BOOL oldValue, NIM_BOOL newValue) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = __atomic_compare_exchange_n (p, (&oldValue), newValue, NIM_FALSE, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, selectWorker__pureZconcurrencyZthreadpool_84)(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w, tyProc__fhqfcnDhIcLpBpSTVsWEZg fn, void* data) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = cas__pureZconcurrencyZthreadpool_89((&(*w).ready), NIM_TRUE, NIM_FALSE);
		if (!T3_) goto LA4_;
		(*w).data = data;
		(*w).f = fn;
		signal__pureZconcurrencyZthreadpool_19((&(*w).taskArrived));
		blockUntil__pureZconcurrencyZthreadpool_13((&(*w).taskStarted));
		result = NIM_TRUE;
	}
	LA4_: ;
	return result;
}
static N_INLINE(NIM_BOOL, tryAcquire__coreZlocks_68)(pthread_mutex_t* lock) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = pthread_mutex_trylock(lock);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NI, atomicInc__system_2307)(NI* memLoc, NI x) {
	NI result;
	result = (NI)0;
	result = __atomic_add_fetch(memLoc, x, __ATOMIC_RELAXED);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nimSpawn3)(tyProc__fhqfcnDhIcLpBpSTVsWEZg fn, void* data) {
{	{
		while (1) {
			{
				NIM_BOOL T5_;
				T5_ = (NIM_BOOL)0;
				T5_ = selectWorker__pureZconcurrencyZthreadpool_84(readyWorker__pureZconcurrencyZthreadpool_308, fn, data);
				if (!T5_) goto LA6_;
				goto BeforeRet_;
			}
			LA6_: ;
			{
				NI i;
				NI i_2;
				i = (NI)0;
				i_2 = ((NI) 0);
				{
					while (1) {
						if (!(i_2 < currentPoolSize__pureZconcurrencyZthreadpool_304)) goto LA10;
						i = i_2;
						{
							NIM_BOOL T13_;
							T13_ = (NIM_BOOL)0;
							T13_ = selectWorker__pureZconcurrencyZthreadpool_84((&workersData__pureZconcurrencyZthreadpool_370[(i)- 0]), fn, data);
							if (!T13_) goto LA14_;
							goto BeforeRet_;
						}
						LA14_: ;
						i_2 += ((NI) 1);
					} LA10: ;
				}
			}
			{
				NIM_BOOL T18_;
				T18_ = (NIM_BOOL)0;
				T18_ = (state__pureZconcurrencyZthreadpool_576.calls < maxPoolSize__pureZconcurrencyZthreadpool_305);
				if (T18_) goto LA19_;
				T18_ = ((NI)(state__pureZconcurrencyZthreadpool_576.calls & ((NI) 127)) == ((NI) 0));
				LA19_: ;
				if (!T18_) goto LA20_;
				{
					NIM_BOOL T24_;
					tyEnum_ThreadPoolAdvice__vD9cAMuSmfH29a9al5Q9cUZCig T41_;
					T24_ = (NIM_BOOL)0;
					T24_ = tryAcquire__coreZlocks_68((&stateLock__pureZconcurrencyZthreadpool_577));
					if (!T24_) goto LA25_;
					{
						tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w;
						NI T35_;
						if (!(currentPoolSize__pureZconcurrencyZthreadpool_304 < minPoolSize__pureZconcurrencyZthreadpool_306)) goto LA29_;
						{
							if (!!(workersData__pureZconcurrencyZthreadpool_370[(currentPoolSize__pureZconcurrencyZthreadpool_304)- 0].initialized)) goto LA33_;
							activateWorkerThread__pureZconcurrencyZthreadpool_452(currentPoolSize__pureZconcurrencyZthreadpool_304);
						}
						LA33_: ;
						w = (&workersData__pureZconcurrencyZthreadpool_370[(currentPoolSize__pureZconcurrencyZthreadpool_304)- 0]);
						T35_ = (NI)0;
						T35_ = atomicInc__system_2307((&currentPoolSize__pureZconcurrencyZthreadpool_304), ((NI) 1));
						{
							NIM_BOOL T38_;
							T38_ = (NIM_BOOL)0;
							T38_ = selectWorker__pureZconcurrencyZthreadpool_84(w, fn, data);
							if (!T38_) goto LA39_;
							release__coreZlocks_73((&stateLock__pureZconcurrencyZthreadpool_577));
							goto BeforeRet_;
						}
						LA39_: ;
					}
					LA29_: ;
					T41_ = (tyEnum_ThreadPoolAdvice__vD9cAMuSmfH29a9al5Q9cUZCig)0;
					T41_ = advice__pureZconcurrencyZcpuload_11((&state__pureZconcurrencyZthreadpool_576));
					switch (T41_) {
					case ((tyEnum_ThreadPoolAdvice__vD9cAMuSmfH29a9al5Q9cUZCig) 0):
					{
					}
					break;
					case ((tyEnum_ThreadPoolAdvice__vD9cAMuSmfH29a9al5Q9cUZCig) 1):
					{
						{
							tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w_2;
							NI T52_;
							if (!(currentPoolSize__pureZconcurrencyZthreadpool_304 < maxPoolSize__pureZconcurrencyZthreadpool_305)) goto LA46_;
							{
								if (!!(workersData__pureZconcurrencyZthreadpool_370[(currentPoolSize__pureZconcurrencyZthreadpool_304)- 0].initialized)) goto LA50_;
								activateWorkerThread__pureZconcurrencyZthreadpool_452(currentPoolSize__pureZconcurrencyZthreadpool_304);
							}
							LA50_: ;
							w_2 = (&workersData__pureZconcurrencyZthreadpool_370[(currentPoolSize__pureZconcurrencyZthreadpool_304)- 0]);
							T52_ = (NI)0;
							T52_ = atomicInc__system_2307((&currentPoolSize__pureZconcurrencyZthreadpool_304), ((NI) 1));
							{
								NIM_BOOL T55_;
								T55_ = (NIM_BOOL)0;
								T55_ = selectWorker__pureZconcurrencyZthreadpool_84(w_2, fn, data);
								if (!T55_) goto LA56_;
								release__coreZlocks_73((&stateLock__pureZconcurrencyZthreadpool_577));
								goto BeforeRet_;
							}
							LA56_: ;
						}
						LA46_: ;
					}
					break;
					case ((tyEnum_ThreadPoolAdvice__vD9cAMuSmfH29a9al5Q9cUZCig) 2):
					{
						{
							tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w_3;
							if (!(minPoolSize__pureZconcurrencyZthreadpool_306 < currentPoolSize__pureZconcurrencyZthreadpool_304)) goto LA61_;
							w_3 = (&workersData__pureZconcurrencyZthreadpool_370[((NI)(currentPoolSize__pureZconcurrencyZthreadpool_304 - ((NI) 1)))- 0]);
							(*w_3).shutdown = NIM_TRUE;
						}
						LA61_: ;
					}
					break;
					}
					release__coreZlocks_73((&stateLock__pureZconcurrencyZthreadpool_577));
				}
				LA25_: ;
			}
			LA20_: ;
			{
				TSafePoint TM__Qzgg5NBLvccay07XFph3Rw_13;
				if (!isSlave__pureZconcurrencyZthreadpool_312) goto LA65_;
				acquire__coreZlocks_71((&numSlavesLock__pureZconcurrencyZthreadpool_309));
				pushSafePoint(&TM__Qzgg5NBLvccay07XFph3Rw_13);
				TM__Qzgg5NBLvccay07XFph3Rw_13.status = setjmp(TM__Qzgg5NBLvccay07XFph3Rw_13.context);
				if (TM__Qzgg5NBLvccay07XFph3Rw_13.status == 0) {
				{
					if (!(numSlavesRunning__pureZconcurrencyZthreadpool_310 <= (NI)(numSlavesWaiting__pureZconcurrencyZthreadpool_311 + ((NI) 1)))) goto LA69_;
					{
						tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w_4;
						NI T79_;
						if (!(currentPoolSize__pureZconcurrencyZthreadpool_304 < maxPoolSize__pureZconcurrencyZthreadpool_305)) goto LA73_;
						{
							if (!!(workersData__pureZconcurrencyZthreadpool_370[(currentPoolSize__pureZconcurrencyZthreadpool_304)- 0].initialized)) goto LA77_;
							activateWorkerThread__pureZconcurrencyZthreadpool_452(currentPoolSize__pureZconcurrencyZthreadpool_304);
						}
						LA77_: ;
						w_4 = (&workersData__pureZconcurrencyZthreadpool_370[(currentPoolSize__pureZconcurrencyZthreadpool_304)- 0]);
						T79_ = (NI)0;
						T79_ = atomicInc__system_2307((&currentPoolSize__pureZconcurrencyZthreadpool_304), ((NI) 1));
						{
							NIM_BOOL T82_;
							T82_ = (NIM_BOOL)0;
							T82_ = selectWorker__pureZconcurrencyZthreadpool_84(w_4, fn, data);
							if (!T82_) goto LA83_;
							popSafePoint();
							release__coreZlocks_73((&numSlavesLock__pureZconcurrencyZthreadpool_309));
							goto BeforeRet_;
						}
						LA83_: ;
					}
					goto LA71_;
					LA73_: ;
					{
					}
					LA71_: ;
				}
				LA69_: ;
				numSlavesWaiting__pureZconcurrencyZthreadpool_311 += ((NI) 1);
				popSafePoint();
				}
				else {
					popSafePoint();
				}
				{
					release__coreZlocks_73((&numSlavesLock__pureZconcurrencyZthreadpool_309));
					if (TM__Qzgg5NBLvccay07XFph3Rw_13.status != 0) nimLeaveFinally();
				}
				if (TM__Qzgg5NBLvccay07XFph3Rw_13.status != 0) reraiseException();
			}
			LA65_: ;
			blockUntil__pureZconcurrencyZthreadpool_13((&gSomeReady__pureZconcurrencyZthreadpool_307));
			{
				TSafePoint TM__Qzgg5NBLvccay07XFph3Rw_14;
				if (!isSlave__pureZconcurrencyZthreadpool_312) goto LA90_;
				acquire__coreZlocks_71((&numSlavesLock__pureZconcurrencyZthreadpool_309));
				pushSafePoint(&TM__Qzgg5NBLvccay07XFph3Rw_14);
				TM__Qzgg5NBLvccay07XFph3Rw_14.status = setjmp(TM__Qzgg5NBLvccay07XFph3Rw_14.context);
				if (TM__Qzgg5NBLvccay07XFph3Rw_14.status == 0) {
				numSlavesWaiting__pureZconcurrencyZthreadpool_311 -= ((NI) 1);
				popSafePoint();
				}
				else {
					popSafePoint();
				}
				{
					release__coreZlocks_73((&numSlavesLock__pureZconcurrencyZthreadpool_309));
					if (TM__Qzgg5NBLvccay07XFph3Rw_14.status != 0) nimLeaveFinally();
				}
				if (TM__Qzgg5NBLvccay07XFph3Rw_14.status != 0) reraiseException();
			}
			LA90_: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nimArgsPassingDone)(void* p) {
	tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw* w;
	w = ((tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw*) (p));
	signal__pureZconcurrencyZthreadpool_19((&(*w).taskStarted));
}
static N_INLINE(void, deinitCond__coreZlocks_77)(pthread_cond_t* cond) {
	pthread_cond_destroy(cond);
}
static N_INLINE(void, deinitLock__coreZlocks_66)(pthread_mutex_t* lock) {
	pthread_mutex_destroy(lock);
}
static N_INLINE(void, destroySemaphore__pureZconcurrencyZthreadpool_11)(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw* cv) {
	deinitCond__coreZlocks_77((&(*cv).c));
	deinitLock__coreZlocks_66((&(*cv).L));
}
N_LIB_PRIVATE N_NIMCALL(void, closeBarrier)(Barrier* b) {
	__atomic_thread_fence(__ATOMIC_SEQ_CST);
	{
		if (!!(((*b).left == (*b).entered))) goto LA3_;
		initSemaphore__pureZconcurrencyZthreadpool_9((&(*b).cv));
		__atomic_thread_fence(__ATOMIC_SEQ_CST);
		(*b).interest = NIM_TRUE;
		__atomic_thread_fence(__ATOMIC_SEQ_CST);
		{
			while (1) {
				if (!!(((*b).left == (*b).entered))) goto LA6;
				blockUntil__pureZconcurrencyZthreadpool_13((&(*b).cv));
			} LA6: ;
		}
		destroySemaphore__pureZconcurrencyZthreadpool_11((&(*b).cv));
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, sync__pureZconcurrencyZthreadpool_612)(void) {
	{
		while (1) {
			NIM_BOOL allReady;
			allReady = NIM_TRUE;
			{
				NI i;
				NI i_2;
				i = (NI)0;
				i_2 = ((NI) 0);
				{
					while (1) {
						NIM_BOOL T10_;
						if (!(i_2 < currentPoolSize__pureZconcurrencyZthreadpool_304)) goto LA5;
						i = i_2;
						{
							if (!!(allReady)) goto LA8_;
							goto LA3;
						}
						LA8_: ;
						T10_ = (NIM_BOOL)0;
						T10_ = allReady;
						if (!(T10_)) goto LA11_;
						T10_ = workersData__pureZconcurrencyZthreadpool_370[(i)- 0].ready;
						LA11_: ;
						allReady = T10_;
						i_2 += ((NI) 1);
					} LA5: ;
				}
			} LA3: ;
			{
				if (!allReady) goto LA14_;
				goto LA1;
			}
			LA14_: ;
			nossleep(((NI) 100));
		}
	} LA1: ;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_threadpoolInit000)(void) {
{
	initLock__coreZlocks_64((&numSlavesLock__pureZconcurrencyZthreadpool_309));
	initSemaphore__pureZconcurrencyZthreadpool_9((&gSomeReady__pureZconcurrencyZthreadpool_307));
	initLock__coreZlocks_64((&stateLock__pureZconcurrencyZthreadpool_577));
	initLock__coreZlocks_64((&distinguishedLock__pureZconcurrencyZthreadpool_607));
	setup__pureZconcurrencyZthreadpool_558();
}
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_threadpoolDatInit000)(void) {
static TNimNode* TM__Qzgg5NBLvccay07XFph3Rw_5_9[9];
static TNimNode* TM__Qzgg5NBLvccay07XFph3Rw_6_3[3];
static TNimNode* TM__Qzgg5NBLvccay07XFph3Rw_7_4[4];
static TNimNode TM__Qzgg5NBLvccay07XFph3Rw_0[19];
NTIworker__AqHEWWcw2VBFjoa2Hp8Akw_.size = sizeof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw);
NTIworker__AqHEWWcw2VBFjoa2Hp8Akw_.align = NIM_ALIGNOF(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw);
NTIworker__AqHEWWcw2VBFjoa2Hp8Akw_.kind = 18;
NTIworker__AqHEWWcw2VBFjoa2Hp8Akw_.base = 0;
NTIworker__AqHEWWcw2VBFjoa2Hp8Akw_.flags = 1;
TM__Qzgg5NBLvccay07XFph3Rw_5_9[0] = &TM__Qzgg5NBLvccay07XFph3Rw_0[1];
NTIsemaphore__sx9abLHOwgGDBH9bpoqw2ezw_.size = sizeof(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw);
NTIsemaphore__sx9abLHOwgGDBH9bpoqw2ezw_.align = NIM_ALIGNOF(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw);
NTIsemaphore__sx9abLHOwgGDBH9bpoqw2ezw_.kind = 18;
NTIsemaphore__sx9abLHOwgGDBH9bpoqw2ezw_.base = 0;
NTIsemaphore__sx9abLHOwgGDBH9bpoqw2ezw_.flags = 1;
TM__Qzgg5NBLvccay07XFph3Rw_6_3[0] = &TM__Qzgg5NBLvccay07XFph3Rw_0[3];
TM__Qzgg5NBLvccay07XFph3Rw_0[3].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[3].offset = offsetof(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw, c);
TM__Qzgg5NBLvccay07XFph3Rw_0[3].typ = (&NTIsyscondobj__keOjwH3s9bnYBEeyteQLwbw_);
TM__Qzgg5NBLvccay07XFph3Rw_0[3].name = "c";
TM__Qzgg5NBLvccay07XFph3Rw_6_3[1] = &TM__Qzgg5NBLvccay07XFph3Rw_0[4];
TM__Qzgg5NBLvccay07XFph3Rw_0[4].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[4].offset = offsetof(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw, L);
TM__Qzgg5NBLvccay07XFph3Rw_0[4].typ = (&NTIsyslockobj__9bxnxao7MiiLOwO9aLAh9a3og_);
TM__Qzgg5NBLvccay07XFph3Rw_0[4].name = "L";
TM__Qzgg5NBLvccay07XFph3Rw_6_3[2] = &TM__Qzgg5NBLvccay07XFph3Rw_0[5];
TM__Qzgg5NBLvccay07XFph3Rw_0[5].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[5].offset = offsetof(tyObject_Semaphore__sx9abLHOwgGDBH9bpoqw2ezw, counter);
TM__Qzgg5NBLvccay07XFph3Rw_0[5].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__Qzgg5NBLvccay07XFph3Rw_0[5].name = "counter";
TM__Qzgg5NBLvccay07XFph3Rw_0[2].len = 3; TM__Qzgg5NBLvccay07XFph3Rw_0[2].kind = 2; TM__Qzgg5NBLvccay07XFph3Rw_0[2].sons = &TM__Qzgg5NBLvccay07XFph3Rw_6_3[0];
NTIsemaphore__sx9abLHOwgGDBH9bpoqw2ezw_.node = &TM__Qzgg5NBLvccay07XFph3Rw_0[2];
TM__Qzgg5NBLvccay07XFph3Rw_0[1].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[1].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, taskArrived);
TM__Qzgg5NBLvccay07XFph3Rw_0[1].typ = (&NTIsemaphore__sx9abLHOwgGDBH9bpoqw2ezw_);
TM__Qzgg5NBLvccay07XFph3Rw_0[1].name = "taskArrived";
TM__Qzgg5NBLvccay07XFph3Rw_5_9[1] = &TM__Qzgg5NBLvccay07XFph3Rw_0[6];
TM__Qzgg5NBLvccay07XFph3Rw_0[6].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[6].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, taskStarted);
TM__Qzgg5NBLvccay07XFph3Rw_0[6].typ = (&NTIsemaphore__sx9abLHOwgGDBH9bpoqw2ezw_);
TM__Qzgg5NBLvccay07XFph3Rw_0[6].name = "taskStarted";
TM__Qzgg5NBLvccay07XFph3Rw_5_9[2] = &TM__Qzgg5NBLvccay07XFph3Rw_0[7];
NTIworkerproc__fhqfcnDhIcLpBpSTVsWEZg_.size = sizeof(tyProc__fhqfcnDhIcLpBpSTVsWEZg);
NTIworkerproc__fhqfcnDhIcLpBpSTVsWEZg_.align = NIM_ALIGNOF(tyProc__fhqfcnDhIcLpBpSTVsWEZg);
NTIworkerproc__fhqfcnDhIcLpBpSTVsWEZg_.kind = 25;
NTIworkerproc__fhqfcnDhIcLpBpSTVsWEZg_.base = 0;
NTIworkerproc__fhqfcnDhIcLpBpSTVsWEZg_.flags = 3;
TM__Qzgg5NBLvccay07XFph3Rw_0[7].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[7].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, f);
TM__Qzgg5NBLvccay07XFph3Rw_0[7].typ = (&NTIworkerproc__fhqfcnDhIcLpBpSTVsWEZg_);
TM__Qzgg5NBLvccay07XFph3Rw_0[7].name = "f";
TM__Qzgg5NBLvccay07XFph3Rw_5_9[3] = &TM__Qzgg5NBLvccay07XFph3Rw_0[8];
TM__Qzgg5NBLvccay07XFph3Rw_0[8].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[8].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, data);
TM__Qzgg5NBLvccay07XFph3Rw_0[8].typ = (&NTIpointer__vr5DoT1jILTGdRlYv1OYpw_);
TM__Qzgg5NBLvccay07XFph3Rw_0[8].name = "data";
TM__Qzgg5NBLvccay07XFph3Rw_5_9[4] = &TM__Qzgg5NBLvccay07XFph3Rw_0[9];
TM__Qzgg5NBLvccay07XFph3Rw_0[9].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[9].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, ready);
TM__Qzgg5NBLvccay07XFph3Rw_0[9].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__Qzgg5NBLvccay07XFph3Rw_0[9].name = "ready";
TM__Qzgg5NBLvccay07XFph3Rw_5_9[5] = &TM__Qzgg5NBLvccay07XFph3Rw_0[10];
TM__Qzgg5NBLvccay07XFph3Rw_0[10].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[10].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, initialized);
TM__Qzgg5NBLvccay07XFph3Rw_0[10].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__Qzgg5NBLvccay07XFph3Rw_0[10].name = "initialized";
TM__Qzgg5NBLvccay07XFph3Rw_5_9[6] = &TM__Qzgg5NBLvccay07XFph3Rw_0[11];
TM__Qzgg5NBLvccay07XFph3Rw_0[11].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[11].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, shutdown);
TM__Qzgg5NBLvccay07XFph3Rw_0[11].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__Qzgg5NBLvccay07XFph3Rw_0[11].name = "shutdown";
TM__Qzgg5NBLvccay07XFph3Rw_5_9[7] = &TM__Qzgg5NBLvccay07XFph3Rw_0[12];
NTItofreequeue__5COJP8EWIaAuXvZlDbQZmw_.size = sizeof(tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw);
NTItofreequeue__5COJP8EWIaAuXvZlDbQZmw_.align = NIM_ALIGNOF(tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw);
NTItofreequeue__5COJP8EWIaAuXvZlDbQZmw_.kind = 18;
NTItofreequeue__5COJP8EWIaAuXvZlDbQZmw_.base = 0;
NTItofreequeue__5COJP8EWIaAuXvZlDbQZmw_.flags = 1;
TM__Qzgg5NBLvccay07XFph3Rw_7_4[0] = &TM__Qzgg5NBLvccay07XFph3Rw_0[14];
TM__Qzgg5NBLvccay07XFph3Rw_0[14].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[14].offset = offsetof(tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw, len);
TM__Qzgg5NBLvccay07XFph3Rw_0[14].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__Qzgg5NBLvccay07XFph3Rw_0[14].name = "len";
TM__Qzgg5NBLvccay07XFph3Rw_7_4[1] = &TM__Qzgg5NBLvccay07XFph3Rw_0[15];
TM__Qzgg5NBLvccay07XFph3Rw_0[15].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[15].offset = offsetof(tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw, lock);
TM__Qzgg5NBLvccay07XFph3Rw_0[15].typ = (&NTIsyslockobj__9bxnxao7MiiLOwO9aLAh9a3og_);
TM__Qzgg5NBLvccay07XFph3Rw_0[15].name = "lock";
TM__Qzgg5NBLvccay07XFph3Rw_7_4[2] = &TM__Qzgg5NBLvccay07XFph3Rw_0[16];
TM__Qzgg5NBLvccay07XFph3Rw_0[16].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[16].offset = offsetof(tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw, empty);
TM__Qzgg5NBLvccay07XFph3Rw_0[16].typ = (&NTIsemaphore__sx9abLHOwgGDBH9bpoqw2ezw_);
TM__Qzgg5NBLvccay07XFph3Rw_0[16].name = "empty";
TM__Qzgg5NBLvccay07XFph3Rw_7_4[3] = &TM__Qzgg5NBLvccay07XFph3Rw_0[17];
NTIarrayL48OO495055_pointerT__2PWyF6nokyTyhzmcY3ON3w_.size = sizeof(tyArray__2PWyF6nokyTyhzmcY3ON3w);
NTIarrayL48OO495055_pointerT__2PWyF6nokyTyhzmcY3ON3w_.align = NIM_ALIGNOF(tyArray__2PWyF6nokyTyhzmcY3ON3w);
NTIarrayL48OO495055_pointerT__2PWyF6nokyTyhzmcY3ON3w_.kind = 16;
NTIarrayL48OO495055_pointerT__2PWyF6nokyTyhzmcY3ON3w_.base = (&NTIpointer__vr5DoT1jILTGdRlYv1OYpw_);
NTIarrayL48OO495055_pointerT__2PWyF6nokyTyhzmcY3ON3w_.flags = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[17].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[17].offset = offsetof(tyObject_ToFreeQueue__5COJP8EWIaAuXvZlDbQZmw, data);
TM__Qzgg5NBLvccay07XFph3Rw_0[17].typ = (&NTIarrayL48OO495055_pointerT__2PWyF6nokyTyhzmcY3ON3w_);
TM__Qzgg5NBLvccay07XFph3Rw_0[17].name = "data";
TM__Qzgg5NBLvccay07XFph3Rw_0[13].len = 4; TM__Qzgg5NBLvccay07XFph3Rw_0[13].kind = 2; TM__Qzgg5NBLvccay07XFph3Rw_0[13].sons = &TM__Qzgg5NBLvccay07XFph3Rw_7_4[0];
NTItofreequeue__5COJP8EWIaAuXvZlDbQZmw_.node = &TM__Qzgg5NBLvccay07XFph3Rw_0[13];
TM__Qzgg5NBLvccay07XFph3Rw_0[12].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[12].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, q);
TM__Qzgg5NBLvccay07XFph3Rw_0[12].typ = (&NTItofreequeue__5COJP8EWIaAuXvZlDbQZmw_);
TM__Qzgg5NBLvccay07XFph3Rw_0[12].name = "q";
TM__Qzgg5NBLvccay07XFph3Rw_5_9[8] = &TM__Qzgg5NBLvccay07XFph3Rw_0[18];
TM__Qzgg5NBLvccay07XFph3Rw_0[18].kind = 1;
TM__Qzgg5NBLvccay07XFph3Rw_0[18].offset = offsetof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw, readyForTask);
TM__Qzgg5NBLvccay07XFph3Rw_0[18].typ = (&NTIsemaphore__sx9abLHOwgGDBH9bpoqw2ezw_);
TM__Qzgg5NBLvccay07XFph3Rw_0[18].name = "readyForTask";
TM__Qzgg5NBLvccay07XFph3Rw_0[0].len = 9; TM__Qzgg5NBLvccay07XFph3Rw_0[0].kind = 2; TM__Qzgg5NBLvccay07XFph3Rw_0[0].sons = &TM__Qzgg5NBLvccay07XFph3Rw_5_9[0];
NTIworker__AqHEWWcw2VBFjoa2Hp8Akw_.node = &TM__Qzgg5NBLvccay07XFph3Rw_0[0];
NTIptrworker__CyNApV6Mfiphj5eUnH5G1A_.size = sizeof(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw*);
NTIptrworker__CyNApV6Mfiphj5eUnH5G1A_.align = NIM_ALIGNOF(tyObject_Worker__AqHEWWcw2VBFjoa2Hp8Akw*);
NTIptrworker__CyNApV6Mfiphj5eUnH5G1A_.kind = 21;
NTIptrworker__CyNApV6Mfiphj5eUnH5G1A_.base = (&NTIworker__AqHEWWcw2VBFjoa2Hp8Akw_);
NTIptrworker__CyNApV6Mfiphj5eUnH5G1A_.flags = 3;
}

