/* Generated by Nim Compiler v1.6.2 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#include <stdio.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tySequence__ZE4llUwluRK7Sqp4MtXogQ tySequence__ZE4llUwluRK7Sqp4MtXogQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA;
typedef struct tyObject_DateTime__d9cK9cyKZPJJxFXUmx8dSpPw tyObject_DateTime__d9cK9cyKZPJJxFXUmx8dSpPw;
typedef struct tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw;
typedef struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg tyTuple__7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct Exception Exception;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tyObject_FileLoggercolonObjectType___IRs4hY6GNcXZ1akep9cf7jA tyObject_FileLoggercolonObjectType___IRs4hY6GNcXZ1akep9cf7jA;
typedef struct tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef NU8 tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ {
  RootObj Sup;
tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg levelThreshold;
NimStringDesc* fmtStr;
};
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA {
  tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ Sup;
NIM_BOOL useStderr;
};
typedef NU8 tyEnum_WeekDay__SVfemTA9aCOyua2TJYa6yBg;
struct tyObject_DateTime__d9cK9cyKZPJJxFXUmx8dSpPw {
  RootObj Sup;
NI nanosecond;
NI second;
NI minute;
NI hour;
NI monthdayZero;
NI monthZero;
NI year;
tyEnum_WeekDay__SVfemTA9aCOyua2TJYa6yBg weekday;
NI yearday;
NIM_BOOL isDst;
tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw* timezone;
NI utcOffset;
};
struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef NimStringDesc* tyArray__uTUOefOZpRbrah39bBH8rtw[8];
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef long tyArray__TcvIiMAJvcwzNLsZkfnFnQ[25];
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
};
typedef NimStringDesc* tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
typedef long tyArray__xDUyu9aScDpt0JZLU6q9aEZQ[5];
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
struct tyObject_FileLoggercolonObjectType___IRs4hY6GNcXZ1akep9cf7jA {
  tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ Sup;
FILE* file;
};
typedef NU8 tyEnum_FileMode__ZJfK20XeZ9bv2j1pZjw9aswg;
struct tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g {
  tyObject_FileLoggercolonObjectType___IRs4hY6GNcXZ1akep9cf7jA Sup;
NI maxLines;
NI curLine;
NimStringDesc* baseName;
tyEnum_FileMode__ZJfK20XeZ9bv2j1pZjw9aswg baseMode;
NI logFiles;
NI bufSize;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__ZE4llUwluRK7Sqp4MtXogQ {
  TGenericSeq Sup;
  tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ* data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef__WMDZAmMy1jpL9cg9ccJjI2LQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence__ZE4llUwluRK7Sqp4MtXogQ)(void* p, NI op);
static N_NIMCALL(void, TM__7EbqAVTAsJVrNKIE9b0UU9bA_6)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(void, log__pureZlogging_103)(tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ* logger, tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, log__pureZlogging_108)(tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA* logger, tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, substituteLog__pureZlogging_66)(NimStringDesc* frmt, tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosgetAppFilename)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem__system_1735)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, ntgetDateStr)(tyObject_DateTime__d9cK9cyKZPJJxFXUmx8dSpPw* dt);
N_LIB_PRIVATE N_NIMCALL(void, now__pureZtimes_1467)(tyObject_DateTime__d9cK9cyKZPJJxFXUmx8dSpPw* Result);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, ntgetClockStr)(tyObject_DateTime__d9cK9cyKZPJJxFXUmx8dSpPw* dt);
N_LIB_PRIVATE N_NIMCALL(void, nossplitFile)(NimStringDesc* path, tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* Result);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, writeLine__pureZlogging_122)(FILE* f, NimStringDesc** x, NI xLen_0);
N_LIB_PRIVATE N_NIMCALL(void, write__systemZio_205)(FILE* f, NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, flushFile__systemZio_226)(FILE* f);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5839)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5801)(void* usr);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, decRef__system_5846)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5844)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5795)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(void, log__pureZlogging_172)(tyObject_FileLoggercolonObjectType___IRs4hY6GNcXZ1akep9cf7jA* logger, tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, log__pureZlogging_328)(tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g* logger, tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, close__systemZio_217)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(void, rotate__pureZlogging_316)(tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g* logger);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_3)(NI x);
N_LIB_PRIVATE N_NIMCALL(void, nosmoveFile)(NimStringDesc* source, NimStringDesc* dest);
static N_INLINE(NimStringDesc*, slash___pureZos_121)(NimStringDesc* head, NimStringDesc* tail);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail);
N_LIB_PRIVATE N_NIMCALL(FILE*, open__systemZio_433)(NimStringDesc* filename, tyEnum_FileMode__ZJfK20XeZ9bv2j1pZjw9aswg mode, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
static N_NIMCALL(void, Marker_tyRef__j7jaC9bphBP0jQQCzNTCL0w)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, log__pureZlogging_107)(tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ* logger, tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
extern TNimType NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_;
N_LIB_PRIVATE TNimType NTIlogger58objecttype__9bhietBQiofDPLK3sBa0qPQ_;
N_LIB_PRIVATE TNimType NTIlevel__pW4mH4lipH6u2NKDGEWdGg_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
N_LIB_PRIVATE TNimType NTIlogger__WMDZAmMy1jpL9cg9ccJjI2LQ_;
N_LIB_PRIVATE TNimType NTIseqLloggerT__ZE4llUwluRK7Sqp4MtXogQ_;
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_7, "date", 4);
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_8, "time", 4);
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_9, "datetime", 8);
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_10, "app", 3);
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_11, "appdir", 6);
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_12, "appname", 7);
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_13, "levelid", 7);
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_14, "levelname", 9);
extern TNimType NTIdatetime__d9cK9cyKZPJJxFXUmx8dSpPw_;
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_15, "T", 1);
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_16, "DEBUG", 5);
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_17, "INFO", 4);
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_18, "NOTICE", 6);
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_19, "WARN", 4);
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_20, "ERROR", 5);
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_21, "FATAL", 5);
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_22, "NONE", 4);
N_LIB_PRIVATE NIM_CONST tyArray__uTUOefOZpRbrah39bBH8rtw LevelNames__pureZlogging_16 = {((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_16),
((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_16),
((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_17),
((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_18),
((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_19),
((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_20),
((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_21),
((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_22)}
;
STRING_LITERAL(TM__7EbqAVTAsJVrNKIE9b0UU9bA_24, "\012", 1);
extern TNimType NTIioerror__iLZrPn9anoh9ad1MmO0RczFw_;
N_LIB_PRIVATE TNimType NTIconsolelogger58objecttype__4w707i5soOx7A2LWkxurNA_;
extern TNimType NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_;
N_LIB_PRIVATE TNimType NTIconsolelogger__j7jaC9bphBP0jQQCzNTCL0w_;
N_LIB_PRIVATE TNimType NTIfilelogger58objecttype__IRs4hY6GNcXZ1akep9cf7jA_;
extern TNimType NTIfile__XBeRj4rw9bUuE7CB3DS1rgg_;
N_LIB_PRIVATE TNimType NTIrollingfilelogger58objecttype__RVbeT0aVEu0OfdbVn1KX0g_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTIfilemode__ZJfK20XeZ9bv2j1pZjw9aswg_;
N_LIB_PRIVATE NIM_THREADVAR tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level__pureZlogging_37;
N_LIB_PRIVATE NIM_THREADVAR tySequence__ZE4llUwluRK7Sqp4MtXogQ* handlers__pureZlogging_38;
extern NIM_THREADVAR TSafePoint* excHandler__system_3091;
extern NIM_THREADVAR TSafePoint* excHandler__system_3091;
extern NIM_THREADVAR TSafePoint* excHandler__system_3091;
extern NIM_THREADVAR TSafePoint* excHandler__system_3091;
extern NIM_THREADVAR Exception* currException__system_3092;
extern NIM_THREADVAR Exception* currException__system_3092;
extern NIM_THREADVAR Exception* currException__system_3092;
extern NIM_THREADVAR tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5738;
static N_NIMCALL(void, Marker_tyRef__WMDZAmMy1jpL9cg9ccJjI2LQ)(void* p, NI op) {
	tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ* a;
	a = (tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ*)p;
	nimGCvisit((void*)(*a).fmtStr, op);
}
static N_NIMCALL(void, Marker_tySequence__ZE4llUwluRK7Sqp4MtXogQ)(void* p, NI op) {
	tySequence__ZE4llUwluRK7Sqp4MtXogQ* a;
	NI T1_;
	a = (tySequence__ZE4llUwluRK7Sqp4MtXogQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, TM__7EbqAVTAsJVrNKIE9b0UU9bA_6)(void) {
	nimGCvisit((void*)handlers__pureZlogging_38, 0);
}
N_LIB_PRIVATE N_NIMCALL(void, log__pureZlogging_103)(tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ* logger, tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_1735)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
{	result = (NIM_BOOL)0;
	alen = (a ? a->Sup.len : 0);
	blen = (b ? b->Sup.len : 0);
	{
		if (!(alen == blen)) goto LA3_;
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		result = equalMem__system_1735(((void*) ((&a->data[((NI) 0)]))), ((void*) ((&b->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, substituteLog__pureZlogging_66)(NimStringDesc* frmt, tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
	NimStringDesc* result;
	NI msgLen;
	NI i_2;
	result = NIM_NIL;
	msgLen = ((NI) 0);
	{
		NimStringDesc** arg;
		NI i;
		arg = (NimStringDesc**)0;
		i = ((NI) 0);
		{
			while (1) {
				if (!(i < argsLen_0)) goto LA3;
				arg = (&args[i]);
				msgLen += ((*arg) ? (*arg)->Sup.len : 0);
				i += ((NI) 1);
			} LA3: ;
		}
	}
	result = rawNewString(((NI) ((NI)((NI)((frmt ? frmt->Sup.len : 0) + msgLen) + ((NI) 20)))));
	i_2 = ((NI) 0);
	{
		while (1) {
			if (!(i_2 < (frmt ? frmt->Sup.len : 0))) goto LA5;
			{
				if (!!(((NU8)(frmt->data[i_2]) == (NU8)(36)))) goto LA8_;
				result = addChar(result, frmt->data[i_2]);
				i_2 += ((NI) 1);
			}
			goto LA6_;
			LA8_: ;
			{
				NimStringDesc* v;
				NimStringDesc* app;
				i_2 += ((NI) 1);
				v = ((NimStringDesc*) NIM_NIL);
				app = nosgetAppFilename();
				{
					while (1) {
						NIM_BOOL T13_;
						NIM_CHAR T15_;
						T13_ = (NIM_BOOL)0;
						T13_ = (i_2 < (frmt ? frmt->Sup.len : 0));
						if (!(T13_)) goto LA14_;
						T13_ = (((NU8)(frmt->data[i_2])) >= ((NU8)(97)) && ((NU8)(frmt->data[i_2])) <= ((NU8)(122)) || ((NU8)(frmt->data[i_2])) >= ((NU8)(65)) && ((NU8)(frmt->data[i_2])) <= ((NU8)(90)) || ((NU8)(frmt->data[i_2])) >= ((NU8)(48)) && ((NU8)(frmt->data[i_2])) <= ((NU8)(57)) || ((NU8)(frmt->data[i_2])) == ((NU8)(95)));
						LA14_: ;
						if (!T13_) goto LA12;
						T15_ = (NIM_CHAR)0;
						T15_ = nsuToLowerAsciiChar(frmt->data[i_2]);
						v = addChar(v, T15_);
						i_2 += ((NI) 1);
					} LA12: ;
				}
				if (eqStrings(v, ((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_7))) goto LA16_;
				if (eqStrings(v, ((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_8))) goto LA17_;
				if (eqStrings(v, ((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_9))) goto LA18_;
				if (eqStrings(v, ((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_10))) goto LA19_;
				if (eqStrings(v, ((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_11))) goto LA20_;
				if (eqStrings(v, ((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_12))) goto LA21_;
				if (eqStrings(v, ((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_13))) goto LA22_;
				if (eqStrings(v, ((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_14))) goto LA23_;
				goto LA24_;
				LA16_: ;
				{
					tyObject_DateTime__d9cK9cyKZPJJxFXUmx8dSpPw T27_;
					NimStringDesc* T28_;
					nimZeroMem((void*)(&T27_), sizeof(tyObject_DateTime__d9cK9cyKZPJJxFXUmx8dSpPw));
					T27_.Sup.m_type = (&NTIdatetime__d9cK9cyKZPJJxFXUmx8dSpPw_);
					now__pureZtimes_1467((&T27_));
					T28_ = NIM_NIL;
					T28_ = ntgetDateStr((&T27_));
					result = resizeString(result, (T28_ ? T28_->Sup.len : 0) + 0);
appendString(result, T28_);
				}
				goto LA25_;
				LA17_: ;
				{
					tyObject_DateTime__d9cK9cyKZPJJxFXUmx8dSpPw T30_;
					NimStringDesc* T31_;
					nimZeroMem((void*)(&T30_), sizeof(tyObject_DateTime__d9cK9cyKZPJJxFXUmx8dSpPw));
					T30_.Sup.m_type = (&NTIdatetime__d9cK9cyKZPJJxFXUmx8dSpPw_);
					now__pureZtimes_1467((&T30_));
					T31_ = NIM_NIL;
					T31_ = ntgetClockStr((&T30_));
					result = resizeString(result, (T31_ ? T31_->Sup.len : 0) + 0);
appendString(result, T31_);
				}
				goto LA25_;
				LA18_: ;
				{
					NimStringDesc* T33_;
					tyObject_DateTime__d9cK9cyKZPJJxFXUmx8dSpPw T34_;
					NimStringDesc* T35_;
					tyObject_DateTime__d9cK9cyKZPJJxFXUmx8dSpPw T36_;
					NimStringDesc* T37_;
					T33_ = NIM_NIL;
					nimZeroMem((void*)(&T34_), sizeof(tyObject_DateTime__d9cK9cyKZPJJxFXUmx8dSpPw));
					T34_.Sup.m_type = (&NTIdatetime__d9cK9cyKZPJJxFXUmx8dSpPw_);
					now__pureZtimes_1467((&T34_));
					T35_ = NIM_NIL;
					T35_ = ntgetDateStr((&T34_));
					nimZeroMem((void*)(&T36_), sizeof(tyObject_DateTime__d9cK9cyKZPJJxFXUmx8dSpPw));
					T36_.Sup.m_type = (&NTIdatetime__d9cK9cyKZPJJxFXUmx8dSpPw_);
					now__pureZtimes_1467((&T36_));
					T37_ = NIM_NIL;
					T37_ = ntgetClockStr((&T36_));
					T33_ = rawNewString((T35_ ? T35_->Sup.len : 0) + (T37_ ? T37_->Sup.len : 0) + 1);
appendString(T33_, T35_);
appendString(T33_, ((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_15));
appendString(T33_, T37_);
					result = resizeString(result, (T33_ ? T33_->Sup.len : 0) + 0);
appendString(result, T33_);
				}
				goto LA25_;
				LA19_: ;
				{
					result = resizeString(result, (app ? app->Sup.len : 0) + 0);
appendString(result, app);
				}
				goto LA25_;
				LA20_: ;
				{
					tyTuple__7q7q3E6Oj24ZNVJb9aonhAg T40_;
					nimZeroMem((void*)(&T40_), sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
					nossplitFile(app, (&T40_));
					result = resizeString(result, (T40_.Field0 ? T40_.Field0->Sup.len : 0) + 0);
appendString(result, T40_.Field0);
				}
				goto LA25_;
				LA21_: ;
				{
					tyTuple__7q7q3E6Oj24ZNVJb9aonhAg T42_;
					nimZeroMem((void*)(&T42_), sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
					nossplitFile(app, (&T42_));
					result = resizeString(result, (T42_.Field1 ? T42_.Field1->Sup.len : 0) + 0);
appendString(result, T42_.Field1);
				}
				goto LA25_;
				LA22_: ;
				{
					result = addChar(result, LevelNames__pureZlogging_16[(level)- 0]->data[((NI) 0)]);
				}
				goto LA25_;
				LA23_: ;
				{
					result = resizeString(result, (LevelNames__pureZlogging_16[(level)- 0] ? LevelNames__pureZlogging_16[(level)- 0]->Sup.len : 0) + 0);
appendString(result, LevelNames__pureZlogging_16[(level)- 0]);
				}
				goto LA25_;
				LA24_: ;
				{
				}
				LA25_: ;
			}
			LA6_: ;
		} LA5: ;
	}
	{
		NimStringDesc** arg_2;
		NI i_3;
		arg_2 = (NimStringDesc**)0;
		i_3 = ((NI) 0);
		{
			while (1) {
				if (!(i_3 < argsLen_0)) goto LA48;
				arg_2 = (&args[i_3]);
				result = resizeString(result, ((*arg_2) ? (*arg_2)->Sup.len : 0) + 0);
appendString(result, (*arg_2));
				i_3 += ((NI) 1);
			} LA48: ;
		}
	}
	return result;
}
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).prev = excHandler__system_3091;
	excHandler__system_3091 = s;
}
static N_INLINE(void, writeLine__pureZlogging_122)(FILE* f, NimStringDesc** x, NI xLen_0) {
	{
		NimStringDesc** i;
		NI i_2;
		i = (NimStringDesc**)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < xLen_0)) goto LA3;
				i = (&x[i_2]);
				write__systemZio_205(f, (*i));
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	write__systemZio_205(f, ((NimStringDesc*) &TM__7EbqAVTAsJVrNKIE9b0UU9bA_24));
}
static N_INLINE(void, popSafePoint)(void) {
	excHandler__system_3091 = (*excHandler__system_3091).prev;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = NIM_NIL;
	result = currException__system_3092;
	return result;
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__system_5839)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5801)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5844)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT__system_5795((&gch__system_5738.zct), c);
}
static N_INLINE(void, decRef__system_5846)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_5844(c);
	}
	LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5801(src);
		incRef__system_5839(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5801((*dest));
		decRef__system_5846(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException__system_3092), (*currException__system_3092).up);
}
N_LIB_PRIVATE N_NIMCALL(void, log__pureZlogging_108)(tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA* logger, tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
	{
		NIM_BOOL T3_;
		NimStringDesc* ln;
		TSafePoint TM__7EbqAVTAsJVrNKIE9b0UU9bA_23;
		FILE* volatile handle;
		tyArray__nHXaesL0DJZHyVS07ARPRA T11_;
		T3_ = (NIM_BOOL)0;
		T3_ = (level__pureZlogging_37 <= level);
		if (!(T3_)) goto LA4_;
		T3_ = ((*logger).Sup.levelThreshold <= level);
		LA4_: ;
		if (!T3_) goto LA5_;
		ln = substituteLog__pureZlogging_66((*logger).Sup.fmtStr, level, args, argsLen_0);
		pushSafePoint(&TM__7EbqAVTAsJVrNKIE9b0UU9bA_23);
		TM__7EbqAVTAsJVrNKIE9b0UU9bA_23.status = setjmp(TM__7EbqAVTAsJVrNKIE9b0UU9bA_23.context);
		if (TM__7EbqAVTAsJVrNKIE9b0UU9bA_23.status == 0) {
		handle = stdout;
		{
			if (!(*logger).useStderr) goto LA9_;
			handle = stderr;
		}
		LA9_: ;
		nimZeroMem((void*)T11_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
		T11_[0] = copyString(ln);
		writeLine__pureZlogging_122(handle, T11_, 1);
		{
			if (!((96 &((NU8)1<<((NU)(level)&7U)))!=0)) goto LA14_;
			flushFile__systemZio_226(handle);
		}
		LA14_: ;
		popSafePoint();
		}
		else {
			popSafePoint();
			if (isObj(nimBorrowCurrentException()->Sup.m_type, (&NTIioerror__iLZrPn9anoh9ad1MmO0RczFw_))) {
				TM__7EbqAVTAsJVrNKIE9b0UU9bA_23.status = 0;
				popCurrentException();
			}
		}
		if (TM__7EbqAVTAsJVrNKIE9b0UU9bA_23.status != 0) reraiseException();
	}
	LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, log__pureZlogging_172)(tyObject_FileLoggercolonObjectType___IRs4hY6GNcXZ1akep9cf7jA* logger, tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
	{
		NIM_BOOL T3_;
		tyArray__nHXaesL0DJZHyVS07ARPRA T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = (level__pureZlogging_37 <= level);
		if (!(T3_)) goto LA4_;
		T3_ = ((*logger).Sup.levelThreshold <= level);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimZeroMem((void*)T7_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
		T7_[0] = substituteLog__pureZlogging_66((*logger).Sup.fmtStr, level, args, argsLen_0);
		writeLine__pureZlogging_122((*logger).file, T7_, 1);
		{
			if (!((96 &((NU8)1<<((NU)(level)&7U)))!=0)) goto LA10_;
			flushFile__systemZio_226((*logger).file);
		}
		LA10_: ;
	}
	LA5_: ;
}
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[(*dest).Sup.len] = c;
	(*dest).data[(NI)((*dest).Sup.len + ((NI) 1))] = 0;
	(*dest).Sup.len += ((NI) 1);
}
static N_INLINE(NimStringDesc*, slash___pureZos_121)(NimStringDesc* head, NimStringDesc* tail) {
	NimStringDesc* result;
	result = NIM_NIL;
	result = nosjoinPath(head, tail);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rotate__pureZlogging_316)(tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g* logger) {
	tyTuple__7q7q3E6Oj24ZNVJb9aonhAg T1_;
	NimStringDesc* dir;
	NimStringDesc* name;
	NimStringDesc* ext;
	nimZeroMem((void*)(&T1_), sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
	nossplitFile((*logger).baseName, (&T1_));
	dir = NIM_NIL;
	dir = T1_.Field0;
	name = NIM_NIL;
	name = T1_.Field1;
	ext = NIM_NIL;
	ext = T1_.Field2;
	{
		NI i;
		NI res;
		i = (NI)0;
		res = (*logger).logFiles;
		{
			while (1) {
				NimStringDesc* srcSuff;
				NimStringDesc* T12_;
				NimStringDesc* T13_;
				NimStringDesc* T14_;
				NimStringDesc* T15_;
				NimStringDesc* T16_;
				if (!(((NI) 0) <= res)) goto LA4;
				i = res;
				{
					NimStringDesc* T9_;
					NimStringDesc* T10_;
					if (!!((i == ((NI) 0)))) goto LA7_;
					T9_ = NIM_NIL;
					T10_ = NIM_NIL;
					T10_ = dollar___systemZdollars_3(i);
					T9_ = rawNewString((T10_ ? T10_->Sup.len : 0) + 1);
appendChar(T9_, 46);
appendString(T9_, T10_);
					srcSuff = T9_;
				}
				goto LA5_;
				LA7_: ;
				{
					srcSuff = ((NimStringDesc*) NIM_NIL);
				}
				LA5_: ;
				T12_ = NIM_NIL;
				T12_ = rawNewString((name ? name->Sup.len : 0) + (ext ? ext->Sup.len : 0) + (srcSuff ? srcSuff->Sup.len : 0) + 0);
appendString(T12_, name);
appendString(T12_, ext);
appendString(T12_, srcSuff);
				T13_ = NIM_NIL;
				T13_ = slash___pureZos_121(dir, T12_);
				T14_ = NIM_NIL;
				T15_ = NIM_NIL;
				T15_ = dollar___systemZdollars_3((NI)(i + ((NI) 1)));
				T14_ = rawNewString((name ? name->Sup.len : 0) + (ext ? ext->Sup.len : 0) + (T15_ ? T15_->Sup.len : 0) + 1);
appendString(T14_, name);
appendString(T14_, ext);
appendChar(T14_, 46);
appendString(T14_, T15_);
				T16_ = NIM_NIL;
				T16_ = slash___pureZos_121(dir, T14_);
				nosmoveFile(T13_, T16_);
				res -= ((NI) 1);
			} LA4: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(void, log__pureZlogging_328)(tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g* logger, tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
	{
		NIM_BOOL T3_;
		tyArray__nHXaesL0DJZHyVS07ARPRA T11_;
		T3_ = (NIM_BOOL)0;
		T3_ = (level__pureZlogging_37 <= level);
		if (!(T3_)) goto LA4_;
		T3_ = ((*logger).Sup.Sup.levelThreshold <= level);
		LA4_: ;
		if (!T3_) goto LA5_;
		{
			if (!((*logger).maxLines <= (*logger).curLine)) goto LA9_;
			close__systemZio_217((*logger).Sup.file);
			rotate__pureZlogging_316(logger);
			(*logger).logFiles += ((NI) 1);
			(*logger).curLine = ((NI) 0);
			(*logger).Sup.file = open__systemZio_433((*logger).baseName, (*logger).baseMode, (*logger).bufSize);
		}
		LA9_: ;
		nimZeroMem((void*)T11_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
		T11_[0] = substituteLog__pureZlogging_66((*logger).Sup.Sup.fmtStr, level, args, argsLen_0);
		writeLine__pureZlogging_122((*logger).Sup.file, T11_, 1);
		{
			if (!((96 &((NU8)1<<((NU)(level)&7U)))!=0)) goto LA14_;
			flushFile__systemZio_226((*logger).Sup.file);
		}
		LA14_: ;
		(*logger).curLine += ((NI) 1);
	}
	LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, addHandler__pureZlogging_410)(tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ* handler) {
	NI T1_;
	asgnRef((void**) (&handlers__pureZlogging_38), (tySequence__ZE4llUwluRK7Sqp4MtXogQ*) incrSeqV3((TGenericSeq*)(handlers__pureZlogging_38), (&NTIseqLloggerT__ZE4llUwluRK7Sqp4MtXogQ_)));
	T1_ = handlers__pureZlogging_38->Sup.len++;
	asgnRef((void**) (&handlers__pureZlogging_38->data[T1_]), handler);
}
static N_NIMCALL(void, Marker_tyRef__j7jaC9bphBP0jQQCzNTCL0w)(void* p, NI op) {
	tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA* a;
	a = (tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA*)p;
	nimGCvisit((void*)(*a).Sup.fmtStr, op);
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5801(p);
	decRef__system_5846(T1_);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA*, newConsoleLogger__pureZlogging_146)(tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg levelThreshold, NimStringDesc* fmtStr, NIM_BOOL useStderr) {
	tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA* result;
	NimStringDesc* T1_;
	result = NIM_NIL;
	result = (tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA*) newObj((&NTIconsolelogger__j7jaC9bphBP0jQQCzNTCL0w_), sizeof(tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA));
	(*result).Sup.Sup.m_type = (&NTIconsolelogger58objecttype__4w707i5soOx7A2LWkxurNA_);
	T1_ = NIM_NIL;
	T1_ = (*result).Sup.fmtStr; (*result).Sup.fmtStr = copyStringRC1(fmtStr);
	if (T1_) nimGCunrefNoCycle(T1_);
	(*result).Sup.levelThreshold = levelThreshold;
	(*result).useStderr = useStderr;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, logLoop__pureZlogging_359)(tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
	{
		tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ** logger;
		NI i;
		NI L;
		NI T2_;
		logger = (tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ**)0;
		i = ((NI) 0);
		T2_ = (handlers__pureZlogging_38 ? handlers__pureZlogging_38->Sup.len : 0);
		L = T2_;
		{
			while (1) {
				if (!(i < L)) goto LA4;
				logger = &handlers__pureZlogging_38->data[i];
				{
					if (!((*(*logger)).levelThreshold <= level)) goto LA7_;
					log__pureZlogging_107((*logger), level, args, argsLen_0);
				}
				LA7_: ;
				i += ((NI) 1);
			} LA4: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_loggingInit000)(void) {
{
	TFrame FR_; FR_.len = 0;

	nimRegisterThreadLocalMarker(TM__7EbqAVTAsJVrNKIE9b0UU9bA_6);

}/* preInitProc end */
{
}
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_loggingDatInit000)(void) {
static TNimNode* TM__7EbqAVTAsJVrNKIE9b0UU9bA_2_2[2];
static TNimNode* TM__7EbqAVTAsJVrNKIE9b0UU9bA_3_8[8];
NI TM__7EbqAVTAsJVrNKIE9b0UU9bA_5;
static char* NIM_CONST TM__7EbqAVTAsJVrNKIE9b0UU9bA_4[8] = {
"lvlAll", 
"lvlDebug", 
"lvlInfo", 
"lvlNotice", 
"lvlWarn", 
"lvlError", 
"lvlFatal", 
"lvlNone"};
static TNimNode* TM__7EbqAVTAsJVrNKIE9b0UU9bA_25_6[6];
static TNimNode TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[21];
NTIlogger58objecttype__9bhietBQiofDPLK3sBa0qPQ_.size = sizeof(tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ);
NTIlogger58objecttype__9bhietBQiofDPLK3sBa0qPQ_.align = NIM_ALIGNOF(tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ);
NTIlogger58objecttype__9bhietBQiofDPLK3sBa0qPQ_.kind = 17;
NTIlogger58objecttype__9bhietBQiofDPLK3sBa0qPQ_.base = (&NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_2_2[0] = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[1];
NTIlevel__pW4mH4lipH6u2NKDGEWdGg_.size = sizeof(tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg);
NTIlevel__pW4mH4lipH6u2NKDGEWdGg_.align = NIM_ALIGNOF(tyEnum_Level__pW4mH4lipH6u2NKDGEWdGg);
NTIlevel__pW4mH4lipH6u2NKDGEWdGg_.kind = 14;
NTIlevel__pW4mH4lipH6u2NKDGEWdGg_.base = 0;
NTIlevel__pW4mH4lipH6u2NKDGEWdGg_.flags = 3;
for (TM__7EbqAVTAsJVrNKIE9b0UU9bA_5 = 0; TM__7EbqAVTAsJVrNKIE9b0UU9bA_5 < 8; TM__7EbqAVTAsJVrNKIE9b0UU9bA_5++) {
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[TM__7EbqAVTAsJVrNKIE9b0UU9bA_5+2].kind = 1;
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[TM__7EbqAVTAsJVrNKIE9b0UU9bA_5+2].offset = TM__7EbqAVTAsJVrNKIE9b0UU9bA_5;
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[TM__7EbqAVTAsJVrNKIE9b0UU9bA_5+2].name = TM__7EbqAVTAsJVrNKIE9b0UU9bA_4[TM__7EbqAVTAsJVrNKIE9b0UU9bA_5];
TM__7EbqAVTAsJVrNKIE9b0UU9bA_3_8[TM__7EbqAVTAsJVrNKIE9b0UU9bA_5] = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[TM__7EbqAVTAsJVrNKIE9b0UU9bA_5+2];
}
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[10].len = 8; TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[10].kind = 2; TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[10].sons = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_3_8[0];
NTIlevel__pW4mH4lipH6u2NKDGEWdGg_.node = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[10];
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[1].kind = 1;
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[1].offset = offsetof(tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ, levelThreshold);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[1].typ = (&NTIlevel__pW4mH4lipH6u2NKDGEWdGg_);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[1].name = "levelThreshold";
TM__7EbqAVTAsJVrNKIE9b0UU9bA_2_2[1] = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[11];
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[11].kind = 1;
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[11].offset = offsetof(tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ, fmtStr);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[11].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[11].name = "fmtStr";
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[0].len = 2; TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[0].kind = 2; TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[0].sons = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_2_2[0];
NTIlogger58objecttype__9bhietBQiofDPLK3sBa0qPQ_.node = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[0];
NTIlogger__WMDZAmMy1jpL9cg9ccJjI2LQ_.size = sizeof(tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ*);
NTIlogger__WMDZAmMy1jpL9cg9ccJjI2LQ_.align = NIM_ALIGNOF(tyObject_LoggercolonObjectType___9bhietBQiofDPLK3sBa0qPQ*);
NTIlogger__WMDZAmMy1jpL9cg9ccJjI2LQ_.kind = 22;
NTIlogger__WMDZAmMy1jpL9cg9ccJjI2LQ_.base = (&NTIlogger58objecttype__9bhietBQiofDPLK3sBa0qPQ_);
NTIlogger__WMDZAmMy1jpL9cg9ccJjI2LQ_.marker = Marker_tyRef__WMDZAmMy1jpL9cg9ccJjI2LQ;
NTIseqLloggerT__ZE4llUwluRK7Sqp4MtXogQ_.size = sizeof(tySequence__ZE4llUwluRK7Sqp4MtXogQ*);
NTIseqLloggerT__ZE4llUwluRK7Sqp4MtXogQ_.align = NIM_ALIGNOF(tySequence__ZE4llUwluRK7Sqp4MtXogQ*);
NTIseqLloggerT__ZE4llUwluRK7Sqp4MtXogQ_.kind = 24;
NTIseqLloggerT__ZE4llUwluRK7Sqp4MtXogQ_.base = (&NTIlogger__WMDZAmMy1jpL9cg9ccJjI2LQ_);
NTIseqLloggerT__ZE4llUwluRK7Sqp4MtXogQ_.marker = Marker_tySequence__ZE4llUwluRK7Sqp4MtXogQ;
NTIconsolelogger58objecttype__4w707i5soOx7A2LWkxurNA_.size = sizeof(tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA);
NTIconsolelogger58objecttype__4w707i5soOx7A2LWkxurNA_.align = NIM_ALIGNOF(tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA);
NTIconsolelogger58objecttype__4w707i5soOx7A2LWkxurNA_.kind = 17;
NTIconsolelogger58objecttype__4w707i5soOx7A2LWkxurNA_.base = (&NTIlogger58objecttype__9bhietBQiofDPLK3sBa0qPQ_);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[12].kind = 1;
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[12].offset = offsetof(tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA, useStderr);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[12].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[12].name = "useStderr";
NTIconsolelogger58objecttype__4w707i5soOx7A2LWkxurNA_.node = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[12];
NTIconsolelogger__j7jaC9bphBP0jQQCzNTCL0w_.size = sizeof(tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA*);
NTIconsolelogger__j7jaC9bphBP0jQQCzNTCL0w_.align = NIM_ALIGNOF(tyObject_ConsoleLoggercolonObjectType___4w707i5soOx7A2LWkxurNA*);
NTIconsolelogger__j7jaC9bphBP0jQQCzNTCL0w_.kind = 22;
NTIconsolelogger__j7jaC9bphBP0jQQCzNTCL0w_.base = (&NTIconsolelogger58objecttype__4w707i5soOx7A2LWkxurNA_);
NTIconsolelogger__j7jaC9bphBP0jQQCzNTCL0w_.marker = Marker_tyRef__j7jaC9bphBP0jQQCzNTCL0w;
NTIfilelogger58objecttype__IRs4hY6GNcXZ1akep9cf7jA_.size = sizeof(tyObject_FileLoggercolonObjectType___IRs4hY6GNcXZ1akep9cf7jA);
NTIfilelogger58objecttype__IRs4hY6GNcXZ1akep9cf7jA_.align = NIM_ALIGNOF(tyObject_FileLoggercolonObjectType___IRs4hY6GNcXZ1akep9cf7jA);
NTIfilelogger58objecttype__IRs4hY6GNcXZ1akep9cf7jA_.kind = 17;
NTIfilelogger58objecttype__IRs4hY6GNcXZ1akep9cf7jA_.base = (&NTIlogger58objecttype__9bhietBQiofDPLK3sBa0qPQ_);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[13].kind = 1;
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[13].offset = offsetof(tyObject_FileLoggercolonObjectType___IRs4hY6GNcXZ1akep9cf7jA, file);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[13].typ = (&NTIfile__XBeRj4rw9bUuE7CB3DS1rgg_);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[13].name = "file";
NTIfilelogger58objecttype__IRs4hY6GNcXZ1akep9cf7jA_.node = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[13];
NTIrollingfilelogger58objecttype__RVbeT0aVEu0OfdbVn1KX0g_.size = sizeof(tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g);
NTIrollingfilelogger58objecttype__RVbeT0aVEu0OfdbVn1KX0g_.align = NIM_ALIGNOF(tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g);
NTIrollingfilelogger58objecttype__RVbeT0aVEu0OfdbVn1KX0g_.kind = 17;
NTIrollingfilelogger58objecttype__RVbeT0aVEu0OfdbVn1KX0g_.base = (&NTIfilelogger58objecttype__IRs4hY6GNcXZ1akep9cf7jA_);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_25_6[0] = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[15];
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[15].kind = 1;
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[15].offset = offsetof(tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g, maxLines);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[15].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[15].name = "maxLines";
TM__7EbqAVTAsJVrNKIE9b0UU9bA_25_6[1] = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[16];
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[16].kind = 1;
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[16].offset = offsetof(tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g, curLine);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[16].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[16].name = "curLine";
TM__7EbqAVTAsJVrNKIE9b0UU9bA_25_6[2] = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[17];
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[17].kind = 1;
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[17].offset = offsetof(tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g, baseName);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[17].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[17].name = "baseName";
TM__7EbqAVTAsJVrNKIE9b0UU9bA_25_6[3] = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[18];
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[18].kind = 1;
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[18].offset = offsetof(tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g, baseMode);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[18].typ = (&NTIfilemode__ZJfK20XeZ9bv2j1pZjw9aswg_);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[18].name = "baseMode";
TM__7EbqAVTAsJVrNKIE9b0UU9bA_25_6[4] = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[19];
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[19].kind = 1;
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[19].offset = offsetof(tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g, logFiles);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[19].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[19].name = "logFiles";
TM__7EbqAVTAsJVrNKIE9b0UU9bA_25_6[5] = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[20];
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[20].kind = 1;
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[20].offset = offsetof(tyObject_RollingFileLoggercolonObjectType___RVbeT0aVEu0OfdbVn1KX0g, bufSize);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[20].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[20].name = "bufSize";
TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[14].len = 6; TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[14].kind = 2; TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[14].sons = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_25_6[0];
NTIrollingfilelogger58objecttype__RVbeT0aVEu0OfdbVn1KX0g_.node = &TM__7EbqAVTAsJVrNKIE9b0UU9bA_0[14];
}

