# Generated by Django 3.1.7 on 2021-03-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sitelfl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recreated_urls',
            name='table_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
