# Generated by Django 3.2.7 on 2021-09-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitelfl', '0004_auto_20210916_1153'),
    ]

    operations = [
        migrations.RunSQL('''
        ALTER TABLE player_histories ADD comp_ids varchar(255) AFTER edited_by_id;
        CREATE INDEX player_histories_comp_ids_idx ON player_histories (comp_ids);
        UPDATE player_histories set comp_ids =  concat(match_id, '_', player_id, '_', club_id);
        ''')
    ]
