STS = {
    "ALTRV": "Flight operated in accordance with an altitude reservation",
    "ATFMX": "Flight approved for exemption from ATFM measures by the appropriate ATS authority",
    "FFR": "Fire-fighting",
    "FLTCK": "Flight check for calibration of navaids",
    "HAZMAT": "Flight carrying hazardous material",
    "HEAD": "Flight with Head of State status",
    "HOSP": "Medical flight declared by medical authorities",
    "HUM": "Flight operating on a humanitarian mission",
    "MARSA": "Flight for which a military entity assumes responsibility for separation of military aircraft",
    "MEDEVAC": "Life critical medical emergency evacuation",
    "NONRVSM": "Non-RVSM capable flight intending to operate in RVSM airspace",
    "SAR": "Flight engaged in a search and rescue mission",
    "STATE": "Flight engaged in military, customs or police services",
}

EQUIPMENT = {
    "A": "GBAS Landing System",
    "B": "LPV (APV with SBAS)",
    "C": "LORAN C",
    "D": "DME",
    "E1": "FMC WPR ACARS",
    "E2": "D-FIS ACARS",
    "E3": "PDC ACARS",
    "F": "ADF",
    "G": "GNSS",
    "H": "HF RTF",
    "I": "Inertial Navigation",
    "J1": "CPDLC ATN VDL Mode 2",
    "J2": "CPDLC FANS 1/A HFDL",
    "J3": "CPDLC FANS 1/A VDL Mode A",
    "J4": "PDLC FANS 1/A Mode 2",
    "J5": "CPDLC FANS 1/A SATCOM",
    "J7": "CPDLC FANS 1/A SATCOM (Iridium)",
    "K": "MLS",
    "L": "ILS",
    "M1": "ATC SATVOICE (INMARSAT)",
    "M3": "ATC RTF (Iridium)",
    "O": "VOR",
    "P1": "CPDLC RCP 400",
    "P2": "CPDLC RCP 240",
    "P3": "SATVOICE RCP 400",
    "R": "PBN Approved",
    "T": "TACAN",
    "U": "UHF RTF",
    "V": "VHF RTF",
    "W": "RVSM Approved",
    "X": "MNPS Approved",
    "Y": "VHF with 8.33 kHz Channel Spacing Capacity",
    "Z": "Other",
}
