# Generated by Django 4.0b1 on 2022-01-27 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osmflex", "0002_remove_roadmajor_access_remove_roadmajor_oneway_and_more"),
    ]

    operations = [migrations.RunSQL("CREATE SCHEMA osm;", reverse_sql="DROP SCHEMA osm CASCADE;")]
