# Generated by Django 3.2.6 on 2021-08-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0107_alter_users_images_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users_old_images',
            unique_together={('image', 'main_model', 'props', 'type', 'deleted_at')},
        ),
    ]
