
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-07T19:46:35-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "96060edbe03eae9412040a7211df94eaf61bc7a3",
 "version": "2022.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
