
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-04T11:39:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "022effc0381a6d9c0418592c727ee14b7eea2a1b",
 "version": "2587"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
