
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-08T17:51:05+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe4af6fbfa93363b187480834f3fc15dcf89b11e",
 "version": "2.5.28.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
