
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-02T10:10:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0526aa2fabea350dc26a50ed2e35832cbd7fdd8a",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
