from os.path import abspath, dirname

from setuptools import setup

LONG_DESCRIPTION = open(dirname(abspath(__file__)) + "/README.md", "r").read()


setup(
    name="boto3-stubs",
    version="1.20.50",
    packages=["boto3-stubs"],
    url="https://github.com/vemel/mypy_boto3_builder",
    license="MIT License",
    author="Vlad Emelianov",
    author_email="vlad.emelianov.nz@gmail.com",
    description="Type annotations for boto3 1.20.50 generated by mypy-boto3-builder 7.0.1",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Environment :: Console",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: Implementation :: CPython",
        "Typing :: Typed",
    ],
    keywords="boto3 type-annotations boto3-stubs mypy typeshed autocomplete",
    long_description=LONG_DESCRIPTION,
    long_description_content_type="text/markdown",
    package_data={"boto3-stubs": ["py.typed", "*.pyi", "*/*.pyi"]},
    python_requires=">=3.6",
    project_urls={
        "Documentation": "https://mypy-boto3-builder.readthedocs.io/en/latest/",
        "Source": "https://github.com/vemel/mypy_boto3_builder",
        "Tracker": "https://github.com/vemel/mypy_boto3_builder/issues",
    },
    install_requires=[
        "botocore-stubs",
        "typing-extensions; python_version < '3.9'",
    ],
    extras_require={
        "all": [
            "mypy-boto3-auditmanager>=1.20.0",
            "mypy-boto3-synthetics>=1.20.0",
            "mypy-boto3-ssm-incidents>=1.20.0",
            "mypy-boto3-events>=1.20.0",
        ],
        "essential": [],
        "auditmanager": ["mypy-boto3-auditmanager>=1.20.0"],
        "synthetics": ["mypy-boto3-synthetics>=1.20.0"],
        "ssm-incidents": ["mypy-boto3-ssm-incidents>=1.20.0"],
        "events": ["mypy-boto3-events>=1.20.0"],
    },
    zip_safe=False,
)
