# file stubs/ogdf/ClusterStructure.py generated from structogdf_1_1_cluster_structure
import enum
from typing import *
from ogdf_python import ogdf, cpp
std = cpp.std
class ClusterStructure(object):

	m_childCluster : Array[List[  int ] ] = ...

	m_clusterOf : NodeArray[  int ] = ...

	m_G : Graph = ...

	m_mainSiteCluster : List[  int ] = ...

	m_nodesIn : Array[SList[node] ] = ...

	m_parentCluster : Array[  int ] = ...

	@overload
	def __init__(self, _ : ClusterStructure) -> None:
		...

	@overload
	def __init__(self, G : Graph) -> None:
		...

	def initCluster(self, nCluster : int, parent : Array[  int ]) -> None:
		...

	def numberOfCluster(self) -> int:
		...

	def __Graph__(self) -> None:
		...

	def __assign__(self, _ : ClusterStructure) -> ClusterStructure:
		...

	def resetNodes(self, clusterIdx : int, nodes : List[node]) -> None:
		...

	def sortChildren(self, i : int, nodes : List[node], posList : Array[List[  int ] ], parentWeight : Array[ float ], dirFromParent : Array[ float ], mainSiteWeights : List[Tuple2[  int, float ] ]) -> None:
		...
