# file stubs/ogdf/CutvertexPreference.py generated from structogdf_1_1_cutvertex_preference
import enum
from typing import *
from ogdf_python import ogdf, cpp
std = cpp.std
class CutvertexPreference(object):

	m_b1 : int = ...

	m_b2 : int = ...

	m_len1 : int = ...

	m_len2 : int = ...

	m_v1 : node = ...

	m_v2 : node = ...

	def __init__(self, v1 : node, b1 : int, v2 : node, b2 : int) -> None:
		...
