# Generated by Django 3.2.10 on 2021-12-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocca_consent', '0002_auto_20210225_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectreconsent',
            name='tracking_identifier',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='subjectreconsent',
            name='tracking_identifier',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
