# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: systemathics/apis/services/intraday_analytics/v1/intraday_bollinger.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from systemathics.apis.type.shared.v1 import identifier_pb2 as systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_identifier__pb2
from systemathics.apis.type.shared.v1 import constraints_pb2 as systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_constraints__pb2
from systemathics.apis.type.shared.v1 import sampling_pb2 as systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_sampling__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='systemathics/apis/services/intraday_analytics/v1/intraday_bollinger.proto',
  package='systemathics.apis.services.intraday_analytics.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nIsystemathics/apis/services/intraday_analytics/v1/intraday_bollinger.proto\x12\x30systemathics.apis.services.intraday_analytics.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x31systemathics/apis/type/shared/v1/identifier.proto\x1a\x32systemathics/apis/type/shared/v1/constraints.proto\x1a/systemathics/apis/type/shared/v1/sampling.proto\"\x95\x02\n\x18IntradayBollingerRequest\x12@\n\nidentifier\x18\x01 \x01(\x0b\x32,.systemathics.apis.type.shared.v1.Identifier\x12<\n\x08sampling\x18\x02 \x01(\x0e\x32*.systemathics.apis.type.shared.v1.Sampling\x12\x42\n\x0b\x63onstraints\x18\x03 \x01(\x0b\x32-.systemathics.apis.type.shared.v1.Constraints\x12\x0e\n\x06length\x18\x04 \x01(\x05\x12\x11\n\tdeviation\x18\x05 \x01(\x01\x12\x12\n\nadjustment\x18\x06 \x01(\x08\"r\n\x19IntradayBollingerResponse\x12U\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32G.systemathics.apis.services.intraday_analytics.v1.IntradayBollingerData\"\xde\x01\n\x15IntradayBollingerData\x12.\n\ntime_stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05value\x18\x02 \x01(\x01\x12+\n\x05lower\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12+\n\x05upper\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12,\n\x06middle\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue2\xc9\x01\n\x18IntradayBollingerService\x12\xac\x01\n\x11IntradayBollinger\x12J.systemathics.apis.services.intraday_analytics.v1.IntradayBollingerRequest\x1aK.systemathics.apis.services.intraday_analytics.v1.IntradayBollingerResponseb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_identifier__pb2.DESCRIPTOR,systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_constraints__pb2.DESCRIPTOR,systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_sampling__pb2.DESCRIPTOR,])




_INTRADAYBOLLINGERREQUEST = _descriptor.Descriptor(
  name='IntradayBollingerRequest',
  full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerRequest.identifier', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sampling', full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerRequest.sampling', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='constraints', full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerRequest.constraints', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerRequest.length', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deviation', full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerRequest.deviation', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='adjustment', full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerRequest.adjustment', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=622,
)


_INTRADAYBOLLINGERRESPONSE = _descriptor.Descriptor(
  name='IntradayBollingerResponse',
  full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=624,
  serialized_end=738,
)


_INTRADAYBOLLINGERDATA = _descriptor.Descriptor(
  name='IntradayBollingerData',
  full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerData.time_stamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerData.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lower', full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerData.lower', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upper', full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerData.upper', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='middle', full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerData.middle', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=741,
  serialized_end=963,
)

_INTRADAYBOLLINGERREQUEST.fields_by_name['identifier'].message_type = systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_identifier__pb2._IDENTIFIER
_INTRADAYBOLLINGERREQUEST.fields_by_name['sampling'].enum_type = systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_sampling__pb2._SAMPLING
_INTRADAYBOLLINGERREQUEST.fields_by_name['constraints'].message_type = systemathics_dot_apis_dot_type_dot_shared_dot_v1_dot_constraints__pb2._CONSTRAINTS
_INTRADAYBOLLINGERRESPONSE.fields_by_name['data'].message_type = _INTRADAYBOLLINGERDATA
_INTRADAYBOLLINGERDATA.fields_by_name['time_stamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_INTRADAYBOLLINGERDATA.fields_by_name['lower'].message_type = google_dot_protobuf_dot_wrappers__pb2._DOUBLEVALUE
_INTRADAYBOLLINGERDATA.fields_by_name['upper'].message_type = google_dot_protobuf_dot_wrappers__pb2._DOUBLEVALUE
_INTRADAYBOLLINGERDATA.fields_by_name['middle'].message_type = google_dot_protobuf_dot_wrappers__pb2._DOUBLEVALUE
DESCRIPTOR.message_types_by_name['IntradayBollingerRequest'] = _INTRADAYBOLLINGERREQUEST
DESCRIPTOR.message_types_by_name['IntradayBollingerResponse'] = _INTRADAYBOLLINGERRESPONSE
DESCRIPTOR.message_types_by_name['IntradayBollingerData'] = _INTRADAYBOLLINGERDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntradayBollingerRequest = _reflection.GeneratedProtocolMessageType('IntradayBollingerRequest', (_message.Message,), {
  'DESCRIPTOR' : _INTRADAYBOLLINGERREQUEST,
  '__module__' : 'systemathics.apis.services.intraday_analytics.v1.intraday_bollinger_pb2'
  # @@protoc_insertion_point(class_scope:systemathics.apis.services.intraday_analytics.v1.IntradayBollingerRequest)
  })
_sym_db.RegisterMessage(IntradayBollingerRequest)

IntradayBollingerResponse = _reflection.GeneratedProtocolMessageType('IntradayBollingerResponse', (_message.Message,), {
  'DESCRIPTOR' : _INTRADAYBOLLINGERRESPONSE,
  '__module__' : 'systemathics.apis.services.intraday_analytics.v1.intraday_bollinger_pb2'
  # @@protoc_insertion_point(class_scope:systemathics.apis.services.intraday_analytics.v1.IntradayBollingerResponse)
  })
_sym_db.RegisterMessage(IntradayBollingerResponse)

IntradayBollingerData = _reflection.GeneratedProtocolMessageType('IntradayBollingerData', (_message.Message,), {
  'DESCRIPTOR' : _INTRADAYBOLLINGERDATA,
  '__module__' : 'systemathics.apis.services.intraday_analytics.v1.intraday_bollinger_pb2'
  # @@protoc_insertion_point(class_scope:systemathics.apis.services.intraday_analytics.v1.IntradayBollingerData)
  })
_sym_db.RegisterMessage(IntradayBollingerData)



_INTRADAYBOLLINGERSERVICE = _descriptor.ServiceDescriptor(
  name='IntradayBollingerService',
  full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=966,
  serialized_end=1167,
  methods=[
  _descriptor.MethodDescriptor(
    name='IntradayBollinger',
    full_name='systemathics.apis.services.intraday_analytics.v1.IntradayBollingerService.IntradayBollinger',
    index=0,
    containing_service=None,
    input_type=_INTRADAYBOLLINGERREQUEST,
    output_type=_INTRADAYBOLLINGERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INTRADAYBOLLINGERSERVICE)

DESCRIPTOR.services_by_name['IntradayBollingerService'] = _INTRADAYBOLLINGERSERVICE

# @@protoc_insertion_point(module_scope)
