__title__ = 'ampscz-lochness'
__description__ = 'Data aggregator'
__url__ = 'https://github.com/AMP-SCZ/lochness'
__version__ = 'v0.1.6'
__author__ = 'DPACC'
__author_email__ = 'kevincho@bwh.harvard.edu'
